### ISSUE TITLE
从远景围截lz到此……

### ISSUE THREAD

**Issue by shiweifu** [syscl/M3800#1]
关心几点：
1、续航，电池表现？发热大么？风扇声音吵么？
2、外接显示器是否正常？
3、待机和盒盖模式的表现
4、内置显示器能否开retina？
5、有啥不能接受小缺陷？

对这款电脑很感兴趣，不太喜欢rmbp的硬件，想长期使用，盼望lz回复。

**Comment by syscl** [comment]
1.续航好，Windows下面的使用时间6-8个小时，在OS X下也有4个小时的表现，我不是大电池版本。日常使用风扇从来不转，3800的散热不是RMBP可以比的，无论是在Windows下还是在OS X下。
2.HDMI外接正常，包括音频输出高清。
3.盒盖唤醒瞬间完成
4.可以，再patch了IOKit之后，OS X对这块3k(4k)屏幕实现了Retina的输出，非常的漂亮。
5.目前触控板驱动可以更完善，实现更顺滑的双指缩放（RehabMan的驱动不支持缩放，但是另一个支持）

P.S.现在出了M3800的升级版5010，你可以去参考一下。
真厉害，能够从论坛围观到这。

**Comment by shiweifu** [comment]
谢谢回复。

因为OS X对我来说是个硬性要求，我自己也不怎么喜欢MBP的硬件，所以想折腾下。你的帖子和提供的工具坚定了我的信心（因为工作比较忙，没太多时间折腾……）

看你的帖子，似乎这台机器不需要换任何硬件，只需要刷BIOS，除了屏蔽显卡，别的都能驱动？

我在淘宝上看到有好几个版本的M3800，有的显卡是K1100M，有的是GT750，有的CPU是4712，有的是4702，这个在安装过程中没区别吧？

要准备下手了！！

**Comment by syscl** [comment]
需要更换硬件的，更换网卡。当然你能够在香港dell官网选配dw1560的网卡。这样的话，m3800的优势就体现出来了，拆机仍旧保修，不过这台机子真的太好拆了，D面十颗螺丝拧下来拆机就结束了。

安装过程区别不大，不过750M对应着XPS 9530，似乎可以完全按照darkvoid的帖子来，M3800需要按照我的帖子来，才能实现盒盖睡眠。

关于CPU，4702和4712有点区别，4712的第一批次有盒盖死机（无论在什么系统下都一样）和恼人的电流声，后续的批次好像修复了这个问题，4702好像没有这些问题。总之，如果你在淘宝上买，最好问清楚。说来讽刺，同学在淘宝买的至今没坏，我自己买的3CC反而用了第一个星期就坏了。

Anyway，稍微折腾还是需要的，不过至今没当过机是真的。

**Comment by shiweifu** [comment]
OK，基本了解〜实在太感谢了。

我看到资源里有个A10_patched.bin，是不是我直接刷这个文件就可以了，不用再自己修改了？对BIOS版本有要求没？

哥们你同学买的是淘宝那种没官方保修的么？那种硬件应该是一样的吧？要是没啥区别我就下手啦，不然我就海淘去

**Comment by syscl** [comment]
这个文件M3800可以用。XPS9530貌似还是A09，需要进一步的修改（不确定两个文件是否一样）。

没有官方保修，不过可以去Dell付费保修和店保。硬件都是dell官方的，就是走的非官方渠道罢了。

**Comment by shiweifu** [comment]
好，那我就直接用这个文件刷了。十分感谢。

**Comment by shiweifu** [comment]
哥们，我已经装上啦，用的你很赞的脚本和修改后的BIOS。
显卡成功驱动并retina，wifi和蓝牙用了你推荐的那个型号，直接免驱。睡眠唤醒也不黑屏啦。

不过执行完安装脚本后，打印出一个错误日志：

./M3800andXPS15.sh: line 229: iasl: command not found
但之前几行的iasl的调用都没打出错误日志，而且iasl这个文件也在tools里。

可能和这个错误有关，然后现在的几个小问题是：
- 声卡没驱动
- 触摸板有时候失灵，用着用着可能就失灵了
- 盒盖没法睡眠，但在菜单上选择睡眠工作是正常的
- 显卡亮度没法调节，快捷键也不能用

---

除了这几点，已经很完美了。屏幕效果确实不错：）
而且这电脑似乎有3个内存插槽，这下爽了！

**Comment by Guanyunhan** [comment]
也是声卡没驱动

**Comment by shiweifu** [comment]
@Guanyunhan 
我10.11没引导起来，装的是10.10.5，不知道和这个有没有关系？

**Comment by Guanyunhan** [comment]
@shiweifu 
我10.11.1、10.10.5都能引导，但是声卡都没能驱动

**Comment by shiweifu** [comment]
@Guanyunhan 
你触摸板会用着用着失灵么？还有亮度能调节么？我的hdmi口输出会花，dp没问题

**Comment by shiweifu** [comment]
我QQ：52670590
可以交流一下 :)

**Comment by syscl** [comment]
我晚点回复 你们现在在路上

**Comment by Guanyunhan** [comment]
@shiweifu
HDMI没试过不知道

**Comment by Guanyunhan** [comment]
10.11.1
亮度不可调  电池图标打叉

**Comment by shiweifu** [comment]
@Guanyunhan 
10.11 我引导的时候提示

```
SMCProvider Error: Waiting for AppleSMC provider time out
could not get SMCProvider
```

声卡我用的那个毒药驱动合集装了一下 就好了。

**Comment by Guanyunhan** [comment]
@syscl 
声卡我用的是VooDooHDA驱动，但是ALC668死活驱动不起来，求大神指点

**Comment by Guanyunhan** [comment]
@syscl 
还有就是我是1080P版的，运行Finalstep.sh之后会闪屏，不运行就不会

**Comment by syscl** [comment]
显卡驱动上了吗？触摸板失灵是硬件问题，估计要换触摸板或者更新固件。

**Comment by syscl** [comment]
@Guanyunhan 1080p版本的不需要运行Finalstep.sh，因为那个是针对高分屏盒盖睡眠问题的。

声卡驱动不起来表明显卡也没有顺利驱动。

**Comment by Guanyunhan** [comment]
@syscl
抹掉重装了一次系统，声卡可以驱动了，但是这次蓝牙不能用了= =

**Comment by syscl** [comment]
@Guanyunhan 蓝牙好办，如果bluetoothinjector无效的话，将https://bitbucket.org/RehabMan/os-x-brcmpatchram/downloads里面最新的kext下载并安装到/S/L/E下面。

**Comment by Guanyunhan** [comment]
@syscl
问题都解决了，感谢

**Comment by syscl** [comment]
@Guanyunhan 我现在下载不下来，等会同步一些更新！

**Comment by Guanyunhan** [comment]
@syscl 
用了新脚本之后，按F11和F12都有小太阳，但是亮度不可调，10.11.1😢

**Comment by syscl** [comment]
@Guanyunhan 脚本输出了什么信息？

你现在计算机的具体驱动情况？

**Comment by Guanyunhan** [comment]
@syscl 
加个QQ方便联系13178338006😃
我把我的DSDT和SSDT都发给你

installation.log输出./Deploy.sh: line 236: iasl: command not found

**Comment by syscl** [comment]
@Guanyunhan 十分感谢你的反馈，问题已经修复，你在使用Deploy.sh之前先删除掉./M3800/下面的efi文件，重新执行一下。等待你的反馈。

**Comment by Guanyunhan** [comment]
@syscl 
1、亮度可调了
2、声音又没了（kext wizard里可以看到AppleHDA.kext已加载，版本号前面多了个9）

**Comment by syscl** [comment]
@Guanyunhan 显卡驱动了吗？

**Comment by Guanyunhan** [comment]
@syscl 驱动了的

**Comment by syscl** [comment]
在执行完脚本后，重启有再执行脚本一次吗？

**Comment by Guanyunhan** [comment]
我是1080P版本，再执行一次脚本的话电池图标会打叉

**Comment by syscl** [comment]
@Guanyunhan 你现在再试一次

**Comment by Guanyunhan** [comment]
@syscl 
闪屏

**Comment by syscl** [comment]
看来我需要单独查看你的情况.

在2015年12月09日 22:33，Guanyunhan 写道:

@syscl
闪屏

**Comment by Guanyunhan** [comment]
@syscl
我双系统，可以在win下删除efi/clover文件夹恢复

**Comment by syscl** [comment]
@Guanyunhan 我大概知道你的问题出在哪里了，在kext的patches上。我会专门为你的版本改脚本的。

**Comment by syscl** [comment]
@Guanyunhan 把我这个目录同步到你电脑上，删掉M3800下面的efi文件，然后修改显存为128MB，重新运行脚本试一试。这次应该没有问题了。

**Comment by Guanyunhan** [comment]
@syscl 按照步骤重做了一遍，依然没有声音，感觉是DSDT的问题，因为Kext Wizard里可以看到AppleHDA.kext已经加载（版本9272.50.31）

**Comment by syscl** [comment]
@Guanyunhan 重新在Clover下面dump改动后的dsdt吧，然后放到M3800/DSDT/raw下面执行一下。

脚本执行提示了什么结果呢？

**Comment by Guanyunhan** [comment]
@syscl 脚本没有输出错误，系统信息→音频里只有Intel 高清晰度音频(HDA)，设备那栏是空白的

**Comment by syscl** [comment]
@Guanyunhan 
Clover下面用boot without caches参数试一下。M3800声卡的驱动我记得一个重要的条件是显卡正常驱动。

**Comment by Guanyunhan** [comment]
所有问题都已解决，1080P版的朋友请区分使用plist文件哦

**Comment by shiweifu** [comment]
啊哈，更新了！

我晚上回去再重新patch一次！！
现在声音偶尔会自己破音一下，还有电量显示正常，但经常百分之90几就变成了红色。

**Comment by syscl** [comment]
@shiweifu 电量90红那个是驱动的问题，我也有，重启一下就好了，不影响使用。破音也是正常的，Mac下面也会有。
