### ISSUE TITLE
BIOS Step 4

### ISSUE THREAD

**Issue by SkyMacToch** [syscl/M3800#100]
Hello,

I'm not in QHD +, from what I see in the windows display setting, I am in Full-HD Touch 1920 * 1080, do you have another .bin?

And for AFUWINx64 if I understood correctly I must launch it in a CMD, can you tell me the exact command to launch it with the .bin?
And what happens after launching the command, my pc will restart and normally in the bios it should have other options?

**Comment by syscl** [comment]
Hello, I think FHD does not require a patched BIOS, but you have to apply MSR 0xE2 patch (aka Intel PM) in case to get over the kernel panic.
