### ISSUE TITLE
10.12.6 耳机无法驱动

### ISSUE THREAD

**Issue by zuoyuan333** [syscl/M3800#101]
10.12.6 耳机无法驱动 ，内置喇叭倒是可以，用了一周下来除了耳机其他是完美的，除了开机苹果进度条到一大半的时候闪一下。。
voodoohda我安装最新的后耳机和内置都是可以的，不过耳机的白噪音很大啊。重新刷Deploy.sh 后就又变成耳机不能驱动了。。  m3800文件夹下面的所有东西都是最新的。

**Comment by zuoyuan333** [comment]
有人刷10.14的么？怎么样？

**Comment by moxiecn** [comment]
@zuoyuan333 您的问题解决了吗？我在10.11(15G31)下面deploy.sh后内置声卡、耳机都是可以正常用的，但升级到10.12.6、10.12.4用同样的办法内置声卡无法驱动。困扰很久了。我的电脑配置是：M3800 I7-4702+16G。外接hdmi转VGA，可以使用HDMI上的声音输出。不知道为什么内置声卡在10.12.6下无法被 驱动。

**Comment by zuoyuan333** [comment]
@moxiecn 重新在git上面下东西，一套打下来内置声卡是可以的。。只是耳机不行。

**Comment by moxiecn** [comment]
@zuoyuan333 我用最新的deploy在10.12.6下无法直接驱动声卡，只有用voodoohda驱动才能驱动内置声卡，插上耳机杂音巨大。我又开了个102号问题，大神回复了，你参考下。

**Comment by zuoyuan333** [comment]
@moxiecn 请问你现在的耳机可以用了么?

**Comment by zuoyuan333** [comment]
@moxiecn 大哥,为啥我的10.11(15G31)执行了sh过后扬声器无声.插耳机无声,装了voodoohda也没用啊...囧

**Comment by syscl** [comment]
请尝试最新的版本。

**Comment by syscl** [comment]
请尝试最新的deploy.sh以及Clover目录，我已经修复了这些问题。

**Comment by zuoyuan333** [comment]
依然不行.并且将最新的clover放到efi目录会导致系统安装失败

**Comment by zuoyuan333** [comment]
@syscl 非常开心大神终于想起了m3800,感谢您的更新.
.我今天试了一下音频依然不行.并且将最新的clover放到efi目录会导致系统安装失败.用别人的clover安装好,再执行你的deploy.sh 后音频不能用. macos 10.12.6 
看到有人说m3800能完美黑苹果我才买的.到现在看来坑依然很多呢
再次感谢大神的更新

**Comment by syscl** [comment]
我到现在不知道为什么你们的会安装失败 我自己用已经没有问题了 得看你们的log才知道发生了什么

**Comment by moxiecn** [comment]
不知道是哪里的问题，我收到syscl的邮件后直接更新声卡总是不成功。后来全新安装10.14并升级到10.14.2后下载并执行deploy之后成功。声卡不再需要voohda即可驱动。现在HDMI，声卡等驱动完美了。谢谢大神的分享。不行你也再全新安装一次操作系统再试试看。

**Comment by moxiecn** [comment]
@syscl 
a failed in log.


[ ---> ]  Installing SSDT-m-M3800.aml to ./DSDT/compile...
[FAILED]  Copy SSDT-m-M3800.aml to ./DSDT/compile.
cp: /Users/moxieliu/M3800/DSDT/prepare/SSDT-m-M3800.aml: No such file or directory

**Comment by syscl** [comment]
Thank you I will remove this line of code because we don’t need it anymore.
