### ISSUE TITLE
No sound, brightness

### ISSUE THREAD

**Issue by froggr** [syscl/M3800#109]
as per #108 

The latest deploy script, and after copying the efi zip provided in #108, fixes many issues. however still experiencing:

* Lid closing doesn't work.
* touchpad multitouch isn't working properly (inconsistent touch recognition, inconsistent two finger recognition, scrolling stops or at times is not recognized)
* can't change screen brightness
* power management is poor - full battery lasts about 30 mins
* touchscreen doesn't work

On the last run of the deploy script, I receive this at the end when rebuilding kernel extension cache:
```
[ ---> ]  Installing external devices sleep patch...
/Library/LaunchDaemons/com.syscl.externalfix.sleepwatcher.plist: service already loaded
[ ---> ]  Rebuilding kernel extensions cache...
kill: 1060: No such process
Warning: /AppleInternal/Library/Extensions: No such file or directory
KernelCache ID: AAC9D39DAC8EE82D22A9458239008A47
update_dyld_shared_cache: warning: x86_64h skipping because of bad install name /System/Library/PrivateFrameworks/FaceCore.framework/Versions/A/Resources/fcl-fc-1.dat
update_dyld_shared_cache: warning: x86_64h skipping because of bad install name /System/Library/PrivateFrameworks/FaceCore.framework/Versions/A/Resources/fcl-fc-2.dat
update_dyld_shared_cache: warning: x86_64h skipping because of bad install name /System/Library/PrivateFrameworks/FaceCore.framework/Versions/A/Resources/fcl-fc-3.dat
update_dyld_shared_cache: warning: i386 skipping because of bad install name /System/Library/PrivateFrameworks/FaceCore.framework/Versions/A/Resources/fcl-fc-1.dat
update_dyld_shared_cache: warning: i386 skipping because of bad install name /System/Library/PrivateFrameworks/FaceCore.framework/Versions/A/Resources/fcl-fc-2.dat
update_dyld_shared_cache: warning: i386 skipping because of bad install name /System/Library/PrivateFrameworks/FaceCore.framework/Versions/A/Resources/fcl-fc-3.dat
update_dyld_shared_cache: i386 incorporating 630 OS dylibs, tracking 457 others, building closures for 248 executables
update_dyld_shared_cache: warning: x86_64h rejected from cached dylibs: /System/Library/PrivateFrameworks/CreateML.framework/Versions/A/CreateML (("Could not find dependency '/System/Library/PrivateFrameworks/TuriCore.framework/Versions/A/TuriCore'"))
update_dyld_shared_cache: x86_64h incorporating 1361 OS dylibs, tracking 1001 others, building closures for 2127 executables
[ Note ]  Congratulations! All operation has been completed.
[ Note ]  Reboot now. Then enjoy your OS X! -syscl/lighting/Yating Zhou @PCBeta.
```

**Comment by GuillaumeHullin** [comment]
Concerning the touchscreen https://github.com/syscl/M3800/issues/106#issuecomment-447650719

**Comment by syscl** [comment]
Please try the latest Clover in my repo.

**Comment by froggr** [comment]
I completely replaced my clover folder just to make sure I had the most recent clover version.

The latest script changes seems to allow the computer to go to sleep however still not when the lid closes. Brightness still will not change and the battery is draining very very quickly. Also touchpad is still not very usable. 

Here is the entire debug log:
[log_3jan19_0740.txt](https://github.com/syscl/M3800/files/2723713/log_3jan19_0740.txt)

**Comment by syscl** [comment]
Feel free to test the latest repo which add support for 10.15, resolve lid wake issue and multi touch support. :)
