### ISSUE TITLE
hi, syscl, can you help me to fix my xps15 9350

### ISSUE THREAD

**Issue by coopercoder** [syscl/M3800#11]
#10

**Amazing work!**
I install OS X step by step as what you said, and it worked great.
But there is still a little problem.
when i install OS X 10.10.3, the sound card works, though there is a little noise;

**But when i upgrade OS X to 10.11.4, the sound card does not work,**
can you help me, my QQ is **76751553**.

PS: I did not change the wifi card of my xps 9350.

**Comment by syscl** [comment]
OK, let's see whats going on;)

**Comment by chenpaijie** [comment]
Thanks for syscl help me to install  OS X . He almost spends  a day to help me. Really good job!

**Comment by coopercoder** [comment]
thanks a lot for your kindness help, now I get a almost perfect hackintosh.
Now the sound card works fine!
