### ISSUE TITLE
XPS15 9530安装界面屏幕花屏问题

### ISSUE THREAD

**Issue by geminird** [syscl/M3800#110]
大神，您好！
       我使用了您最新的Clover文件，通过U盘安装系统时，进入安装界面时，屏幕都是花的。我之前有一个安装了10.14.2的硬盘，使用这个硬盘，使用您的Clover替换了原来的Clover，然后进入系统，屏幕也全是花屏的，根本没法识别内容，不知道如何解决，在网上看帖子说部分机器需要把显存从1530M提升到2048M，但是我不知道如何配置，也不知道是不是这个原因，麻烦帮我诊断一下，谢谢！
      我电脑配置如下：XPS15 9530，CPU：4702HQ，显卡：HD4600集显 + GT750M独显，内存：16G，屏幕：3200*1800；

     后来我在配置文件中修改了平台ID（故意修改错误的ID），让系统没法驱动显卡（似乎是系统已经驱动了显卡才导致的花屏问题），才能无花屏的进入系统，但是此时没法驱动显卡，显存只有21M。

**Comment by geminird** [comment]
@syscl 大神，您好！刚刚电脑休眠了一下后，屏幕就好了（我具体的操作是：按下电源键两秒钟，这个时候屏幕会黑掉，然后再按一下电源键，屏幕点亮，这个时候屏幕就恢复正常了。屏幕黑掉后，我观察了一下，键盘灯是亮的，风扇也在转动，可能是休眠不正常吧。），很怪异，这种情况需要修改什么配置呢。
休眠后屏幕好了，但是又有了新的问题，耳机和蓝牙音箱用不了了。触摸屏好像也用不了，不知道是不是我之前装了一个触摸屏增强软件导致的。

**Comment by machangpeng** [comment]
10.14.2休眠可以正常使用了？我的10.14一直不行呢。耳机貌似是插在电脑上休眠时就会出问题，触摸屏一直就不能使用吧。

**Comment by geminird** [comment]
> 10.14.2休眠可以正常使用了？我的10.14一直不行呢。耳机貌似是插在电脑上休眠时就会出问题，触摸屏一直就不能使用吧。

应该是要重新运行一下Deploy.sh脚本。

还有，刚刚试了一下，好像也不是休眠。我具体的操作是：按下电源键两秒钟，这个时候屏幕会黑掉，然后再按一下电源键，屏幕点亮，这个时候屏幕就恢复正常了。屏幕黑掉后，我观察了一下，键盘灯是亮的，风扇也在转动，感觉确实不像休眠，或者说休眠不正常。

触摸屏以前都是可以用的，耳机之前用voodhd的，可以驱动电脑音箱，但是耳机是噪音，现在新的驱动已经可以驱动耳机和电脑喇叭了。

**Comment by geminird** [comment]
@syscl 大神，您好！屏幕开机花屏的问题已经解决了，我严格按照TonyMacx86上，关于XPS15 _9530的帖子设置了BIOS，花屏问题就OK了。休眠恢复后，电脑外放音箱与耳机也工作正常。但是触摸屏还是不能工作。_
具体链接如下：
https://www.tonymacx86.com/threads/guide-dell-xps-9530-using-clover-uefi.172859/
