### ISSUE TITLE
"Black Screen" problem - M3800 UHD

### ISSUE THREAD

**Issue by YenForYang** [syscl/M3800#113]
So I'm having this problem where everything goes smoothly until the very last moment of installing OS X.

Display works fine and perfectly up until immediately after the final setup screen: the *Setting up your Mac* message. The message appears after you have finished logging in, inputting all the settings and agreed to all the policies.

Then the screen goes dark. Not pitch black -- you can see clearly that the screen is still on. I can even change the brightness using the multimedia keys (note my F# keys default to their multimedia functions), so that the lowest brightness basically turns off the screen completely.

It's almost as if a blank screensaver, cranked down to ~0.5 second delay, is initiated. 

I say that because if I move my mouse very fast in circles so that the cursor hits the edge of the screen continuously, I can see the desktop perfectly with frequent flickering (I can see the desktop, with an unrecognized keyboard layout pop up message). 

Simply touching the mouse or moving it doesn't cause the screen to turn on at all usually. However, most of the time, if I press some key combo that causes some screen animation, the screen lights up for a split second. For example, alt tab seems to do this, (Fn + brightness down/F11) causes the screen to light up as well for some reason (pressing the key combo causes some sort of shift on the screen).

If I reboot using the power button, manually hit f12 to boot Mac OS X...

> (NOTE: I have to manually specify Mac OS X to boot from, otherwise I hit the following error message:
> ```
> Reboot and Select proper Boot device or Insert Boot Media in selected Boot device and press a key
> ```

...click "boot Mac OS X from mydrivename", I eventually reach the login screen and it is black (it flicks on and off for a split second, so I can confirm that I have reach the login). Hitting an arrow key and typing my password cause the screen to shine again to show I'm logging in for a split second, then I'm back at the desktop (screen dark).

Right now I'm writing this on my phone-- I'll update this post in 15 minutes when I reach my computer to give details on what I did leading up to the installation.

**Comment by YenForYang** [comment]
So what I did to install OS X. I'll try to go into as much detail as possible as I find this whole issue to be pretty obscure.

1-2. After downloading Mojave from the App Store, I used
```
sudo /Applications/Install\ macOS\ Mojave.app/Contents/Resources/createinstallmedia --downloadassets --volume /Volumes/TargetDriveForInstallMedia
```
to create the installation media from a 16 GB USB3.0 flash drive. 

3. Downloaded the *latest* (r4844) version of Clover, installed it into the drive setting
   - Clover for UEFI booting only
   - Install Clover in the ESP
   - Themes (all)
   - UEFI Drivers (all)
   - FileVault 2 UEFI Drivers (all)

4. I then *replaced* (deleted and copied) the `CLOVER` folder in the ESP with the one from your git repo.

5. I then flashed your [unlocked BIOS for A10 UHD](https://github.com/syscl/M3800/blob/M3800/unlocked%20BIOS/M3800_UHD_A10_patched.bin) using the AFUWINx64 tool in your repo on my M3800 (which has UHD, 4k touchscreen display)

6. I then did a Load Optimized Defaults from within Setup (F2), and set all the settings your readme. Loading the defaults was done in hopes of eliminating issues.
   - **NOTE:** I did *not* understand your note however:
     ```
     NOTE: Once you modify your settings in BIOS(especially Graphics Configuration in SA), you have to remove previous ACPI tables first, redump ACPI tables by press Fn+F4/F4 under Clover, and run deploy.sh again to patch your ACPI tables again.
     ```
     So I ended up doing nothing for that

7. Then I took the flash drive I created, plugged it in the M3800 and UEFI booted from it using F12 Boot options.
8. Reaching the clover menu (text is really pretty small here by the way), I select the flash drive to boot from, and proceed with the macOS X 10.14.2 installation.

**Comment by YenForYang** [comment]
So I found a relevant forum post -- I believe that this is the exact same issue that I'm having

https://www.tonymacx86.com/threads/my-dell-precision-m3800-is-playing-peekaboo-with-me.157928/

**Comment by caltor726** [comment]
I have similar issue with the same laptop. I managed to install everything and I can see it on HDMI monitor but the builtin screen does not stay.

Also, I could not flash the A10 UHD bios , the flasher gave me error

**here are my specs**

 Core i7-4712HQ 2.3GHz , 3,840 x 2,160 (4K) touch screen, 16GB RAM , SAMSUNG SSD SM871 2.5 7mm 512GB, Intel HD 4600/Nvidia Quadro K1100M 2GB graphics

**Comment by syscl** [comment]
feel free to try the latest repo which added 10.15 support.
