### ISSUE TITLE
XPS15 9530 使用DW1820A网卡无法启动系统

### ISSUE THREAD

**Issue by geminird** [syscl/M3800#114]
大神，你好。我的XPS15 9530上了一块博通的DW1820A网卡，换上这个网卡后无法启动了，使用-v 启动，提示问题:
kextd stall[0] 'BMC2045A0'
ACPIBatteryManager:WARNING! fCurrentCapacity > fMaxCapacity. adjust fCurrentCapacity from 54970, to 4834.
我把所有高通的驱动全部从Clover下去掉了，也没法启动，不知道这个网卡需要怎么驱动，麻烦指点，谢谢。

**Comment by syscl** [comment]
建议使用DW1830
