### ISSUE TITLE
10.14.2背光亮度无法调节

### ISSUE THREAD

**Issue by xuemingyang** [syscl/M3800#115]
大神您好, 使用了您的脚本, 效果非常好, 就是一点, 笔记本背光亮度无法调节, 太亮了. 希望加入亮度调节功能

**Comment by xuemingyang** [comment]
自己解决了, 用最新版的whateverGreen+SSDT-PNLF放进去搞定. 感谢大神脚本.

**Comment by syscl** [comment]
修复了，增加了10.15支持，尽情尝试。
