### ISSUE TITLE
Works with 10.14.3 but...

### ISSUE THREAD

**Issue by BaoSLi** [syscl/M3800#116]
Just installed 10.14.3 Mojave and most things work.  After using it for 2 weeks, I found 2 issues.  They're not show stoppers but would be nice if they work.

1.  Closing the lid doesn't put the laptop to sleep.  Not a big deal, I've been hitting Win+Alt+Pwr to put it to sleep before closing the lid.

2.  Sound doesn't work after wake.  A quick reboot will bring the sound back.

**Comment by Just-maple** [comment]
I have the same problem and I made it worked
How I get it worked:

1.I found system.log console a error when i close and open the lid

the log show that _Q15 and _Q16 methods had some problem

2.look up _Q15 and _Q16 in your dsdt and found it did relate to lid method

Method (_Q15, 0, NotSerialized) // _Qxx: EC Query
{
Store (0x15, P80H)
^^^IGPU.GLID (LIDM)
Notify (LID0, 0x80)
}

    Method (_Q16, 0, NotSerialized)  // _Qxx: EC Query
    {
        Store (0x16, P80H)
        ^^^IGPU.GLID (LIDM)
        Notify (LID0, 0x80)
    }

3.Try delete   ^^^IGPU.GLID (LIDM)  and reboot

4.Lid works!!!!

**Comment by Just-maple** [comment]
> Just installed 10.14.3 Mojave and most things work. After using it for 2 weeks, I found 2 issues. They're not show stoppers but would be nice if they work.
> 
> 1. Closing the lid doesn't put the laptop to sleep.  Not a big deal, I've been hitting Win+Alt+Pwr to put it to sleep before closing the lid.
> 2. Sound doesn't work after wake.  A quick reboot will bring the sound back.

I have the same lid  problem and I made it worked
How I get it worked:

1.I found system.log console a error when i close and open the lid

the log show that _Q15 and _Q16 methods had some problem

2.look up _Q15 and _Q16 in your dsdt and found it did relate to lid method

Method (_Q15, 0, NotSerialized) // _Qxx: EC Query
{
Store (0x15, P80H)
^^^IGPU.GLID (LIDM)
Notify (LID0, 0x80)
}

Method (_Q16, 0, NotSerialized)  // _Qxx: EC Query
{
    Store (0x16, P80H)
    ^^^IGPU.GLID (LIDM)
    Notify (LID0, 0x80)
}
3.Try delete ^^^IGPU.GLID (LIDM) and reboot

4.Lid works!!!!

**Comment by syscl** [comment]
Add 10.15.x support. Feel free to try the latest update.
