### ISSUE TITLE
Problem with graphic hd4600, 10.14.2

### ISSUE THREAD

**Issue by trungtinitee** [syscl/M3800#118]
Why fix.?
Thanks you bro!
![IMG_20190416_151230](https://user-images.githubusercontent.com/49675459/56194711-bc5dce00-605d-11e9-8358-c4d109a275a5.jpg)

**Comment by trungtinitee** [comment]
My screen 3200x1800

**Comment by andreikr79** [comment]
This keys in clover config.plist helped for me
`<key>ScreenResolution</key>
<string>1024x768</string>`

**Comment by trungtinitee** [comment]
> This keys in clover config.plist helped for me
> `<key>ScreenResolution</key> <string>1024x768</string>`

**Comment by trungtinitee** [comment]
> This keys in clover config.plist helped for me
> `<key>ScreenResolution</key> <string>1024x768</string>`

Hi @andreikr79 , I

**Comment by trungtinitee** [comment]
> This keys in clover config.plist helped for me
> `<key>ScreenResolution</key> <string>1024x768</string>`

Hi @andreikr79 , do you have Facebook? I want make friend with you to ask you some question. I want install mac os version 14 on my laptop!

**Comment by syscl** [comment]
Update, could you please try the latest update?. Thanks!
