### ISSUE TITLE
Cannot unlock Dell D3800 Bios 

### ISSUE THREAD

**Issue by caltor726** [syscl/M3800#119]
my Current bios is A12.

I have tried to flash your unlocked bios, but got the error.

**Specs**
Dell M3800 mobile workstation
* 2.3GHz i7-4712HQ
* 3,840 x 2,160  (4K) touchscreen
* Intel HD 4600/Nvidia Quadro K1100M 2GB graphics
* 16GB RAM
* SAMSUNG SSD SM871 2.5 7mm 512GB
* Tenda W311+ USB wifi. ( RT2870 based)

**Comment by rod972** [comment]
Open a command prompt with administrative rights 
Go to the folder: **M3800-M3800/unlocked BIOS/**
and execute: 
_AFUWINx64/afuwinx64 M3800_QHD_A12_patched.bin /GAN_ 
Reboot, and enter the bios setup via F2 and verify you have the new unlocked menus.

**Comment by Samerbi** [comment]
Just do what this guy did
https://youtu.be/F-Kd3Enum0w
