### ISSUE TITLE
2 finger scroll

### ISSUE THREAD

**Issue by froggr** [syscl/M3800#12]
Not able to scroll with 2 fingers. Anyone else having this issue?

**Comment by syscl** [comment]
OK, this can be fixed by a very simple way: SysPref->Trackpad->Change the scrolling speed. And then enjoy your TouchPad:)

**Comment by froggr** [comment]
LOL! Haha I was reading commits and source!  Boy do I feel silly! Thanks a ton for your work putting this together dude! By far the easiest OSX setup I've ever done. Cheers

**Comment by syscl** [comment]
Congratulations! Not a problem, enjoy your OS X and M3800 :)
