### ISSUE TITLE
Redump ACPI

### ISSUE THREAD

**Issue by i3theans** [syscl/M3800#124]
hi, I am stuck here "Once you modify your settings in BIOS(especially Graphics Configuration in SA), you have to remove previous ACPI tables first, redump ACPI tables by press Fn+F4/F4 under Clover, and run deploy.sh again to patch your ACPI tables again."
Is there a guide on how to do this? press fn+f4 on the clover selection screen for usb install? run deploy.sh where to patch? Thanks

**Comment by syscl** [comment]
Feel free to test the latest version, which add supported 10.15.x.
