### ISSUE TITLE
Nvidia Graphic Cards K1100M

### ISSUE THREAD

**Issue by GuillaumeHullin** [syscl/M3800#125]
Hello there,
I know that during the Deploy.sh the graphic card is being disabled in order to get the show on the road but I stumbled upon this post yesterday https://www.reddit.com/r/hackintosh/comments/apivow/success_mojave_on_the_dell_precision_m4800_with/ and I thought to try out if I could manage to get the discrete GPU working...
Well I had no success... the only thing I managed to do was to get the GPU detected into the System Information... but only as generic Nvidia GPU with 0MB memory.
I did manage to install Web driver and Cuda using this article https://www.travelertechie.com/2018/09/nvidia-web-drivers-mojave-workaround.html but no success to get the GPU recognize...
I also found this post interesting https://osxlatitude.com/forums/topic/11182-final-dell-precision-m6800-m4800-fully-working-high-sierra-or-mojave/ but no success too.

I'm not a pro in the subject and I mostly just tried and restore my EFI or MacOS... maybe someone with more experience might have more success than me?

**Comment by GuillaumeHullin** [comment]
Here is a screenshot of what I "succeeded" to do 
![Screenshot 2020-05-24 at 15 48 47](https://user-images.githubusercontent.com/4108400/82755790-3c647480-9dd6-11ea-81a1-4f73a3ee1cb7.png)

**Comment by syscl** [comment]
This has been addressed.
