### ISSUE TITLE
Deploy.sh Run Errors

### ISSUE THREAD

**Issue by GuillaumeHullin** [syscl/M3800#126]
Hi,
I believe that in the new version of the repo, the folder "drivers64UEFI" was renamed "drivers".

When I ran the latest deploy.sh I got the following errors:

`[FAILED]  Update /Volumes/EFI/EFI/CLOVER/drivers64UEFI/FSInject-64.efi.
cp: /Users/guillaume/M3800/CLOVER/drivers64UEFI/FSInject-64.efi: No such file or directory
[FAILED]  Update /Volumes/EFI/EFI/CLOVER/drivers64UEFI/HFSPlus.efi.
cp: /Users/guillaume/M3800/CLOVER/drivers64UEFI/HFSPlus.efi: No such file or directory
[FAILED]  Update /Volumes/EFI/EFI/CLOVER/drivers64UEFI/DataHubDxe-64.efi.
cp: /Users/guillaume/M3800/CLOVER/drivers64UEFI/DataHubDxe-64.efi: No such file or directory
[FAILED]  Update /Volumes/EFI/EFI/CLOVER/tools/Shell.inf.
cp: /Users/guillaume/M3800/CLOVER/tools/Shell.inf: No such file or directory
`

I changed the path on line 63 and line 241 to get those errors out.

And there is one more error I got when I ran the script 
`[FAILED]  Update /Volumes/EFI/EFI/CLOVER/tools/Shell.inf.
cp: /Users/guillaume/M3800/CLOVER/tools/Shell.inf: No such file or directory
`

As the file Shell.inf is not in the new version I'm not sure what to do.

**Comment by syscl** [comment]
@GuillaumeHullin Thanks for pointing out, I think the issue is the structure of the Clover directory changed. Will fix it.

**Comment by GuillaumeHullin** [comment]
@syscl sure no problem. I actually ran into more troubles to get the repo working and right now I switched back to a backup of the EFI.
There are 2 things I'm not sure to understand, should I delete my Clover folder, copy the repo one, dump the table with F4 and then run deploy.sh? 

Seems that some drivers are missing cause I don't get any drive to boot on when Clover start on boot.

Or should I wipe out my EFI, reinstall Clover, "merge" your Clover folder, dump the table and then run deploy.sh?

Also, I couldn't find which version of clover you are using.

**Comment by syscl** [comment]
@GuillaumeHullin feel free to try the latest update which correct the drivers64UEFI to drivers/UEFI

**Comment by GuillaumeHullin** [comment]
@syscl thanks for the fix 

However I tried again but I run into the same problem below... (but no error when running Deploy.sh)

> @syscl sure no problem. I actually ran into more troubles to get the repo working and right now I switched back to a backup of the EFI.
> There are 2 things I'm not sure to understand, should I delete my Clover folder, copy the repo one, dump the table with F4 and then run deploy.sh?
> 
> Seems that some drivers are missing cause I don't get any drive to boot on when Clover start on boot.
> 
> Or should I wipe out my EFI, reinstall Clover, "merge" your Clover folder, dump the table and then run deploy.sh?
> 
> Also, I couldn't find which version of clover you are using.

**Comment by syscl** [comment]
What error you seen? 

Could you also paste the deploy.sh run log here?

**Comment by GuillaumeHullin** [comment]
[Terminal Saved Output.txt](https://github.com/syscl/M3800/files/4872862/Terminal.Saved.Output.txt)
![screenshot0](https://user-images.githubusercontent.com/4108400/86513164-59925700-be08-11ea-9fe8-1d300457a856.png)
[EFI.zip](https://github.com/syscl/M3800/files/4872866/EFI.zip)

Here is log of Deply.sh -d
You can see the Screenshot when I boot
I had the EFI for reference
