### ISSUE TITLE
El Capitan QE/CI

### ISSUE THREAD

**Issue by scopolamine1401** [syscl/M3800#13]
Hi you, can QE/CI be enable in El Capitan, I am at 10.10 now but when I upgrade it to a newer version, it is disabled.
By the way, if it is, what is the latest version can I upgrade without QE/CI be disbaled.
Thank you.

**Comment by syscl** [comment]
Oh, dear tranmlnhche, the latest version that this project support is El captain 10.11.4, and will support any future version as well:)

Well, the only procedure you have to do is running the deploy.sh again to finish all the patches on your latest version of OS X. :)

**Comment by scopolamine1401** [comment]
Thank you so much for your reply. Wish you all best!

**Comment by syscl** [comment]
If you have trouble booting into 10.11.4, just set Inject Intel=False under Clover, and then boot into OS X. Now you have a none QE/Cl mode, then run deploy.sh again to finish all the rest progress!

Wait for your feedback.

**Comment by scopolamine1401** [comment]
Hi you, do you know how to enable to screen?

**Comment by syscl** [comment]
What do you mean? 

Do you mean how to enable touch screen function?

**Comment by scopolamine1401** [comment]
Yes, sorry I mistyped it. How can I enable touch screen? Thank you.

**Comment by syscl** [comment]
You need to install updd for touchpad under 10.10.x.
