### ISSUE TITLE
Audio output from headphone only

### ISSUE THREAD

**Issue by froggr** [syscl/M3800#14]
Continued from #10 

Context: Audio only works via headphone jack. However, when awaking from sleep sound works for a brief moment (1 second or so). 
[systemlog.txt](https://github.com/syscl/M3800/files/224298/systemlog.txt)

When reviewing logs, on boot CodecCommander stops due to codec profile disable flag.
(Note: There are also a number of bluetooth related errors)

CodecCommander has also been tested from within /L/E and /S/L/E

**Comment by froggr** [comment]
@syscl just to clarify, was there anything else you wanted me to upload? 

This is an interesting issue as I have two M3800 units. On the first, I had some issues with bluetooth (I re-patched with Rehabman's BCM patch), the touchscreen doesn't work, and I installed Rehabman's nullethernet kext. Otherwise, it is stable as can be. 

The second machine - the one I'm am describing in this issue - has working touchscreen, seems to have bluetooth issues according to logs (untested) and has the sound issue. I have followed the exact same install procedure each time; Since my original install was at the end of March, I'm wondering if jumping back a few commits (say before 964491e) and see if I can recreate the install on my first M3800.

**Comment by syscl** [comment]
Sounds interesting. 

The screen touchpad of my 1st M3800 works like a charm, but with a new replaced one, I lose my touchpad function.(Or say more precisely, to power up the touchscreen, I have to install updd under 10.10)

But both M3800 have nice sound output. So can you upload your codec information from Ubuntu ( I will upload the terminate later)

Btw, which wifi model do you have?

**Comment by froggr** [comment]
Sorry - my brain is running slow today; It took me far too long to process what you were asking for. Here is the codec info:
[codec1.txt](https://github.com/syscl/M3800/files/224456/codec1.txt)

I have the DELL DW1560 (broadcom) wifi

**Comment by syscl** [comment]
@froggr 
You are in the right way :)

I've just seen codec#1.txt but that's about HDMI audio, we need the realtek one. In this case, type

``` sh
cat /proc/asound/card0/codec#0 > ~/Desktop/codec_dump.txt
```

If you can provide both M3800's codec for futher diff, I will be much appreciated.

BT issue:
Try replace BrcmFirmwareRepo.kext with BrcmFirmwareData.kext[location: ./M3800/Kexts/].

P.S. about your BT[0a5c:216f], I've just found bug reports even though in Ubuntu/Arch Linux, hence I guess the BrcmPatchRAM2.kext just upload the wrong hex for you, we need to correct it later since I am still very busy with my – non hack related – work/startup, but I will try to push things forward.

**Comment by froggr** [comment]
Apologies! I uploaded the wrong file.
[codec0.txt](https://github.com/syscl/M3800/files/227091/codec0.txt)

I'm wondering if I'm experiencing this bug:
https://bugs.launchpad.net/ubuntu/+source/alsa-driver/+bug/1320020

I just rebooted into a live ubuntu usb and although sound is detected, I'm only able to get sound via headphones. I will reinstall windows to see if speakers begin to work which will confirm this is indeed the issue. If so, I'm wondering if this was caused by windows shutting down with fastboot enabled?

I agree regarding being busy as I'm in the same boat! However I was very disappointed with the M3800 until finding your repo so thanks again! I owe you a beer!

**Comment by froggr** [comment]
Regarding bluetooth, yes that is exactly what I did to resolve bluetooth issues on my first M3800. I will do the same on the second machine once I get this sound working.

**Comment by froggr** [comment]
This is quite interesting. I'm now experiencing the issue in Windows as well so I'm thinking I have a hardware issue. Its just surprising that this occurred as soon as I installed OSX.

**Comment by syscl** [comment]
This is very possible hardware issue. Try full sleep(light indicator disappear, about 1 min) under Windows and then see if this can fix the audio issue.

I have the "fastboot enabled" in BIOS.

If your laptop is still in warranty, try to replace/fix it a.s.a.p!

**Comment by syscl** [comment]
Hello @froggr , could you please provide your  ioreg for me. I mean the one which touchscreen can work normally, I wanna solve this issue. 

Thanks, 
syscl

**Comment by froggr** [comment]
Im not using the machine right now; I've given it to one of the devs on my team. I'll send her a PM to post it up on here, otherwise I'll grab that for you when I'm back to the office on Tuesday.
