### ISSUE TITLE
A few questions!

### ISSUE THREAD

**Issue by Byron657** [syscl/M3800#16]
Hello, I have a few questions:

1)I'm about to install OS X on my M3800, I see the folder is updated to clover 3438, but I see tehre is clover 3469 ready to download, I'm downloading the 3438, but can I just change the folder when the repo will be updated?
2)My M3800 is a little bit custom, new RAMs and Mini SSD, can this be a problem?
3)What happen if I run the script when it's not needed? When a update is out can I just re-run the script?

Sorry for the noobie questions but I'm totally a stranger to OS X :)

**Comment by syscl** [comment]
1. The version of clover has nothing to do with the OS X on M3800/XPS9530. I just sync/update clover to latest one as a reminder that this repo has not been forgotten. So, you can use whatever version of Clover you like. However, to be honest, I strongly suggest you to update clover of M3800/XPS9530 from my git because I have various tests on both models and improvements(optimised the source code of Clover).
2. The result is positive, memory and storage have nothing to do with OS X on M3800.
3. When a update is release, you can re-run the deploy.sh to apply the patch for IOKit which is used to limit the maximum resolution for a real Mac at 2880x1440. We cannot power up the QE/CI without that patch. That's the reason why we have to re-run the deploy.sh again.

P.S. It's extensive effort I've made that makes OS X on M3800/XPS9530 is as easy as we can imagine, almost all operations have been done once you get executed deploy.sh!

**Comment by Byron657** [comment]
Hello, I noticed that after a sleep the screen won't wake in any ways, is this a know issue?

EDIT: I actually mean stop, like stand-by for windows, not screen sleep, that one works. The only problem I found is that after keyboard light goes sleep, it can't be woken up by the usb wireless mouse, but only by the trackpad or the keyboard itself.

**Comment by syscl** [comment]
Sorry I still get confused about what you mean.

Sleep issue has long been solved, more details can be found [here](https://github.com/syscl/M3800/commit/dc450dbe616a0d7635532710028f1ee3148e542a).

The only way to wake from sleep is press/touch the power button on the left side of the M3800/XPS9530, it seems you get messed with the config.plist and new deploy.sh. Please use the latest config.plist and deploy.sh. 

syscl

**Comment by Byron657** [comment]
Well I don't use the english language on the mac so I don't know what sleep means, if it means that after x time the screen goes black, so the sleep works! I mean what in Windows is called stand-by, SOMETIMES, the screen will stay black after powering on again. Also I was trying to say that when the keyboard light goes off, I'm able to light it up again only by keyboard or touchpad, not by the external mouse. Also I wanted to ask you if using CloverConfigurator I can mess your config and if running deploy.sh just to fix the config file can be a problem.

Oh, and last feedback, when OS X starts and the loading bar goes from small to big cause of the resolution changing, the screen will vibrate and go crazy for 1 second.

Thanks for this awesome script btw, this is by far the best around.

**Comment by syscl** [comment]
Which language do you use? I mean maybe we can use the same language(maybe chinese ;))

Why use Clover Configurator? I never use that buggy tool.

Well, about the screen vibration during booting progress within 1s, it's normal. Till now there's no better solution than emulating verbose mode(as we use in the patch to fix boot glitches). So don't worry about that 'issue'(Not an issue for me).

syscl

**Comment by Byron657** [comment]
I use it in Italian, way far from chinese ahah
By the way I need Clover Configurator to put the Custom Entries in the Clover GUI, since I'm not good to do it manually, doing this only can cause problems?

By the way the thing I refer to in italian it's called Stop, when I put it by myself (apple logo->stop), sometimes when powering on the screen will stay black and I'm not able to wake it up.

The other problem is not a problem caused by the sleep/stop, just the keyboard's light not able to be woken up by usb mouse after it goes off when not typing.

**Comment by syscl** [comment]
Oops, don't worry about Clover configurator at all ;) 

Try my latest config.plist and then rebuild kernel cache by typing in terminal

``` sh
sudo touch /System/Library/Extensions && sudo touch /Library/Extensions && sudo kextcache -u /
```

Then reboot.

If that still cannot solve your lid wake issue, it's very likely that your sleep function is broken as well. Because my first M3800 has that issue as well! It's a hardware issue, not OS X. To verify whether sleep/stop is performing normally, you can stop/sleep M3800 under Windows then wake it again.
If your laptop is still in warranty, try to fix/replace a new one as soon as possible!

Sorry, about the keyboard's light, how to use mouse to light it up? I just use 'F10' to light it up, and the light will disappear after several minutes(don't know if this is the issue). Maybe that's dell's design?

best wishes!
syscl

**Comment by Byron657** [comment]
On windows works perfectly, but as I said, this happens rarely, I would say once every 20 times, totally random.

Also I have one question, do the script copy all the CLOVER files to the destination? Since I tried deleting the old config file, but it created a config containing only 2 patches. The first time I ran the script even if I selected the hdd EFI partition the whole thing was made on the USB stick, I moved everything manually.

**Comment by syscl** [comment]
Do you use external wireless devices(e.g. USB Wi-Fi)? 

Nope, the script just update kexts, add necessary kexts patches. Umm, try to remove USB stick then execute the deploy.sh.

More details is welcome to do a further analysis, such as IOReg(how to make an IOReg, please see [here](http://www.tonymacx86.com/threads/guide-how-to-make-a-copy-of-ioreg.58368/), and also please provide the following by typing

``` sh
kextstat >~/byron657.txt
diskutil list >>~/byron657.txt
```

Best,
syscl

**Comment by Byron657** [comment]
Unbelievably I'm not able to replicate the bug, it seems to be fixed now. The only problem is the keyboard light that doesn't wake using bluetooth mouse (connected to USB), atm I'm not at home, I'm replying from my tablet, I'll send you the IOReg and the txt when I come back. Beside the keyboard light everything seems to work perfectly, no problems at all. I've got a question, if for example I delete the entire CLOVER folder on the EFI partion, I have just to reinstall CLOVER, dump tables, copy your CLOVER folder and re-run deploy.sh or I have to reinstall the OS? Because I'm really new to this and I used (in Yosemite) to reinstall everytime there was a problem.

**Comment by syscl** [comment]
The answer is positive, no reinstallation is required. All you just to do is as you said:" reinstall Clover then replace it with my clover...".

**Comment by Byron657** [comment]
Well, I guess FileVault is not supported. I tried to enable it and when rebooted the screen was grey+prohibitory sign.

**Comment by syscl** [comment]
I'm sorry to hear that, but FileVault may not be supported on hackintosh from my experience. 

Note: Do not lock or try to lock your hackbook(M3800) by iCloud and etc, it will make your OS X totally be locked unless clean NVRAM and ...

syscl

**Comment by Byron657** [comment]
No problem, I will reinstall it. What do you mean with "lock by iCloud"? I can't sign in iCloud for syncing things with iPhone?

**Comment by syscl** [comment]
There's no problem in sync with iCloud. I mean the find my mac function, once you lock your laptop by "find my Mac", it will be a disaster: you can't easily unlock the locked system by only reinstalling it, u have to remove/clean the whole NVRAM.

syscl

**Comment by Byron657** [comment]
Oh well, it could be possible that I activated it before activating the FileVault ahah
But I deleted all the partitions and formatted the volume, I'll start from a vanilla usb installation, isn't that enough? You should write this things to avoid noobs like me doing shit stuffs :'(
Is there any other disaster I can do?

**Comment by syscl** [comment]
Um, if you've locked OS X you cannot enable FileVault. Just reinitiate the hard disk is enough.

**Comment by Byron657** [comment]
Well but I'm sure that I activated, I mean, I was sarcastic with that "it could be possible", I did it. So there is like a chance to lock it or what? Anyway I don't understand what do you mean with locked, like crashing upon activating, not rebooting or what? If I deleted everything on the SSD there is chance to get problems?

**Comment by syscl** [comment]
Um, you have to try since I'm outside far from my laptop :(

I will be back tonight in to give u a screenshot about the 'lock my Mac' function.

syscl

**Comment by Byron657** [comment]
So it's something not related to "Find my Mac"? Because I just enabled that, I logged in with my account and nothing else, just find my mac under iCloud prefs menu. If i go to find my phone i can see my "macbook", offline obviously.

**Comment by syscl** [comment]
I mean lock that laptop just like if u lost your iPhone and then use iCloud to lock it. Maybe u just turn on find my Mac instead of locking it.

**Comment by Byron657** [comment]
Oh no, I didn't lock it, the "lock" option is still available. So If I never lock it I can use Find my mac safely?

**Comment by syscl** [comment]
yes, till now do not press the 'lock' button.

**Comment by Byron657** [comment]
Well for the keyboard not lighting when moving the external mouse is a dell problem I think, on Windows I see I got the same issue unfortunately. I have a question, can I leave Vt-d on in BIOS? Cause I need it on Windows, but I see every guide says to disable it except yours.

**Comment by syscl** [comment]
No need to disable VT-d option in bios, and you can enjoy your VT-d on Windows and also use OS X flawslessly! Don't worry about that :)

**Comment by Byron657** [comment]
Wow, impressive! You did a really nice job, I wish I was good half as you are :) I saw you added BIOS for UHD models, I have the 3200x1800 model and I patched the BIOS myself (I didn't use your file because I patched it before you made this repo, while I was following the Austinn's Yosemite one), do I have to change something in BIOS? And sorry for the question, but are you planning to support macOS Sierra? Thanks! :)

**Comment by syscl** [comment]
About bios setting: it's better to remove all acpi tables(dsdt and ssdt) then set bios to default.
Then re-dump acpi tables, re-run deploy.sh to finish all patches.

Yes, the answer is positive. I will later add support for macOS till the fall when the macOS is released(sorry I do not use any beta versions since I think those OS as unreliable half finished products, and always recommend users prevent to use it!).

**Comment by Byron657** [comment]
So I have to reset BIOS to default and nothing else? Don't I have to re-change the settings as the readme says?

**Comment by syscl** [comment]
Yes, you have to change the bios setting as readme as well.
