### ISSUE TITLE
OsxAptionFix2Drv: Starting overrides for .IABootFiles\boot.efi

### ISSUE THREAD

**Issue by vivodlink** [syscl/M3800#18]
syscl:
你好请问安装10.11.4一直卡在
 《OsxAptionFix2Drv: Starting overrides for .IABootFiles\boot.efi
            Using reloc block:no, hibernate wake:no
                 ++++++++++++++++++++++》
 已经换了好几个版本的clover和config.plist都不行，
 按照你这边提供的按装方法都尝试过了都不行。甚至连内存条的卡槽都换过了，请问还有什么方法解决吗？
这是笔记本的配置
电脑型号            戴尔 Precision M3800 笔记本电脑
  操作系统            Windows 10 专业版 64位 ( DirectX 12 )

  处理器              英特尔 第四代酷睿 i7-4712HQ @ 2.30GHz 四核
  主板                戴尔 Precision M3800 ( 英特尔 Haswell )
  显卡                英特尔 HD Graphics 4600 ( 112 MB / 戴尔 )
  内存                8 GB ( DDR3 1600MHz )
  主硬盘              西数 WDC WD10SPCX-00HWST0 ( 1 TB / 5400 转/分 )
  显示器              夏普 SHP13F8 ( 15.7 英寸  )
  声卡                瑞昱  @ 英特尔 Lynx Point  高保真音频
  网卡                英特尔 Dual Band Wireless-AC 7260

--------[ 主板 ]----------------------------------------------------------------------------------

  主板型号            戴尔 Precision M3800
  芯片组              英特尔 Haswell
  主板版本            A10
  BIOS                戴尔 Inc. A10  /  制造日期: 2015年08月17日
  BIOS的大小          2048 KB

  板载设备            NVIDIA Graphic Device / 视频设备 (启用)

--------[ 处理器 ]--------------------------------------------------------------------------------

  处理器              英特尔 第四代酷睿 i7-4712HQ @ 2.30GHz 四核
  步进                C0
  速度                2.30 GHz (100 MHz x 23.0)
  处理器数量          核心数: 4 / 线程数: 8
  核心代号            Haswell
  生产工艺            22 纳米
  插槽/插座           Socket H3 (LGA 1150)
  一级数据缓存        4 x 32 KB, 8-Way, 64 byte lines
  一级代码缓存        4 x 32 KB, 8-Way, 64 byte lines
  二级缓存            4 x 256 KB, 8-Way, 64 byte lines
  三级缓存            6 MB, 12-Way, 64 byte lines
  特征                MMX, SSE, SSE2, SSE3, SSSE3, SSE4.1, SSE4.2, HTT, EM64T, EIST, Turbo Boost

**Comment by syscl** [comment]
你的BIOS解锁了吗?
用了什么版本/谁的系统？ 什么引导配置？

**Comment by vivodlink** [comment]
BIOS按照你的方法解锁并按你远景论坛的教程设置的。系统是下载远景《winxpzzg 》提供的自带Clover 3355引导的OS X El10.11.4(15E65).dmg原版[http://bbs.pcbeta.com/viewthread-1681547-1-5.html](url)

**Comment by vivodlink** [comment]
引导配置就是下载你这里提供的M3800的Clover

**Comment by syscl** [comment]
果然是这样, 你用的镜像有问题. 这个镜像不建议使用, 因为加入了大量第三方非必要的内核扩展, 甚至很多乱七八糟的改动, 在我的例子中使用的是原版的镜像来安装的!
