### ISSUE TITLE
蓝牙激活成功，但不能搜到设备

### ISSUE THREAD

**Issue by shiweifu** [syscl/M3800#2]
![](http://i12.tietuku.com/6181bf8c947ab24b.png)

显示是激活成功了，但不能搜到设备。键盘、鼠标、手机都不行。
airdrop是正常的。
想不通这是咋回事……

10.10.5。

**Comment by syscl** [comment]
你的可被发现关闭了（设置—>蓝牙）。建议使用EI Captain，修复了很多问题。

**Comment by syscl** [comment]
我也遇到这样的问题了，在更换了蓝牙驱动之后这个问题修复了，不知道是怎么引起的。你试一下新的驱动吧。

**Comment by shiweifu** [comment]
替换了新的驱动，重新执行了脚本，目前一切完美。
记得deploy执行两遍哦
