### ISSUE TITLE
Bluetooth not working

### ISSUE THREAD

**Issue by bochamsua** [syscl/M3800#20]
Hello,

Firstly I have to say thank you so much for this great automate tool.
I have M3800 late 2013 running Yosemite 10.10.5

I get everything working perfectly except Bluetooth: No Bluetooth icon show, No information found about Bluetooth in System Information.

I use Broadcom 94352z card and wifi is still working well.
Card Type:  AirPort Extreme  (0x14E4, 0x2162)
  Firmware Version: Broadcom BCM43xx 1.0 (7.15.166.24.3)

Could you please help me to resolve this since I want to use my Magic mouse.

Thank you very much

**Comment by syscl** [comment]
Hi, 

I'm glad to hear that deploy.sh help you:)

About the BT issue:
The issue is due to the BrcmFirmwareRepo.kext, try to replace BrcmFirmwareRepo.kext with BrcmFirmwareData.kext [location: ./M3800/Kexts/ ]

Wait for ur reply.

Best wishes!
syscl

**Comment by bochamsua** [comment]
Hello, 

Thank you for your prompt response.

I just tried your suggestion, but it still didn't work: no bluetooth.
Please see the attachments of what I have in Clover kexts and boot log.

Could you please check and see what I am missing?

Thank you!
[bootlog.log.txt](https://github.com/syscl/M3800/files/262441/bootlog.log.txt)
![screen shot 2016-05-13 at 08 16 12](https://cloud.githubusercontent.com/assets/13343665/15235170/26fd5e8a-18e3-11e6-92e0-aa023307d679.png)

**Comment by syscl** [comment]
OK, let's try to figure out the issue.

Boot.log is not enough, we will need ioreg(refer: http://www.tonymacx86.com/threads/guide-how-to-make-a-copy-of-ioreg.58368/), kernel.log, and kext state by typing 

``` sh
kextstat >~/kextstat.rtf 
```

Then kextstat.rtf is now saved as rtf in ~/.

Upload such files and together we will solve the BT issue!

Best wishes!
syscl

**Comment by bochamsua** [comment]
Hi,

I dont see kernel.log in /var/log
Please check the attached file (zip file) for others.
[Archive.zip](https://github.com/syscl/M3800/files/264252/Archive.zip)

Thank you!

**Comment by syscl** [comment]
@bochamsua 

I've just seen the files you attached, it seems OS X has identified the address of your BT, but two bluetooth drivers(kexts) have not been uploaded. That maybe the reason why BT is not working (hex files have not been uploaded correctly).

BTW, your config.plist is different from the one in Git/M3800/Clover, try to replace the whole Clover folder with the one under my git, re-dump ACPI tables by pressing (Fn+)F4 under Clover GUI, then re-execute deploy.sh to finish the whole progress.

Best wishes!
syscl

**Comment by bochamsua** [comment]
Hi Syscl,

I have just done the whole progress as your suggested but Bluetooth still didn't work either.

The reason my config.plist is different is that I went to Rt Variables tab of Clover Configurator and click on Calculate button, after that I copy the generated MLB value into MLB field on top ( I did this method long time ago to fix iMessage). It randomly worked for me but after restart, it stopped working and I couldn't to make it work again.

Could you please investigate this issue?

Thank you very much!

**Comment by syscl** [comment]
About iMessage/FaceTime:

Go to take a shot in About This Mac-->System Report-->Hardware(Model Name, Serial Number (system), UUID) from a real MacBook(better 11,4 or say MacBook Pro (Retina, 15-inch, Mid 2015)) in AppleStore. Then inject such information by Clover!(This method is the one I use to fix my FaceTime, iMessage, etc...)

Back to BT:
Install BrcmPatchRAM+BrcmFirmwareRepo in L/E or /S/L/E and then rebuild caches by typing

``` sh
sudo touch /System/Library/Extensions && sudo touch /Library/Extensions && sudo kextcache -u /
```

Note: Remove previous BT related kexts in /EFI/Clover/kexts/10.10.

Reboot to see if this method works.

syscl

**Comment by bochamsua** [comment]
Hi Syscl,
I just followed your guidance and now I can see Bluetooth icon but it still doesn't work.
I saw this message when running the given command: 

kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext BrcmPatchRAM.kext
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext BrcmFirmwareRepo.kext

BTW, my card is: [0a5c:21fd] Broadcom 4352Z
It's not [0a5c:216f] Dell DW1560 (4352/20702)

What would cause this issue?

Please help me out.

Thank you

**Comment by syscl** [comment]
Yes, 94352 has various IDs...

OK, 

Try to replace BrcmFirmwareRepo.kext with BrcmFirmwareData.kext in /L/E or /S/L/E and then rebuild cache by typing 

``` sh
sudo touch /System/Library/Extensions && sudo touch /Library/Extensions && sudo kextcache -u /
```

syscl

**Comment by bochamsua** [comment]
Hi Syscl,
I actually have already tried that but it was the same.
Bluetooth icon was shown up in System Preferences and System Bar but it just didn't work (couldn't turn On or Off or Connect).

I didn't have real Mac to prepare USB installation, I used VMWare OSX, do you think that could lead to issue with the installation?

Thank you

**Comment by syscl** [comment]
What do you mean by VMWare OS X? The OS X on your laptop is on VMWare instead of M3800??

**Comment by bochamsua** [comment]
I mean when preparing the USB OSX installation I didn't have the real Mac so I have to use OSX on the VMWare on windows 10 to prepare the USB OSX Installation.

**Comment by syscl** [comment]
Manually Create An Installation Media

Clone the base binaries to the the hfs+ partition:

mkdir /tmp/install_esd
hdiutil attach "/Applications/Install OS X Yosemite.app/Contents/SharedSupport/InstallESD.dmg" -readonly -mountpoint /tmp/install_esd -nobrowse
sudo asr restore -source /tmp/install_esd/BaseSystem.dmg -target /Volumes/install_osx -erase -format HFS+ -noprompt
diskutil rename "OS X Base System" install_osx
rm /Volumes/install_osx/System/Installation/Packages
cp -a /tmp/install_esd/Packages /Volumes/install_osx/System/Installation
cp -a /tmp/install_esd/BaseSystem.dmg /tmp/install_esd/BaseSystem.chunklist /Volumes/install_osx
hdiutil detach /tmp/install_esd
rmdir /tmp/install_esd
Replace the config.plist in the USB's CLOVER directory with the one located in the repository's INSTALLATION directory.

**Comment by bochamsua** [comment]
Hi,
Yeh, I used this method.

BTW I managed to get bluetooth working by installing all kexts in /S/L/E and remove all from Clover kexts folder. 

Dont know why it works.

**Comment by syscl** [comment]
I'm glad it did work!

Actually, you just need to install BT related kext to /S/L/E will solve your BT issue. The reason is due to the BrcmPatchRepo/BrcmPatchData & BrcmPatchRAM have not been fast enough to be injected during the booting progress(Rehabman's problem). Once you install the kexts to SLE where the place is more memory efficient, it will work as expect. 

BTW, Which BT kexts do you use? And why don't you try El Capitan 10.11.4(which is supported by this project :))

**Comment by bochamsua** [comment]
Hi Syscl,

Will the iMessage, Facetime, Handoff work on EI Capitan 10.11.4? 
I tried with 10.11.4 at the first time I see your project indeed but none of iMessage, Facetime worked so I went back to Yosemite.

Just install BT related kexts to /S/L/E didn't work as I have already tried above.
FYI, here what I have in /S/L/E
![screen shot 2016-05-15 at 6 47 07 pm](https://cloud.githubusercontent.com/assets/13343665/15273792/85b03a56-1acd-11e6-979b-802fcffb3efa.png)

BTW, do you know how to make this option work? (Ignore built-in Trackpad...) Even it is selected I am still able to use Trackpad
![screen shot 2016-05-15 at 6 56 52 pm](https://cloud.githubusercontent.com/assets/13343665/15273853/1bb3aa14-1acf-11e6-9c8c-6eb38bfb9ec5.png)

Thank you

**Comment by syscl** [comment]
The result of using FaceTime, iMessage on 10.11.4 is positive. The procedure is as following:
1. config.plist/SMBIOS/Serial Number.
2. config.plist/SMBIOS/SmUUID: Note the last 12 values which have to match the MAC address as your wireless card, the final injected SmUUID will look like: 1E58914B-6EEA-50E8-9392-A1B2C3D4E5F6(MAC: A1-B2-C3-D4-E5-F6).

---

BT related kexts: Brcm*, USB_injector, FakePCIID_Broadcom*.

---

I just find a mouse to test this for you, yes, the option "Ignore built-in..." works as expect. 
Post your Trackpad setting for further analysis.

syscl

**Comment by bochamsua** [comment]
Thank you, I just installed EI Capitan as your suggestion and notice 2 issues:
1. The mouse is very lag (magic mouse) compares with Yosemite
2. The option Ignore built-in trackpad still doesnt work for me

**Comment by syscl** [comment]
Ummm, sorry I do not have magic mouse or BT mouse, I just have USB mouse.

About lag, do you try to change the *speed in Pref/Mouse?
Or I just saw a software smoothmouse for better MOUSE experience. Open source software: http://smoothmouse.com, wish that could help you.

syscl

**Comment by bochamsua** [comment]
Yeh, USB mouse is working just fine.

I think that might be the issue with Bluetooth/Wifi kext

**Comment by syscl** [comment]
How about the http://smoothmouse.com? Does it work?

**Comment by bochamsua** [comment]
No, unfortunately it doesn't help.

I am thinking going back to Yosemite.

**Comment by syscl** [comment]
Umm, how about replacing BrcmFirmwareRepo with BrcmFirmwareData? Or replace BrcmFirmwareData with BrcmFirmwareRepo? 

We need to figure out what's going on.

**Comment by bochamsua** [comment]
I actually tried this already because I had the same experience on Yosemite as above.
We need to install BrcmFirmwareData instead of BrcmFirmwareRepo to /S/L/E.
BrcmFirmwareRepo didn't work as expected.

BTW, do you know how to make iMessage work without adding country code to contact phone numbers.
For now I have to add country code to contact phone numbers otherwise it will not be recognized as registered with iMessage.

Thank you

**Comment by syscl** [comment]
Ummm, my iMessage work without adding country code, not sure what cause that issue.

Maybe set the right location fix that issue? 

BTW: I just forgot one SMBIOS setting(sorry for my ignorance since I was busy these days):
About SMBIOS/Board Serial Number=Serial Number + 5 random digits(for example: C02K7SNAFD56A0CF3 = C02K7SNAFD56 + A0CF3).

syscl

**Comment by bochamsua** [comment]
Hi Syscl,

Above information was already correct.

EI Capitan 10.11.5 is just released and I upgraded it.

Everything still works well but magic mouse issue is not resolved.

**Comment by syscl** [comment]
I'm curious about what cause that issue?

Ummm, you can try to backup old USB/BT Mouse related kexts(in /S*/L*/E*) and then revert back to 10.10 kexts(if this can solve your issue, we can find a way to patch the binary kexts to solve that issue).

That's why a backup is required.

syscl

**Comment by bochamsua** [comment]
Yeh I tried this and the issue still there. Dont know what happens.
I think I should go back to Yosemite because I need a stable system for work :(
