### ISSUE TITLE
引导界面撕裂.左右各四个虚苹果......

### ISSUE THREAD

**Issue by AKA-KC** [syscl/M3800#21]
以上问题......

**Comment by AKA-KC** [comment]
还有就是我用了ramdisk.sh脚本....现在不想用的...有什么办法能去掉它？

**Comment by syscl** [comment]
引导四苹果问题修复一下缓存

``` sh
sudo touch /System/Library/Extensions && sudo touch /Library/Extensions && sudo kextcache -u /
```

然后重启.

关于ramdisk的问题你应该到https://github.com/syscl/Fix-usb-sleep 下面反馈, 不过在这里一并解答了吧

``` sh
cd ./Fix-usb-sleep
./ramdisk -u
```

---

About boot glitches, you should rebuild kernel caches by 

``` sh
sudo touch /System/Library/Extensions && sudo touch /Library/Extensions && sudo kextcache -u /
```

Then reboot.

About ramdisk question, you should post question in https://github.com/syscl/Fix-usb-sleep, but I allow it once here: how to remove ramdisk

``` sh
cd ./Fix-usb-sleep
./ramdisk -u
```

////

**Comment by AKA-KC** [comment]
`MacBook-Pro:~ kcwong$ sudo touch /System/Library/Extensions && sudo touch /Library/Extensions && sudo kextcache -u /
kext-dev-mode allowing invalid signature -67030 0xFFFFFFFFFFFEFA2A for kext msdosfs.kext`

还使存在这个问题～。。。。修复不了。。。。你看执行出来的代码正确么

**Comment by syscl** [comment]
这个显然你用过kext utility修复权限导致msdosfs.kext签名失效, 你是不是用过其它人的方法破解系统? 

关于四个苹果, 在打入了kext补丁之后, 只会在引导中途瞬间出现, 不知道你指的是不是这种情况. 如果不是, 很有可能你的安装过程/配置文件没有使用我目录中的. 我记得AustinSMU有过类似破解IOGraphics的, 那种破解方法会引发一系列的问题的(不够优雅), 我没有用那种给系统带来很多改动的破解方法(可以说几乎没有).

建议你按照我的教程完整的安装一次(用原版的安装盘).

祝好!
syscl

**Comment by AKA-KC** [comment]
谢谢回复：
就试用kext utility修复过....其他都是按照你的来的
哪我重装系统吧

**Comment by syscl** [comment]
重装系统吧
如何创建原版镜像

mkdir /tmp/install_esd
hdiutil attach "/Applications/Install OS X Yosemite.app/Contents/SharedSupport/InstallESD.dmg" -readonly -mountpoint /tmp/install_esd -nobrowse
sudo asr restore -source /tmp/install_esd/BaseSystem.dmg -target /Volumes/install_osx -erase -format HFS+ -noprompt
diskutil rename "OS X Base System" install_osx
rm /Volumes/install_osx/System/Installation/Packages
cp -a /tmp/install_esd/Packages /Volumes/install_osx/System/Installation
cp -a /tmp/install_esd/BaseSystem.dmg /tmp/install_esd/BaseSystem.chunklist /Volumes/install_osx
hdiutil detach /tmp/install_esd
rmdir /tmp/install_esd

Replace the config.plist in the USB's CLOVER directory with the one located in the repository's INSTALLATION directory.

**Comment by AKA-KC** [comment]
说没权限失败。。。。可是我已经给了权限了啊。。。。

KCdeMacBook-Pro:m3800 KCWONG$ ./deploy.sh
[ ---> ]  Updating files from https://github.com/syscl/M3800...
Already up-to-date.
[  OK  ]  Create ./DSDT.
[  OK  ]  Create ./DSDT/prepare.
[  OK  ]  Create ./DSDT/precompile.
[  OK  ]  Create ./DSDT/compile.
/dev/disk0 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *240.1 GB   disk0
   1:                        EFI EFI                     209.7 MB   disk0s1
   2:                  Apple_HFS Mac OS X (HFS+) part... 51.6 GB    disk0s2
   3:                 Apple_Boot Recovery HD             650.0 MB   disk0s3
   4:       Microsoft Basic Data Scratch Live  Disk      187.6 GB   disk0s4
/dev/disk1 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *256.1 GB   disk1
   1: 142F5F5D-B9E5-4433-87C0-68B6B72699C7               593.5 MB   disk1s1
   2:       Microsoft Basic Data windows System          119.9 GB   disk1s2
   3:                  Apple_HFS                         135.6 GB   disk1s3
Enter EFI's IDENTIFIER, e.g. disk0s1: disk0s1
[  OK  ]  Mount disk0s1.
[  OK  ]  Copy untouch ACPI tables.
[ ---> ]  Disassembling tables...
[  OK  ]  Disassemble tables.
[  OK  ]  Search specification tables by syscl/Yating Zhou.
[ ---> ]  Patching DSDT.dsl
[  OK  ]  Fix PARSEOP_ZERO.
[  OK  ]  Fix ADBG Error.
[  OK  ]  Rename GFX0 to IGPU.
[  OK  ]  7-series/8-series USB.
[  OK  ]  Fix USB _PRW.
[  OK  ]  Acer Aspire E1-571.
[  OK  ]  IRQ Fix.
[  OK  ]  SMBus Fix.
[  OK  ]  AC Adapter Fix.
[  OK  ]  Add MCHC.
[  OK  ]  Fix _WAK Arg0 v2.
[  OK  ]  Add IMEI.
[  OK  ]  Fix Non-zero Mutex.
[  OK  ]  OS Check Fix.
[  OK  ]  Add audio Layout 1.
[  OK  ]  Rename B0D3 to HDAU.
[  OK  ]  Remove GLAN device.
[ ---> ]  Patching SSDT-10.dsl
[  OK  ]  _BST package size.
[  OK  ]  Rename GFX0 to IGPU.
[ ---> ]  Patching SSDT-12.dsl
[  OK  ]  Rename GFX0 to IGPU.
[  OK  ]  Rename HD4600 to Iris Pro.
[  OK  ]  Brightness fix (Haswell).
[  OK  ]  Rename B0D3 to HDAU.
[  OK  ]  Insert HDAU device.
[ ---> ]  Patching SSDT-13.dsl
[  OK  ]  Rename GFX0 to IGPU.
[ ---> ]  Patching SSDT-14.dsl
[  OK  ]  Remove invalid operands.
[  OK  ]  Rename GFX0 to IGPU.
[  OK  ]  Disable Nvidia card (Non-operational in OS X).
[ ---> ]  Copying tables to precompile...
[  OK  ]  Copy tables to precompile.
[ ---> ]  Copying untouched tables to ./DSDT/compile...
[  OK  ]  Copy untouched tables to ./DSDT/compile.
[ ---> ]  Compiling tables...
[  OK  ]  Compiling DSDT.
[  OK  ]  Compile DptfTa.
[  OK  ]  Compile SaSsdt.
[  OK  ]  Compile SgRef.
[  OK  ]  Compile OptRef.
[ ---> ]  Copying SSDT-rmne.aml to ./DSDT/compile...
[  OK  ]  Copy SSDT-rmne.aml to ./DSDT/compile.
[  OK  ]  Generate C-States and P-State for Intel i7-4712HQ.
[  OK  ]  Clean dynamic SSDTs.
[  OK  ]  Create /Volumes/EFI/EFI/CLOVER/ACPI/patched.
[  OK  ]  Copy tables to /Volumes/EFI/EFI/CLOVER/ACPI/patched.
[ ---> ]  Updating kexts...
[  OK  ]  Remove pervious kexts in /Volumes/EFI/EFI/CLOVER/kexts/10.11.
[  OK  ]  Update kexts from ./CLOVER/kexts/10.11.
[  OK  ]  Update kexts from ./Kexts.
[  OK  ]  BCM2045A0 found.
[  OK  ]  Remove redundant BT driver: BrcmPatchRAM.kext.
[ ---> ]  Installing audio...
[  OK  ]  Install audio.
[ Note ]  Set System Agent (SA) Configuration—>Graphics Configuration->DVMT Pre-Allocated->『160MB』.
[ ---> ]  Unlocking maximum pixel clock...
[  OK  ]  Sign IOKit.
[ ---> ]  Leading to lid wake on 0x0a2e0008 (c) syscl/lighting/Yating Zhou...
[  OK  ]  Lead to lid wake on 0x0a2e0008.
[  OK  ]  Generate configuration file of sleepwatcher launch daemon.
[  OK  ]  Generating script to unmount external devices before sleep (c) syscl/lighting/Yating Zhou.
[  OK  ]  Generate script to load RTWlanUSB upon sleep.
[ ---> ]  Installing external devices sleep patch...
[FAILED]  Create /usr/local/sbin/.
mkdir: /usr/local/sbin/: Permission denied
[FAILED]  Install sleepwatcher daemon.
cp: directory /usr/local/sbin does not exist
[  OK  ]  Install configuration of sleepwatcher daemon.
[  OK  ]  Install sleep script.
[  OK  ]  Install wake script.
[  OK  ]  Fix the permissions of /etc/sysclusbfix.sleep.
[  OK  ]  Fix the permissions of /etc/sysclusbfix.wake.
[  OK  ]  Trigger startup service of syscl.usb.fix.
[  OK  ]  Clean up.
[ ---> ]  Rebuilding kernel extensions cache...
[  OK  ]  Rebuild kernel extensions cache.
[  OK  ]  Clean up.
[ Note ]  Congratulations! All operation has been completed.
[ Note ]  Reboot now. Then enjoy your OS X! -syscl/lighting/Yating Zhou @PCBeta.
KCdeMacBook-Pro:m3800 KCWONG$

**Comment by syscl** [comment]
感谢你的反馈, 创建sleepwatcher目录问题已经修复.

**Comment by AKA-KC** [comment]
重装了还是存在 引导撕裂问题......真难受.......

**Comment by syscl** [comment]
什么系统版本？

**Comment by AKA-KC** [comment]
10.11.4

**Comment by syscl** [comment]
一直撕裂么？

**Comment by AKA-KC** [comment]
不是.....一进引导有个小苹果进度条....小苹果进度条换大进度条就开始左右4个虚苹果.....就闪一下.....

**Comment by syscl** [comment]
那一下是正常的, 因为用了verbose模式来引导所以会有那么一瞬间的glitch, 正常现象. 除非以后发现了更好的方法修复这个问题（intel驱动的锅）

---

As except, this is due to we use verbose emulation mode to solve boot glitches. (Intel driver's issue).

**Comment by AKA-KC** [comment]
那好吧...谢谢回复

工作顺利
