### ISSUE TITLE
HiDPI flicker

### ISSUE THREAD

**Issue by ssmith353** [syscl/M3800#22]
Hey @syscl,
I was able to get your script to work well on my 2015 Precision M3800! Thanks for all your work! 

I have one issue though; HiDPI is enabled, and works. But I cannot set it to the max resolution. The screen flickers, and eventually stays dark, not until I switch it to a higher DPI setting does it work again. Do you know how to fix this? 

Also, I don't have any sound devices showing. I can plug in an External USB sound card and it works; but the internal sound isn't functional. Any ideas for that? 

(I used the most recent copy of your repo pulled last night) https://github.com/syscl/M3800/commit/56089d44ce2d105699e8a950cb5fade80336afcb

**Comment by syscl** [comment]
Hi @ssmith353 ,

Which specs does your M3800 use?

To solve this issue: we will need ioreg(refer: http://www.tonymacx86.com/threads/guide-how-to-make-a-copy-of-ioreg.58368/), kernel.log, Clover, and kext state by typing

``` sh
kextstat >~/kextstat.txt 
Then kextstat.txt is now saved as text in ~/.
```

Upload such files and together we will try to solve your issue!
syscl

**Comment by ssmith353** [comment]
https://drive.google.com/open?id=0BxDA6ZglKMrld1ZXbFZUalAxQ28

**Comment by syscl** [comment]
OK, I will dig in it tomorrow morning  ;) 

1:00 am in my country and I feel tried these days, see you tomorrow:)

syscl

**Comment by ssmith353** [comment]
Thanks! :+1:

**Comment by syscl** [comment]
Your HDA has not been powered up, type the following command in terminal:

``` sh
sudo touch /Library/Extensions && sudo touch /System/Library/Extensions && sudo kextcache -u /
```

Then reboot and boot without caches. It's quiet possible the sound card issue affects your graphics card(e.g. press "Backspace" on keyboard, you will see white flickers on the screen...)

syscl

**Comment by ssmith353** [comment]
Hmm; I did that but no changes. If I open System Profiler -> Audio, It says "No Audio Devices"

Are there any BIOS settings to change to get the audio to work? I reran the ./Deploy.sh script twice, and didn't see any changes.

**Comment by ssmith353** [comment]
And actually the display works normally, and without issue, except for when I put it at the highest DPI setting (supposed to be like 1080).

**Comment by ssmith353** [comment]
I actually just disabled HiDPI and set a resolution of 2048x1152 instead, stable and works well. :+1: I'm still looking into the sound though.

**Comment by syscl** [comment]
Hi @ssmith353 ,
Try to set the screen refresh rate to just under 60Hz (with tool like SwitchResX). Since OS X has a limitation on 4K display with 60Hz refresh rate.

About sound issue: Try to move Clover/kexts/10.11/AppleALC.kext and CodecCommnader.kext to /L*/E* (or /S*/L*/E*)and then rebuild kernel cache by typing:

``` sh
sudo touch /Library/Extensions && sudo touch /System/Library/Extensions && sudo kextcache -u /
```

If it still not work for you, please upload your Realtek codec information for further differ(I will try to build HDA for you) under Linux by

``` sh
cat /proc/asound/card0/codec#0 > ~/Desktop/codec_dump.txt
```

syscl

**Comment by syscl** [comment]
BTW, can you please upload your unlocked BIOS(4K) for me, a friend with the same model failed to unlock his BIOS menu(strange :( ). 

Thx in advance! 

syscl

**Comment by ssmith353** [comment]
Moved the kext files to both /L/E & /S/L/E, no change. How do I get the Realtec codec info? 

I'll upload my BIOS dump tomorrow 👍

**Comment by syscl** [comment]
To get Realtek codec info you need [Ubuntu](http://www.ubuntu.com/download/desktop), make a bootable USB by UltraISO and etc...

syscl

**Comment by ssmith353** [comment]
```
Codec: Intel Haswell HDMI
Address: 0
AFG Function Id: 0x1 (unsol 0)
Vendor Id: 0x80862807
Subsystem Id: 0x80860101
Revision Id: 0x100000
No Modem Function Group found
Default PCM:
    rates [0x0]:
    bits [0x0]:
    formats [0x0]:
Default Amp-In caps: N/A
Default Amp-Out caps: N/A
State of AFG node 0x01:
  Power states:  D0 D3 CLKSTOP EPSS
  Power: setting=D0, actual=D0, Clock-stop-OK
GPIO: io=0, o=0, i=0, unsolicited=0, wake=0
Node 0x02 [Audio Output] wcaps 0x6611: 8-Channels Digital
  Converter: stream=0, channel=0
  Digital: Enabled KAE
  Digital category: 0x0
  IEC Coding Type: 0x0
  PCM:
    rates [0x7f0]: 32000 44100 48000 88200 96000 176400 192000
    bits [0x1e]: 16 20 24 32
    formats [0x5]: PCM AC3
  Power states:  D0 D3 EPSS
  Power: setting=D0, actual=D0
Node 0x03 [Audio Output] wcaps 0x6611: 8-Channels Digital
  Converter: stream=0, channel=0
  Digital: Enabled KAE
  Digital category: 0x0
  IEC Coding Type: 0x0
  PCM:
    rates [0x7f0]: 32000 44100 48000 88200 96000 176400 192000
    bits [0x1e]: 16 20 24 32
    formats [0x5]: PCM AC3
  Power states:  D0 D3 EPSS
  Power: setting=D0, actual=D0
Node 0x04 [Audio Output] wcaps 0x6611: 8-Channels Digital
  Converter: stream=0, channel=0
  Digital: Enabled KAE
  Digital category: 0x0
  IEC Coding Type: 0x0
  PCM:
    rates [0x7f0]: 32000 44100 48000 88200 96000 176400 192000
    bits [0x1e]: 16 20 24 32
    formats [0x5]: PCM AC3
  Power states:  D0 D3 EPSS
  Power: setting=D0, actual=D0
Node 0x05 [Pin Complex] wcaps 0x40778d: 8-Channels Digital Amp-Out CP
  Control: name="IEC958 Playback Con Mask", index=0, device=0
  Control: name="IEC958 Playback Pro Mask", index=0, device=0
  Control: name="IEC958 Playback Default", index=0, device=0
  Control: name="IEC958 Playback Switch", index=0, device=0
  Control: name="ELD", index=0, device=3
  Amp-Out caps: ofs=0x00, nsteps=0x00, stepsize=0x00, mute=1
  Amp-Out vals:  [0x00 0x00]
  Pincap 0x0b000094: OUT Detect HBR HDMI DP
  Pin Default 0x18560010: [Jack] Digital Out at Int HDMI
    Conn = Digital, Color = Unknown
    DefAssociation = 0x1, Sequence = 0x0
  Pin-ctls: 0x00:
  Unsolicited: tag=01, enabled=1
  Power states:  D0 D3 EPSS
  Power: setting=D0, actual=D0
  Devices: 0
  Connection: 0
  In-driver Connection: 3
     0x02 0x03 0x04
Node 0x06 [Pin Complex] wcaps 0x40778d: 8-Channels Digital Amp-Out CP
  Control: name="IEC958 Playback Con Mask", index=1, device=0
  Control: name="IEC958 Playback Pro Mask", index=1, device=0
  Control: name="IEC958 Playback Default", index=1, device=0
  Control: name="IEC958 Playback Switch", index=1, device=0
  Control: name="ELD", index=0, device=7
  Amp-Out caps: ofs=0x00, nsteps=0x00, stepsize=0x00, mute=1
  Amp-Out vals:  [0x00 0x00]
  Pincap 0x0b000094: OUT Detect HBR HDMI DP
  Pin Default 0x18560010: [Jack] Digital Out at Int HDMI
    Conn = Digital, Color = Unknown
    DefAssociation = 0x1, Sequence = 0x0
  Pin-ctls: 0x40: OUT
  Unsolicited: tag=02, enabled=1
  Power states:  D0 D3 EPSS
  Power: setting=D0, actual=D0
  Devices: 0
  Connection: 3
     0x02 0x03* 0x04
Node 0x07 [Pin Complex] wcaps 0x40778d: 8-Channels Digital Amp-Out CP
  Control: name="IEC958 Playback Con Mask", index=2, device=0
  Control: name="IEC958 Playback Pro Mask", index=2, device=0
  Control: name="IEC958 Playback Default", index=2, device=0
  Control: name="IEC958 Playback Switch", index=2, device=0
  Control: name="ELD", index=0, device=8
  Amp-Out caps: ofs=0x00, nsteps=0x00, stepsize=0x00, mute=1
  Amp-Out vals:  [0x00 0x00]
  Pincap 0x0b000094: OUT Detect HBR HDMI DP
  Pin Default 0x18560010: [Jack] Digital Out at Int HDMI
    Conn = Digital, Color = Unknown
    DefAssociation = 0x1, Sequence = 0x0
  Pin-ctls: 0x00:
  Unsolicited: tag=03, enabled=1
  Power states:  D0 D3 EPSS
  Power: setting=D0, actual=D0
  Devices: 0
  Connection: 0
  In-driver Connection: 3
     0x02 0x03 0x04
Node 0x08 [Vendor Defined Widget] wcaps 0xf00000: Mono

```

**Comment by syscl** [comment]
Hi @ssmith353  ,
You are in the right way :)

I've just seen codec#0.txt but that's about HDMI audio, we need the realtek one. In this case, type

``` sh
cat /proc/asound/card0/codec#1 > ~/Desktop/codec_dump.txt
```

syscl

**Comment by ssmith353** [comment]
I didn't save my patched bios after I updated it on my machine, and haven't been able to find a way to save it from linux or freedos. I'll keep looking into it. 

But I updated my google drive link to have all my /proc/asound files

[https://drive.google.com/open?id=0BxDA6ZglKMrld1ZXbFZUalAxQ28
](https://drive.google.com/open?id=0BxDA6ZglKMrld1ZXbFZUalAxQ28)

**Comment by syscl** [comment]
Use this to dump BIOS: https://github.com/syscl/M3800/tree/M3800/unlocked%20BIOS/AFUWINx64

AFUWINx64.EXE-->Save.

syscl

**Comment by syscl** [comment]
Oh, dear @ssmith353 , 

Does this asound your whole directory? Unfortunately, I haven't seen any realtek sound card (M3800/XPS9530: ALC668). Do you note that Ubuntu has a correct sound output? 

I'm afraid the ALC668 on your M3800 is missed just like https://github.com/syscl/M3800/issues/14

syscl

**Comment by ssmith353** [comment]
I can't run the windows afuwinx64.exe, I only have OSX installed. I'll keep looking into it. 

Hmmmm.

**Comment by ssmith353** [comment]
I tried Ubuntu again, and uploaded the entire sound folder to here

https://drive.google.com/open?id=0BxDA6ZglKMrld1ZXbFZUalAxQ28

**Comment by syscl** [comment]
Does the sound act normal under Ubuntu?

**Comment by ssmith353** [comment]
I have two identical machines; one with OSX one with Ubuntu; I got the sound files from the one with Ubuntu fully installed (sound working). It didn't work from the Ubuntu Live USB

**Comment by ssmith353** [comment]
Okay, I was able to get the bios, and I re-patched it. 

Attached here: 

https://drive.google.com/folderview?id=0BxDA6ZglKMrlWVlNempPRGNWa2c&usp=sharing

**Comment by syscl** [comment]
I mean maybe the OS X one has the sound card problem like issue #14 .

Thx!

**Comment by ssmith353** [comment]
Hmm. It might be similar. I don't have sound when I boot into Ubuntu, except through the HDMI port, but it was working normally under windows. I'll keep looking into it.

**Comment by syscl** [comment]
Hi, @ssmith353 ,

Try inject  "retina/Hi-DPI" 1680x945 (3360x1890). You can use Hi-DPI [here](https://github.com/syscl/Enable-HiDPI-OSX) to set high resolution.

I was thinking of rebuild AppleHDA for you.

**Comment by ssmith353** [comment]
I was able to get the graphics to work using SwitchResX and creating a custom resolution - its been working well :) 

I would appreciate that! But I think it might also be the issue point out in #14; but I don't have any audio through the headphone jack. And in Ubuntu the only sound device recognized is the HDMI audio out.

**Comment by syscl** [comment]
Yes, hardware issue, try to replace it A.S.A.P if in warranty.

**Comment by ssmith353** [comment]
Hey @syscl thanks for the tip about the hardware issue. 

Turns out it was broken. I've gotten the computer replaced, but still don't have sound. (I actually got it replaced with the XPS 9530). 

The sound devices show up in System Profiler, and the microphone works. There is quiet audio from a very small internal speaker; and nothing from the headphones. Any tips?

**Comment by syscl** [comment]
fully sleep.

**Comment by ssmith353** [comment]
I put it to sleep, and have restarted, no change. Any other ideas? 

It makes weird noises randomly; but isn't working properly.

**Comment by syscl** [comment]
Oh, I've experienced that issue before, but I fixed it now. Your problem is due to CodecCommander.kext. Use the CodecCommander.kext in github.com/syscl/M3800/Kexts

If place CodecCommander.kext in Clover do not work, place it in /L*/E* or /S*/L*/E* then rebuild cache by typing 

``` sh
sudo touch /System/Library/Extensions && sudo touch /Library/Extensions && sudo kextcache -u /
```

**Comment by ssmith353** [comment]
Hmm, that made the weird noises go away, but still no sound through the headphones; only through the internal speaker. I'll keep looking into it

**Comment by syscl** [comment]
Umm, try fully sleep.

Note: there's a minor bug if you plug-in your headphone then cold boot OS X, you will lose sound from headphone. It will also affect Windows and Linux as well. If you cold boot with plugged-in headphone, the only solution now is to put your laptop into sleep mode about 1min.

////

**Comment by ssmith353** [comment]
Weird; that fixed it. let it sleep for a few minutes, and headphones work great. 

Thanks @syscl!

**Comment by syscl** [comment]
@ssmith353 I'm pretty happy to hear that. I may look into this problem one day since I always plug-in hp all the time. It's very possible that laptop is initialed something during sleep or wake from sleep(Because you can use the same procedure in Windows to fix this bug as well).

You can try to place CodecCommander.kext under Clover, and remove it from /S*/L*/E* or /L*/E*. See if this work.

An off-topic question @ssmith353 : How do you solve the 4K display black screen issue? Some people asked me for help, but I have not the 4K M3800/XPS 9530. Thks.

**Comment by ssmith353** [comment]
@syscl I'm using SwitchResX, and selected a custom resolution. It is very stable, and hasn't had any issues, (I am using the Intel graphics, not the nVidia). When I use hiDPI on a higher resolution I get a black screen.

**Comment by syscl** [comment]
@ssmith353 Their issue is that how can they manipulate the OS X during black screen especially after executing deploy.sh.

Thks.

**Comment by ssmith353** [comment]
@syscl, I had System Preferences open open to the display panel, and acted quickly. The screen flickered, just enough to select a different option before it went completely black.

**Comment by syscl** [comment]
@ssmith353 lol, thks. Interesting and effective solution ;) 

I will let him know.

How about https://github.com/syscl/Enable-HiDPI-OSX ? Does this work on your 4K model with an appropriate resolution injection?

**Comment by ssmith353** [comment]
Hey @syscl, 
Yeah, It works, I currently have it setup on my internal monitor. I have it injecting, 2048 x 1152 :)

**Comment by ssmith353** [comment]
hey @syscl, 
Do you have any issues with adjusting your screen (back and forth) and the screen going black? It stays lit, but with no image unless I fully sleep and wake. 

Mine is having issues, and I'm trying to determine if its a software/hardware issue.

**Comment by syscl** [comment]
Going black by adjusting screen? Weird, I've tested it for you, no such issue.

Maybe hardware related issue, try adjust screen under Windows.

////

**Comment by ssmith353** [comment]
Looks like it's gone away for now; tried in Ubuntu, reproduced. I think its a loose connector. 

Thanks for checking!

**Comment by ssmith353** [comment]
Hey @syscl, got my computer replaced again to fix the screen issue. The new one came with an Intel wireless card, so I ordered a [new Broadcom one.](http://www.ebay.com/itm/231982664861?_trksid=p2060353.m2749.l2649&ssPageName=STRK%3AMEBIDX%3AIT). And it shows up in the Wi-Fi menu, but its always in the "OFF" state, and I can't turn it on. Have any ideas? 

Thanks for your help! :)

Edit:I actually was able to tape over two of the contacts that forced the card into the off state. And now it works!

**Comment by ssmith353** [comment]
Hey @syscl, I had to reflash the BIOS on my XPS 9530, so I made a copy for it to be added to the repo! 

XPS 9530 A09 Patched: https://drive.google.com/open?id=0BxDA6ZglKMrldjMtN1ZKZHBVVXM

**Comment by syscl** [comment]
@ssmith353 

Hi, is this QHD+(3200x1800) or UHD(3840x2160) bios?

Thanks,
syscl

**Comment by syscl** [comment]
@ssmith353 BTW, try the latest Enable-HiDPI-OSX as well :)

syscl

**Comment by ssmith353** [comment]
This is for UHD 4K bios :)

Sent from my iPhone

On Oct 2, 2016, at 11:41, Zhou Yating notifications@github.com wrote:

@ssmith353 https://github.com/ssmith353 BTW, try the latest
Enable-HiDPI-OSX as well :)

syscl

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
https://github.com/syscl/M3800/issues/22#issuecomment-250953346, or mute
the thread
