### ISSUE TITLE
蓝牙问题....触摸板问题

### ISSUE THREAD

**Issue by AKA-KC** [syscl/M3800#23]
Q:1
蓝牙一断开就连不上......
Q:2
触摸板轻触点击不行么.......

以上问题.....

幸苦你了.......

**Comment by syscl** [comment]
触摸板需要改变速度一下才能使用双指.

启动轻击需要开启设置-->点按功能(这个和Mac一样都需要设置, 否则默认是关闭的). 

蓝牙尝试着把蓝牙相关的驱动(BrcmPatchRAM2+BrcmFirmwareRepo)安装到/S*/L*/E*下面去吧. 注意删除掉Clover/kexts/10.11下面BrcmPatchRAM2+BrcmFirmwareRepo/BrcmFirmwareData.

syscl

**Comment by AKA-KC** [comment]
问题已解决....可以了.....谢谢帮忙.....

工作愉快

**Comment by syscl** [comment]
很高兴你的问题都解决了.

蓝牙问题也解决了吗？用了哪个kext解决的？安装到哪了？

syscl

**Comment by AKA-KC** [comment]
蓝牙就用你那两个驱动安装到/S/E/L 就可以直接连接了....不过存在时不时爆音问题.....

谢谢回复......

**Comment by syscl** [comment]
爆音问题??这个就比较神奇了. 可能需要你的声卡节点信息才能进一步判断.

感谢你的反馈.
