### ISSUE TITLE
求教程及资料下载

### ISSUE THREAD

**Issue by lncken** [syscl/M3800#24]
```
  上次装黑苹果之后patch了bios后手贱升级bios，结果出问题了戴尔售后修了之后因为一直在做ctf比赛，没啥时间就没怎么折腾，最近有空了，上来求个镜像的写入工具和镜像下载链接，多谢。
```

**Comment by syscl** [comment]
这么悲催..

现在修好了吗？

Bios解锁按照http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1635737&extra=&page=1&mobile=yes

其余的按照Github里面的来就好！
