### ISSUE TITLE
1920x1080  i5-4200h，可以用么？？

### ISSUE THREAD

**Issue by busymilk** [syscl/M3800#25]
你好，我的xps是1920x1080  i5-4200h，请问可以直接执行你的脚本么，谢谢😊

**Comment by syscl** [comment]
你是XPS9530或者是M3800吗?

**Comment by syscl** [comment]
@busymilk 感谢你的反馈 我已经增加i5 4200H的初步支持. 请尝试. 从理论上来说, 安装完全没有问题, 只要按照我的步骤进行BIOS破解并且按照Github里面的来设置BIOS下载脚本即可! 祝你成功. 等待你的进一步反馈.

---

@busymilk Thks for your hint that there's i5 model existed in M3800/XPS9530, I used to think that only i7 version on M3800/XPS9530. I've added support for your model, please try :)

Best wishes
syscl

**Comment by busymilk** [comment]
替换了CLOVER，也把生成的acpi那些文件拷贝进去了，执行完脚本，重启，进不去系统。。。
不替换CLOVER的话，执行脚本，好像也没起作用，键盘啥的还是没起作用。。。

对了，执行脚本的时候，并不是所有的都是输出ok的，而是有2条提示没有文件或目录，定位到到是我下载的M3800目录里，不知道是不是这里出的问题？

**Comment by syscl** [comment]
截图给我. 提示错误就有问题!

**Comment by busymilk** [comment]
[FAILED]  Compile SgRef.
Error    6092 - Could not open file "/Users/qin_mac/Downloads/aaa/M3800/DSDT/precompile/.dsl" (Source Input) - No such file or directory

Intel ACPI Component Architecture
ASL+ Optimizing Compiler version 20141107-64 [Jan  2 2015]
Copyright (c) 2000 - 2014 Intel Corporation

[FAILED]  Compile OptRef.
Error    6092 - Could not open file "/Users/qin_mac/Downloads/aaa/M3800/DSDT/precompile/.dsl" (Source Input) - No such file or directory

**Comment by syscl** [comment]
在Clover界面下按Fn+F4或者F4，然后进入系统执行脚本.

**Comment by syscl** [comment]
@busymilk 参看issue #54 , 确认i5可以完美运行.

syscl
