### ISSUE TITLE
Bluetooth won't work.

### ISSUE THREAD

**Issue by SaulGoodman1337** [syscl/M3800#27]
Hi,
i have a new Broadcom and Bluetooth wont work.
WLAN works.

https://abload.de/img/bildschirmfoto2016-06i9ucu.png

Thanks

edit:
I cant find my notebook from my Smartphone and can't find my Smartphone from my Notebook.

**Comment by syscl** [comment]
OK, try the following:
1. Remove BrcmFirmwareData.kext + BrcmPatchRAM2.kext in Clover/EFI/kexts/10.11
2. Install BrcmFirmwareData.kext + BrcmPatchRAM2.kext in /S*/L*/E* or /L*/E*. The two kexts located in ~/M3800/Kexts
3. Rebuild kernel cache by typing:

``` sh
sudo touch /S*/L*/E* && sudo touch /L*/E* && sudo kextcache -u /
```

Wait for your feedback.
syscl

**Comment by SaulGoodman1337** [comment]
Works. Thanks ! 

https://abload.de/img/bildschirmfoto2016-06ziu3k.png

Greetings Daniel
