### ISSUE TITLE
After Sleep high package drop an wifi is slow.

### ISSUE THREAD

**Issue by SaulGoodman1337** [syscl/M3800#28]
Hi.... 💃 

after Sleep my package drop is extremly high and wifi is unusable... a restart is need to fix this.. any idea?

**Comment by syscl** [comment]
Weird, try the following:
1. Move Clover/kexts/10.11/FakePCIID.kext + Clover/kexts/10.11/FakePCIID_Broadcom_WiFi.kext to /S*/L*/E* or /L*/E*
2. Rebuild kernel caches by:

``` sh
~/M3800/tools/rebuild
```

Wait for your feedback.
syscl

**Comment by SaulGoodman1337** [comment]
wont work....

**Comment by syscl** [comment]
Which Wi-Fi card do you use?

Can you post me a copy of ioreg?

syscl

**Comment by SaulGoodman1337** [comment]
sure.
ioreg = http://pastebin.com/mYRjsfP4

My wifi card is a brand new Broadcom BCM94352Z. 
Bought 3 days ago from here : http://tinyurl.com/jnmp7ul.

Please tell me what information you need from me. you got what ever you want.

When my notebook wakes up, wifi need very long to find Networks (1 minute).

**Comment by SaulGoodman1337** [comment]
edit : Bluetooth still not available after sleep

**Comment by SaulGoodman1337** [comment]
When I think about it, I had the problem already with Windows and Ubuntu both. But as yet map with the Intel WiFi.
After exchanging broadcom with, the problem seems to occur still.

This appears to be a hardware problem that could be fixed with newer drivers.

Source:
http://en.community.dell.com/support-forums/laptop/f/3518/t/19621282
http://en.community.dell.com/support-forums/software-os/f/3525/t/19630366

and so on ....

**Comment by syscl** [comment]
@danielpondruff Thank you! I will dig into it. 

I have the same hardware as you before, but I haven't got the issue you post. So I have to see more information about it.

syscl

**Comment by SaulGoodman1337** [comment]
last dmesg from the issue:

> ARPT: 1049.769849: AirPort_Brcm43xx::powerChange: System Wake - Full Wake/ Dark Wake / Maintenance wake
> ARPT: 1050.270639: IOPMPowerSource Information: onWake,  SleepType: Normal Sleep,  
> ARPT: 1050.270723: AirPort_Brcm43xx::platformWoWEnable: WWEN[disable]
> ARPT: 1050.271048: AirPort_Brcm43xx::syncPowerState: WWEN[disabled]
> AirPort: Link Down on en0. Reason 8 (Disassociated because station leaving).
> en0::IO80211Interface::postMessage bssid changed
> IO80211AWDLPeerManager::interfaceStateChange WD reset in progress, not enabling AWDL yet! Interface
> PM response took 305 ms (50, powerd)
> chip reset completed! configuring AWDL!
> IO80211AWDLPeerManager::configure Dynamic country code not supported on this device
> IO80211AWDLPeerManager::setChannelSequenceUnconditional : Couldn't set channel sequence! coded length 16 length 64 step 3 fill ff (Scan + Data):
> 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
> ARPT: 1050.902659: wlc_dump_aggfifo:
> ARPT: 1050.902683: framerdy 0x0 bmccmd 5 framecnt 1024 
> ARPT: 1050.902742: AQM agg params 0x3f maxlen hi/lo 0x0 0xffff minlen 0x0 adjlen 0x0
> ARPT: 1050.902794: AQM agg results 0xa000 len hi/lo: 0x0 0x0 BAbitmap(0-3) 0 0 0 0
> ARPT: 1050.971210: wlc_dump_aggfifo:
> ARPT: 1050.971239: framerdy 0x0 bmccmd 5 framecnt 1024 
> ARPT: 1050.971305: AQM agg params 0x3f maxlen hi/lo 0x0 0xffff minlen 0x0 adjlen 0x0
> ARPT: 1050.971377: AQM agg results 0xa000 len hi/lo: 0x0 0x0 BAbitmap(0-3) 0 0 0 0
> AirPort: Link Up on awdl0
> Setting BTCoex Config: enable_2G:1, profile_2g:0, enable_5G:1, profile_5G:0
> IO80211AWDLPeerManager::setAwdlOperatingMode Setting the AWDL operation mode from AUTO to SUSPENDED
> IO80211AWDLPeerManager::setAwdlSuspendedMode() Suspending AWDL, enterQuietMode(true)
> en0: channel changed to 1
> AirPort: Link Up on en0
> en0: BSSID changed to **:**:**:**:**:**
> en0: channel changed to 44,80
> en0::IO80211Interface::postMessage bssid changed
> AirPort: RSN handshake complete on en0
> Unexpected payload found for message 9, dataLen 0
> IO80211AWDLPeerManager::setAwdlOperatingMode Setting the AWDL operation mode from SUSPENDED to AUTO
> IO80211AWDLPeerManager::setAwdlAutoMode Resuming AWDL

**Comment by syscl** [comment]
@danielpondruff uncheck "Wake for Wi-Fi network access" in ```System Preference```->```Energy Saver```->```Power Adapter```

syscl

**Comment by syscl** [comment]
Hi @danielpondruff Please try the latest config to see if this solve your Wi-Fi issue :)

Good luck,
syscl
