### ISSUE TITLE
Crazy colors after IOKit Patch

### ISSUE THREAD

**Issue by SaulGoodman1337** [syscl/M3800#29]
After a new IOkit Patch (i've used one from 10.11.3, now newest 10.11.5) i have some crazy colors on my screen. 
After Post installation i tried some things and forgot i used a old one IOkit with my new installation.
Outlook an some other Apps doesn't start. 

I have replaced IOKit and patched it. Now the Apps starts normaly but i have some crazy color issue. 
does it mean anything to you?

https://abload.de/img/bildschirmfoto2016-06t4uqa.png

Greetings Daniel

**Comment by SaulGoodman1337** [comment]
Fixed with SwitchResX.
Sorry.

**Comment by syscl** [comment]
I know what's going on, just typing the following fix the issue:

``` sh
~/M3800/tools/rebuild
```

syscl

**Comment by SaulGoodman1337** [comment]
can you please explain me for learning whats exactly the problem here is?

**Comment by syscl** [comment]
due to kernel cache not update and ig-platform-id.
