### ISSUE TITLE
Headphone do not work

### ISSUE THREAD

**Issue by SaulGoodman1337** [syscl/M3800#30]
Hi,

if i plugged in my headphone sound output do not work.
In Settings OSX reorganized the headphone plugin correctly.

**Comment by SaulGoodman1337** [comment]
any news here ?

**Comment by syscl** [comment]
Headphone issue is due to plug-in headphone during cold boot. This is a known issue and the only solution is to try fully sleep about 1 min.

syscl

**Comment by SaulGoodman1337** [comment]
This workaround won't work for me...

**Comment by SaulGoodman1337** [comment]
is it possible to fix this issue with a new Codeccommander?

"New in version 2.6.1, CodecCommander can be used to patch pin configurations instead of patching AppleHDAHardwareConfigDriver.kext"

**Comment by syscl** [comment]
Do you check the hp issue under Windows or Ubuntu?

Not related, CodecCommander with new version (version that greater than 2.5.1) is unstable. I still remember that after updating to new version of CodecCommnader, the hp output is totally corrupted and cause randomly kernel panic by other users' with different specification. So, for a more stable system, I have to test it until I convince it's stable enough to update.

syscl
