### ISSUE TITLE
Random panic on Sierra with DW1820A(BCM94350)

### ISSUE THREAD

**Issue by syscl** [syscl/M3800#32]
Well, till now, there's no clues but random kernel panic on Sierra. 

Will post kernel panic information later. 

Weird issue since a lot people have reported such issue with Sierra on different PC.

syscl

**Comment by syscl** [comment]
This also cause a long suspend on Dell Logo on Dell Precision M3800/XPS9530 with boot options resetting.

**Comment by syscl** [comment]
Confirmed, DW1820(BCM94350+BT94350) will cause kernel panic. 

But still, macOS Sierra Public Beta(PB) 2 will boot slow at the first time(about 1min or so). Once we boot into the Sierra PB2, no more boot slow issue occurs at the next reboot.

syscl

**Comment by x4080** [comment]
Hi can DW1820A works? I'm using 9350

**Comment by syscl** [comment]
@x4080 I have no time to explore into Wi-Fi, maybe it can be fixed through some binary patches. But, for me, it's fairly easy to replace one that can be powered up.

Hint: I do not use DW1560, it's obviously not the best solution for XPS 13 9350!

syscl

**Comment by x4080** [comment]
Oh, do you use Intel one?

**Comment by syscl** [comment]
I use DW1830 for both M3800 and XPS 13 9350.

I am the one who's the first that use DW 1830 on XPS 13 9350.

syscl

**Comment by x4080** [comment]
OK thanks

**Comment by gujiangjiang** [comment]
中文问吧，我的DW1830的蓝牙偶尔开机会卡住，要过1分钟左右才能进系统，而且进系统之后蓝牙没有驱动，我怀疑是rm的brcm驱动导致的，你的有这种情况么？

**Comment by syscl** [comment]
@gujiangjiang 看卡住时候的日志，更像是你用了Kexts的补丁

我在3800上和XPS13 上面都是DW1830没有遇到过这个问题。

**Comment by gujiangjiang** [comment]
@syscl 没有任何补丁，我在10.12下面wifi是原生驱动的，蓝牙就用了data和brcm补丁，大部分时间是正常的，偶尔会卡开机，但是我-v的时候又好像没什么事，每次都看不到-v图。。。

**Comment by gujiangjiang** [comment]
我已经抛弃rm的驱动该用原生驱动了。。。不知道如何写入clover

**Comment by syscl** [comment]
@gujiangjiang 
- FakePCIID我也在维护，这个驱动的真正作用就在于去更好的使用原生驱动
- 开机卡一下的问题，我估计和你开启了HWPEnable有关，这是已知的会引起数据严重损坏的参数，一经开启便无法关闭，只能重装。

syscl

**Comment by gujiangjiang** [comment]
HWPEnable 没开启过。。。。我用的cc，没有这个参数。。。
不是开机卡一下，而是偶尔开机的时候进度条异常缓慢，进去之后发现蓝牙未驱动的问题，偶尔出现。

还有，今天我尝试了一下直接注入蓝牙ID，发现系统能原生上传固件，但是极易掉固件，你看看能解么。

**Comment by syscl** [comment]
@gujiangjiang 我遇到过类似的问题，不过是在`DW1820`上面碰到的，几乎和你的描述一模一样，你用的是BRCM什么驱动，有两个，我使用的是:
- BrcmPatchRAM2.kext 
- BrcmFirmwareRepo.kext/Contents/Info.plist: `disabled_IOResources` -> `IOResources`
- 通过Clover注入
- 利用[这里](https://github.com/syscl/XPS9350-macOS/tree/master/tools) 的rebuild来重建缓存

syscl

**Comment by gujiangjiang** [comment]
这样不行的，用这个的话开机后显示蓝牙已经驱动，但是搜不到任何设备，只能用Data。。。

对了，我放在Clover下面的。。。

**Comment by gujiangjiang** [comment]
我尝试过这个，http://bbs.pcbeta.com/viewthread-1605545-1-28.html，里面的injecter，删掉rm的驱动，一样可以原生驱动蓝牙，但是同样的无法搜索到任何设备，不清楚为什么

**Comment by x4080** [comment]
@syscl, how much is your dw1830? About 30? And is it working well? I stumble on it in AliExpress

**Comment by syscl** [comment]
@x4080 what's that AliExpress?

syscl

**Comment by x4080** [comment]
it's from Jack Ma, shopping app like eBay
