### ISSUE TITLE
Suddenly, iMessage stops working

### ISSUE THREAD

**Issue by scopolamine1401** [syscl/M3800#33]
Dear syscl,

Today, my iMessage suddenly stops working and shows authentication error.
Can you help me on this issue?
Thank you so much.
![screen shot 2016-07-17 at 8 02 46 pm](https://cloud.githubusercontent.com/assets/18452230/16904345/d2aa6648-4c59-11e6-997c-527d8ff1d077.png)

**Comment by ssmith353** [comment]
Mine also stopped working, but I followed this guide and now it works again [http://www.tonymacx86.com/threads/an-idiots-guide-to-imessage.196827/](http://www.tonymacx86.com/threads/an-idiots-guide-to-imessage.196827/)

**Comment by scopolamine1401** [comment]
Thank you so much. It works now
