### ISSUE TITLE
HDMI 偶尔会花屏

### ISSUE THREAD

**Issue by shiweifu** [syscl/M3800#4]
拔了再插一次就正常啦，遇见几次了
10.10.5

**Comment by syscl** [comment]
稍后我会单独查看你的问题。我感觉可能跟dsdt以及ssdt的patches有关。最近身体不舒服，下周跟你探讨这个问题吧。

**Comment by shiweifu** [comment]
好好休息！
这个是很小的问题，基本不影响使用

**Comment by syscl** [comment]
我更新了脚本，你再试一下吧：）

**Comment by syscl** [comment]
已经更新了HDMI相关的patch和驱动。并且修正了冷启动耳机无声的问题。

I've already updated drivers and patches for HDMI. And also, I fixed the issue that HP will lose sound after a cold boot.

**Comment by shiweifu** [comment]
OK，有空我再试一下。
对了，m3800制作的tm备份，恢复到白苹果上，白苹果没有声音，应该是驱动文件被覆盖了……

PS：还是对独立显卡有点残念。

**Comment by syscl** [comment]
白果没声音是因为/Library/Extensions/AppleHDA_ALC668.kext的干扰，在终端中以管理员模式移除（或者在Recovery HD模式下）：
sudo rm -R /Library/Extensions/AppleHDA_ALC668.kext
sudo kextcache -u /

////
