### ISSUE TITLE
macOS Sierra Support

### ISSUE THREAD

**Issue by froggr** [syscl/M3800#40]
continued from #34 

after updating to Sierra PB 7, touchpad improvements are present which is a big improvement (thanks @syscl). No boot issues at all. Bluetooth, wifi, sound working the same as 10.11.

Function keys for sound, multimedia, brightness etc are still not working.

Otherwise, quite usable!

**Comment by froggr** [comment]
[Kernel_2016-09-14-090009_Froggers-CrackBook-Pro.panic.txt](https://github.com/syscl/M3800/files/472099/Kernel_2016-09-14-090009_Froggers-CrackBook-Pro.panic.txt)

Also just to note, on both Sierra and 10.11.6, the most recent updates to the script cause a kernel panic when returning from sleep

**Comment by syscl** [comment]
@froggr thanks for your feedback, do this issue occur all the time?

I'm in the 10.11.6 with the latest update for a while, and never shutdown my M3800(just sleep it). Pretty stable.

I saw your log, still too busy, but I guess maybe you can rebuild your kernel caches to see if the problem solve

``` sh
M3800/tools/rebuild
```

Wait for your feedback(the issue may located in AppleIntelAzul seen from your log).
syscl

**Comment by froggr** [comment]
@syscl yes it does. It has been extremely stable until this started and it is happening on both this machine (10.11.6) as well as sierra.

I've rebuilt the kernel caches and will get back to you. Thanks!

**Comment by syscl** [comment]
@froggr does the rebuild fix your issue?

syscl

**Comment by froggr** [comment]
@syscl all seems well! 

Previously I rebuilt the caches before by re-running the script but that did not help. I'll let you know if anything else happens

**Comment by bochamsua** [comment]
Hi guys,
I just tried with the final 10.12 but wifi was not working.
Its very strange because bluetooth still worked.

**Comment by syscl** [comment]
@bochamsua Please at least provide your WiFi module, otherwise any one cannot help you.

In 10.12, there is a known issue related to WiFi that has been well solved by the-darkvoid, pay attention to the issue #34 , try this patch:

``` sh
Kext:    AirPortBrcm4360
Find:    81F952AA00007529 
Replace: 81F952AA00006690
```

Through Clover's config.plist:

``` sh
<dict>
    <key>Comment</key>
    <string>AirPortBrcm4360 - fcvo</string>
    <key>Disabled</key>
    <false/>
    <key>Find</key>
    <data>gflSqgAAdSk=</data>
    <key>Name</key>
    <string>AirPortBrcm4360</string>
    <key>Replace</key>
    <data>gflSqgAAZpA=</data>
</dict>
```

syscl

**Comment by bochamsua** [comment]
@syscl I have BCM94352Z.
So I should put these in config.plist?
`<dict>
    <key>Comment</key>
    <string>AirPortBrcm4360 - fcvo</string>
    <key>Disabled</key>
    <false/>
    <key>Find</key>
    <data>81F952AA00007529</data>
    <key>Name</key>
    <string>AirPortBrcm4360</string>
    <key>Replace</key>
    <data>81F952AA00006690</data>
</dict>`

**Comment by bochamsua** [comment]
`<dict>
    <key>Comment</key>
    <string>AirPortBrcm4360 - fcvo</string>
    <key>Disabled</key>
    <false/>
    <key>Find</key>
    <data>81F952AA00007529</data>
    <key>Name</key>
    <string>AirPortBrcm4360</string>
    <key>Replace</key>
    <data>81F952AA00006690</data>
</dict>`

**Comment by syscl** [comment]
@bochamsua BCM94352z indeed requires that patch, refer to 

``` sh
M3800/config.plist/KernelAndKextPatches/KextsToPatch
```

You will know how to add the patch yourself.

syscl

**Comment by bochamsua** [comment]
Thank you, I tried, it worked.
However iMessage and Facetime dont work.
Could you help me out?

**Comment by syscl** [comment]
@bochamsua What do you mean by iMessage and FaceTime don't work?

Do you mean you cannot login? 

In my laptop, not such issue. So you have to be more explicit and better to show some screenshot about it.

syscl

**Comment by bochamsua** [comment]
@syscl Yes, I cannot login even I put the correct info.
This happened for me in 10.11 before so I went back to 10.10.
I might need to wait for you to make this more stable then I will start again with 10.12.
Anyway, thank you very much for this great stuff.

**Comment by froggr** [comment]
@bochamsua i don't think this is an issue directly related to the script (@syscl correct me if I'm wrong) as apple validates against your Apple ID as well as the serial number and device ID that are injected in clover. On one m3800 I had this issue and had to fix this manually - through a google search you'll it's a very common issue. On my other m3800 I did not have any issues. I'm betting on your machine your IDs are not unique. 

What do you think @syscl?

**Comment by froggr** [comment]
Also I find the script has been very stable since early summer - mybissues have been slightly self inflicted :P

**Comment by syscl** [comment]
@froggr you answer his question... completely :)

syscl

**Comment by SaulGoodman1337** [comment]
@syscl 
"AirPortBrcm4360 - fcvo" patch works for me ! Please include in Deploy.sh.

Whats not working are the keys for Volume and Backlight. is there is fix available ?

**Comment by syscl** [comment]
@danielpondruff Don't worry, this will be fixed once Apple releases the source code of Sierra. Not so long to wait.

syscl

**Comment by syscl** [comment]
@froggr Please try the 10.12.1 from App Store, all function keys have been fixed!!

syscl

**Comment by froggr** [comment]
@syscl Will do. I'll report back once upgraded.

**Comment by SaulGoodman1337** [comment]
@syscl Wifi is broken with 12.1. These patches works for me > http://pastebin.com/wmjQJ2LN. Please include this patches and the "AirPortBrcm4360 - fcvob" to your script.
FunctionKeys works with 12.1

**Comment by froggr** [comment]
@syscl @danielpondruff Confirm that wifi is broken in 12.1. Thanks @danielpondruff for the patches, those along with AirPortBrcm4360 - fcvo fix the wifi issue. Function keys do work.

@syscl is rehabman's nullethernet patch included? I thought it used to be or perhaps I included it myself. Appstore, itunes etc doesn't work and I assume its the old "network device order" issue, with ethernet needing to come first?

**Comment by syscl** [comment]
@froggr thanks, I was wondering I have included that patch in DSDT form before, but I forgot. So I will add that patch later. 

BTW, do you have usb wifi before, since I have no order issue as you point out. But I will try to add the fix these days.

And, there's another improvement that will come into M3800/XPS9530, that is [IOPowerManagement](https://github.com/syscl/IOPowerManagement). More suggestions are welcome for that project. Wish you all like that project @bochamsua @danielpondruff @froggr 

syscl

**Comment by syscl** [comment]
@froggr @bochamsua @danielpondruff I have already included Nullethernet, name SSDT-rnme.aml, that is the DSDT version of Nullethernet. Sorry for my misleading. 

So do not worry about install the Nullethernet.kext

syscl

**Comment by froggr** [comment]
@syscl love the project! Thanks so much! I was really disappointed with the m3800 and how unstable it was until I found your project! On this machine Wifi is listed first, however I don't have any option for ethernet. I'll troubleshoot this a bit further. It could even be I need to change the serial number in the clover config (the famous imessage issue) as I'm getting some typical errors with imessage as well.

**Comment by syscl** [comment]
@froggr don't hesitate to star to support this projects ;)

iMessage is not a problem if you inject SerialNumber and BoardSerialNumber from `System Report`-->`Overview`, just take a picture from a real macbook that's enouth.

BTW, don't forget to try  [IOPowerManagement](https://github.com/syscl/IOPowerManagement)

syscl

**Comment by froggr** [comment]
@syscl starred! Can't believe I didn't already. Will try and get back to you.
