### ISSUE TITLE
更换WiFi模块，该如何选择？How to choose an appropriate WiFi module?

### ISSUE THREAD

**Issue by MawMawMawMaw** [syscl/M3800#43]
XPS9530之前用大神的脚本，10.11.6基本完美，但自带的Intel WiFi & Bluetooth没换，现在想换个博通的试试，但是不知道怎么选，而且还担心随便买一个会有后续设置方面的有问题。
所以过来向大神请教。我需要蓝牙4.0，看了一下，大家都推荐BCM94352hmb，不知能不能用？
小问题：如果用大神的脚本安装10.12.1，和之前的比稳定性如何？

After I used your script to adjust my XPS9530, macOS 10.11.6 worked almost perfectly. I didn't replace my Intel WiFi & Bluetooth module then, so I cant use those 2 functions. Now I want to replace original module to Broadcom one, but which one should I choose?
I need Bluetooth 4.0, many people recommend Broadcom  BCM94352hmb, I wonder if it work well?
Another question: If I install 10.12.1 to my laptop, will the system be as stable as the previous one?

**Comment by syscl** [comment]
兼容性 性价比 以及各种功能全都实现的话 只有94352z(DW1560, 不是联想的94352hmb)能够实现, 最新的DW1830 有一定几率在打开"Wake Wi-Fi network access"之后无法正确分配IP地址。而且94352z也是M3800和XPS9530上面专门开发和测试的，这样稳定性没得说。

为了便宜你也可以考虑QCNFA335(DELL DW1707).

为了性能DW1830妥妥的.

但是日常用我觉得DW1707就足够了(还便宜).

////

**Comment by MawMawMawMaw** [comment]
谢谢 @syscl ，我去看看94352z去，这是应该是通用且免驱的，macOS和Windows都不需要额外的设置吧？

**Comment by syscl** [comment]
要彻底免驱就dw1830, 但是dw1560, dw1707通过脚本和少许修改一样完美.

////
