### ISSUE TITLE
git clone了最新的提交导致耳机出现白噪音

### ISSUE THREAD

**Issue by Guanyunhan** [syscl/M3800#48]
系统是10.12，这个问题之前没有，现在出现了，原因是用了最新的更新，临时解决方法是休眠再唤醒

**Comment by syscl** [comment]
@Guanyunhan 
我也注意到了, Sierra在我的补丁下面应该是修复了面板切换白噪音的问题，但是最近的更新我没有办法测试（只是担心） 没想到果然还是出现了问题...

我会会滚到之前的版本 感谢你的反馈.
syscl

**Comment by PMheart** [comment]
@syscl 
好吧。。还真的挂了
不过 既然只是杂音，还有声音的话，那么就说明 zero 掉 0x10ec0884 是不需要的。
可以考虑只加入
`41C60600488BBB68 -> 41C60601488BBB68` && `41C6864301000000 -> 41C6864301000001`
这两个。
此外就是可以尝试一下 只修改 0x10ec0262 为 0x10ec0668 i.e. `6202ec10 -> 6806ec10`
在我的ALC887上ok，不过不知是否都可以。我有留意到10.12下很多ID加载规则都变了，具体的说不清楚还...
Anyway, 以下是待测试的 _install_AppleHDA_Injector() 函数（不是完整脚本 变量什么的还要依赖原始脚本啦）：
[hda.sh.zip](https://github.com/syscl/M3800/files/531782/hda.sh.zip)
