### ISSUE TITLE
Trackpad gestures and Sleep mode

### ISSUE THREAD

**Issue by ghost** [syscl/M3800#5]
Hi, and first thank for this really well written script and work.

I have everything work including QHD 3840x2160  screen (SwitchResX  I'm running 1920x1080 hdpi at 58hz). No wifi/bluetooth but i must buy the right device for that.

However i have issues with trackpad gestures. With basic installation it works (by example scrolling vertically 2 fingers in Chrome or Finder), but after using ./Deploy.sh and reboot, no more gestures (2, 3 fingers). In Trackpad panel it's activated. But don't work...

Any idea of what to do ?

Second point, when i close the lid or choose "Sleep", it never stop.

Thanks

**Comment by syscl** [comment]
Do you install any other trackpad driver such as VoodooPS2Controller.kext in/S_/L_/E\* or /L_/E_ or under /EFI/Clover/kext/*/ ? If yes, removed it and rebuild kernel cache by following command line in a terminal:

``` sh
sudo touch /System/Library/Extensions/
```

``` sh
sudo touch /Library/Extensions/
```

and

``` sh
sudo kextcache -u /
```

To active scrolling, you have to change the speed of scrolling once under SysPref/Trackpad/ (a minor bug located in ApplePS2SmartTouchpad.kext)

I've tested  VoodooPS2Controller.kext and ApplePS2SmartTouchPad.kext. With the VoodooPS2Controller.kext, both keyboard and trackpad are often not working after a fresh boot and sleep, however the latter one is much better which gives me more functions(such as zoom, 3f/4f/5f gestures and etc.), and also the trackpad driver would not  lose its response no matter how many time I sleep or reboot OS X. Hence, ApplePS2SmartTouchPad is more recommended in this scenario. 

Wait for your report.

////

**Comment by ghost** [comment]
Perfect. Just change the scrolling speed fix my gestures problems.
Many thanks
