### ISSUE TITLE
No sound and WiFi 10.12 (Dell 9530)

### ISSUE THREAD

**Issue by theupriser** [syscl/M3800#50]
Hello Syscl,

Thanks for your work!
I recently installed your automatic patch on my XPS 9530 with 10.11 and it works like a charm.
However, if I upgrade to Sierra my WiFi and Soundcard don't do anything after the patch. I tried 4 times now to install Sierra, once from a clean install but no good result.

I have a 9530 with 4k display (which works on 10.12!) but no sound, no WiFi.
My WiFi card is a Dell DW1560.

Clean install now and only applied your patch, latest release from git.
Am I doing something wrong?

With kind regards, 

Rick

**Comment by syscl** [comment]
@theupriser 
For DW1560, there's more patch you have to add to your config.plist in 10.12.x

try this patch

```
Kext:    AirPortBrcm4360
Find:    81F952AA00007529 
Replace: 81F952AA00006690
```

Through Clover's config.plist

```
<dict>
    <key>Comment</key>
    <string>AirPortBrcm4360 - fcvo</string>
    <key>Disabled</key>
    <false/>
    <key>Find</key>
    <data>gflSqgAAdSk=</data>
    <key>Name</key>
    <string>AirPortBrcm4360</string>
    <key>Replace</key>
    <data>gflSqgAAZpA=</data>
</dict>
```

BTW, in 10.12.1, there's 2 other patches for DW1560(94352z) 

```
<dict>
                <key>Comment</key>
                <string>AirPortBrcm4360 - PCI Error 1</string>
                <key>Disabled</key>
                <false/>
                <key>Find</key>
                <data>
                QTnEdRs=
                </data>
                <key>Name</key>
                <string>AirPortBrcm4360</string>
                <key>Replace</key>
                <data>
                QTnEZpA=
                </data>
            </dict>
            <dict>
                <key>Comment</key>
                <string>AirPortBrcm4360 - PCI Error 2</string>
                <key>Disabled</key>
                <false/>
                <key>Find</key>
                <data>
                QQ+3zTnBdQw=
                </data>
                <key>Name</key>
                <string>AirPortBrcm4360</string>
                <key>Replace</key>
                <data>
                QQ+3zTnBZpA=
                </data>
            </dict>
            <dict>
                <key>Comment</key>
                <string>AirPortBrcm4360 - PCI Error 3</string>
                <key>Disabled</key>
                <false/>
                <key>Find</key>
                <data>
                g33EBHQG
                </data>
                <key>Name</key>
                <string>AirPortBrcm4360</string>
                <key>Replace</key>
                <data>
                g33EBGaQ
                </data>
 </dict>
```

Or you can wait for me to include such patches in the script, but I am too busy these days. So , have a try. 

syscl

**Comment by syscl** [comment]
@theupriser 
About sound issue, run the deploy.sh again.

syscl

**Comment by theupriser** [comment]
Thanks man!
Super fast reply!

Edit: Wifi is working! (even handoff)
Now the sound >:)

**Comment by theupriser** [comment]
Okay, so for the sound I tried to run the Deploy.sh several times but it won't load the sound card. 
Also tried to rebuild with your tool, and rebuild when booting without caches. 
Do you have a suggestion?

Thanks for your time and work!

**Comment by syscl** [comment]
@theupriser 
Give me some information about the system, for example, System Reports and 

``` sh
kextstat 
```

Something like that, I have to figure out your issue.

syscl

**Comment by theupriser** [comment]
HDA seems to be running, really weird..
I'm using your standard config.plist with the added patches for wifi.

but.. Here you go!
[Archief 2.zip](https://github.com/syscl/M3800/files/562760/Archief.2.zip)

**Comment by syscl** [comment]
@theupriser 
Give me your config.plist after executing the deploy.sh

I think that the patch for HDA has finally added successfully.

syscl

**Comment by theupriser** [comment]
Here you go:
[Archief 3.zip](https://github.com/syscl/M3800/files/562778/Archief.3.zip)

**Comment by syscl** [comment]
@theupriser 
Thanks for your config.plist, now I know why hda refused to load.

It seems that my script has something wrong to add the HDA patch for you, so I will try to fix it tonight, don't worry.

syscl

**Comment by syscl** [comment]
@theupriser BTW, do you have sound now?

**Comment by theupriser** [comment]
No still no sound.

Edit: So magically I managed to get sound.. don't know why..
Edit2: Display driver is glitching now.
Edit3: seems like touching /Library/Exensions did it's job
Edit4: Booted to no cache mode, executed touch /System/Library/Extensions && kextcache -u /

Everything seems to be working now.
