### ISSUE TITLE
dw1708能不能驱动？

### ISSUE THREAD

**Issue by lncken** [syscl/M3800#51]

**Comment by lncken** [comment]
设备安装成功，系统没有问题了，但是由于我的网卡是intel的，目前无法驱动，想问问，dw1707的驱动是否打包在这个安装中，其次就是我的imessage，facetime，app store登录时提示登录时发生意外错误，希望能尽快得到您的回复，谢谢。

**Comment by lncken** [comment]
您好，我更换了dw1830的无线网卡，目前驱动正常，apple id也能正常使用，但是蓝牙貌似并未正常工作,请问如何处理。等待您的回复。

**Comment by syscl** [comment]
切换到Windows下面尝试蓝牙是否打开.

syscl

**Comment by lncken** [comment]
在windows下蓝牙是打开的，工作正常。
在mac下的信息：
 Apple 蓝牙软件版本：	5.0.1f7
  硬件、功能和设置：
  名称：	xxxxxxx
  地址：	
  支持低功耗蓝牙：	是
  支持 Handoff：	是
  支持 Instant Hotspot：	是
  制造商：	Broadcom
  传输：	USB
  芯片组：	20703A1
  固件版本：	v5 c4518
  蓝牙电源：	打开
  可被发现：	打开
  可连接：	是
  自动寻找点：	打开
  远程唤醒：	打开
  供应商 ID：	0x0A5C
  产品 ID：	0x6410
  HCI 版本：	4.1 (0x7)
  HCI 修正版：	0x11A6
  LMP 版本：	4.1 (0x7)
  LMP 子版本：	0x2105
  设备类型（主要）：	Computer
  设备类型（完整）：	Mac Portable
  复合类设备：	0x38010C
  设备类（主要）：	0x01
  设备类（次要）：	0x03
  服务类：	0x1C0
  自动寻找键盘：	打开
地址出于隐私，没有写，见谅。看上去是没问题的，是不是和类型usb有关系呢？现在搜索不到设备，也没法被搜索，handoff和airdrop都不正常。

**Comment by syscl** [comment]
搜不到蓝牙设备并不是这个蓝牙的问题 而是本身macOS的问题，这个即便是白苹果上面也不靠谱。。

**Comment by lncken** [comment]
好的，其次就是显示器的接口貌似没有驱动，外接的显示器hdmi和mini dp都不显示，SD卡槽没有驱动，不能读卡。是我的问题吗？

**Comment by syscl** [comment]
1. 你没有按照要求提供我所需要的信息 我没有办法帮到你
2. 我不知道你设置了什么
3. 我不知道你是如何按照帖子来进行安装的

HDMI功能没有问题 包括HDMI的声音输出

SD由于是PCIE总线的 目前没有对应的驱动

syscl

**Comment by lncken** [comment]
Intel Iris Pro：

  芯片组型号：	Intel Iris Pro
  类型：	GPU
  总线：	内建
  VRAM（动态，最大值）：	1536 MB
  供应商：	Intel (0x8086)
  设备 ID：	0x0412
  修正版 ID：	0x0006
  金属：	支持
  显示器：
显示器：
  分辨率：	1600 x 900
  像素深度：	32 位彩色 (ARGB8888)
  主显示器：	是
  镜像：	关
  联机：	是
  自动调节亮度：	是
  内建：	是

Intel 高清晰度音频 (HDA)：

  音频 ID：	1

内置麦克风：

  连接：	内部

HDMI/DisplayPort 输出：

  连接：	显示器

没有进行其他设置，安装是直接开机clover按f4然后进系统跑./Deploy.sh的。。。。。同时触屏没有办法用，触摸板倒是没问题。。。
在硬件usb里：
Synaptics Large Touch Screen：

  产品 ID：	0x0ac3
  厂商 ID：	0x06cb  (Synaptics Inc.)
  版本：	0.02
  速度：	最大 12 Mb/秒
  制造商：	SYNAPTICS
  位置 ID：	0x14500000 / 7
  可用电流 (mA)：	500
  所需电流 (mA)：	144
  额外的操作电流 (mA)：	0
  内建：	是

是有触摸屏的

**Comment by syscl** [comment]
1. ioreg 2.1
2. 你用了什么config.plist
3. 系统概述-->文件-->另存为
4. 部分3800机型触摸屏无法使用 以后有时间了会试图找二进制补丁破解

syscl

**Comment by lncken** [comment]
[MacBook Pro.zip](https://github.com/syscl/M3800/files/623529/MacBook.Pro.zip)这个是系统概述，clover整一个是用的你github上的这个。3800的驱动无法使用但是看上去是驱动起来的啊。

**Comment by syscl** [comment]
@lncken 尝试新的配置文件和deploy.sh, 看HDMI是否发声正常.

syscl
