### ISSUE TITLE
Sound not working after wake from sleep

### ISSUE THREAD

**Issue by animator013** [syscl/M3800#53]
I am creating this issue for others. Hope you don't mind. Because i could not find any reference to this issue.

Syscl and I know about this problem:

> About sleep lose ext. sound issue, I am also looking at this, but this issue only happen at very special cases:
> 
> The known one for all laptops(not only dell, but also hp, lenovo...): playing audio then put computer into semi-sleep
> Randomly occurs when wake from sleep, you can plugged-in you hp and unplugged it, then the sound will get fixed.

Hope someone or we can manage to fix that :)

Also I think the sound correct itself when there is hdmi or mDP connected and we disconnect it.

**Comment by animator013** [comment]
Yesterday I was working and listening to spotify with headphones. After ~4hours the headphone port died with some hissing sound... After disconnecting hp sound works from internal speaker. After plugging them in again hissing sound for 2 seconds and nothing else.

There is still something bad with the sound.

From log:
```
10/12/16 02:52:44,000 kernel[0]: Sound assertion in AppleHDAFunctionGroup at line 1060
10/12/16 02:52:44,000 kernel[0]: Sound assertion in AppleHDAFunctionGroup at line 1060
10/12/16 02:52:59,000 kernel[0]: Sound assertion in AppleHDAFunctionGroup at line 1060
10/12/16 02:52:59,000 kernel[0]: Sound assertion in AppleHDAFunctionGroup at line 1060
10/12/16 02:52:59,000 kernel[0]: Sound assertion in AppleHDAFunctionGroup at line 1060
```

**Comment by LynnTong** [comment]
I have the same issue on my xps 9530.

The sound will not working after wake from sleep when you use AC adapter,but it was worked if you use the battery.

when the sound not working(use Ac Adapter)：

1.Plug in earphone
2.Took the earphones out

And then,the sound is working.

**Comment by animator013** [comment]
Further investigation:

I tried to debug with hda-verb. I found out that
```
hda-verb 0x14 GET_CONNECT_SEL 0x0
```

will output
```
nid = 0x14, verb = 0xf01, param = 0x0
command 0x014f0100 --> result = 0x00000001
```

When it's working. But when i wake from sleep and run this command i get this result:
```
nid = 0x14, verb = 0xf01, param = 0x0
command 0x014f0100 --> result = 0x00000000
```

I tried to activate it:
```
hda-verb 0x14 SET_CONNECT_SEL 0x0 1
```

But it always set it to 0, also when I run it while the speakers are working it also sets it to 0... And turn off speakers.

Don't know if this is helpful somehow, but maybe someone can shine some light into this.

**Comment by syscl** [comment]
@animator013 you did a really great job, I tried this to. But failed, keep going, you are on the right way!!

syscl

**Comment by animator013** [comment]
Another discovery. Speakers shut off only on AC adapter. On battery i won't lose them.

I managed to send the hda-verb but still no go. I made a nodedump when it was working and nodedump after speakers shut off. Then i used many verbs to get the same config on non-working scenario. After all verbs and next codec dump without any difference the speakers are still off. I think this will not get fixed by a codec commander.

**Comment by syscl** [comment]
@animator013 You mean CodecCommander.kext? That kext just emulate hda-verb. 

syscl

**Comment by animator013** [comment]
Yup. I used all hda-verbs to fix the diffs between non-working and working scenario. Speakers does not work.

**Comment by syscl** [comment]
From information you provide, I guess that speaker is sent to different power state which cause the scenario that we cannot power it up until replug in the hp. Could you try to remove ```ACPIBatteryManager.kext``` under Clover/kexts to see if this can fix the speaker issue?

Thanks for your detail information,
syscl

**Comment by animator013** [comment]
After removing that kext I lost battery indicator and the speakers are still dead while sleeping on AC adapter.

**Comment by olegfusion** [comment]
Hi animator013,
I looked at your issues, we have same hardware here. May you attach your latest working config.plist and clover folder?
Sorry about writting this in this issue thread, but I will join it soon I think.

**Comment by animator013** [comment]
Hello @olegfusion,

here is my clover folder with config.plist.

[CLOVER.zip](https://github.com/syscl/M3800/files/679959/CLOVER.zip)

**Comment by olegfusion** [comment]
Thank you. Sadly the laptop is gone here, I ended up the experiments
with installing win 10 :(

Yours sincerely,
Oleg Pronin

**Comment by animator013** [comment]
Hi there.

After inserting this into codeccommander plist:
```
<key>Realtek ALC668</key>
				<dict>
					<key>Custom Commands</key>
					<array>
						<dict>
							<key>Command</key>
							<data>
							AVcIgw==
							</data>
							<key>Comment</key>
							<string>0x15 SET_UNSOLICITED_ENABLE 0x83</string>
							<key>On Init</key>
							<true/>
							<key>On Sleep</key>
							<false/>
							<key>On Wake</key>
							<true/>
						</dict>
						<dict>
							<key>Command</key>
							<data>
							AbcHIA==
							</data>
							<key>Comment</key>
							<string>Node 0x1b - Pin Control (In Enable)</string>
							<key>On Init</key>
							<false/>
							<key>On Sleep</key>
							<false/>
							<key>On Wake</key>
							<true/>
						</dict>
					</array>
					<key>Perform Reset</key>
					<false/>
					<key>Perform Reset on EAPD Fail</key>
					<true/>
					<key>Perform Reset on External Wake</key>
					<false/>
				</dict>
```

Sound works after wake from sleep even on AC adapter. Try if that works for you all.

It performs codec reset (resets power state, etc). It works for me.

There is only one last thing with sound and that is headphones plugged in while on cold boot. Then the headphones port is dead. After sleep and wake the headphones are back.

**Comment by syscl** [comment]
@animator013 Nice!! I am really appreciate your hard work.

What's the change from CodecCommander? I will merge your change now:) with your name

Again, really thanks for your solution!
syscl

**Comment by animator013** [comment]
I added these lines:
```
                                        <key>Perform Reset on EAPD Fail</key>
					<true/>
					<key>Perform Reset on External Wake</key>
					<false/>
```

**Comment by syscl** [comment]
@animator013 "Perform Reset on External Wake", is this true on as default?

syscl

**Comment by animator013** [comment]
It's quite funny what I just tried. When i set "Perform Reset on EAPD Fail" to false it also works. If I set Perform Reset on External Wake to true, sound is not working at all. It seems that the issue with no sound is just missing configuration issue :)

So it is likely to work also with these lines:
```
                                        <key>Perform Reset on EAPD Fail</key>
					<false/>
					<key>Perform Reset on External Wake</key>
					<false/>
```

**Comment by animator013** [comment]
Seems like codec reset is not working for this ALC. And codec commander gets confused when there is no configuration ? It is very strange.

**Comment by animator013** [comment]
Now I have to figure out the headphones plugged in after cold boot. That's very odd.

**Comment by syscl** [comment]
@animator013 Weird, missing configuration will cause lose sound after sleep?

Need further confirm.

syscl

**Comment by animator013** [comment]
Removed the two lines from codeccommander and lose sound after sleep on AC.

**Comment by syscl** [comment]
@animator013 so we put these two to 
```
<key>Perform Reset on EAPD Fail</key>
					<false/>
					<key>Perform Reset on External Wake</key>
					<false/>
```
?
syscl

**Comment by animator013** [comment]
Yeah. I have like this now and it works. Very interesting.

Will further test it.

**Comment by syscl** [comment]
@animator013 Maybe turn on Perform Reset EAPD Fail and on External Wake cause loose sound after AC plug in?

syscl

**Comment by syscl** [comment]
@animator013 Very nice work, I tried with these two arguments, no more sleep lose sound issue. Nice.

BTW, I will provide VoodooPS2 for Sierra users later on.

Thank you,
syscl

**Comment by animator013** [comment]
Great to hear that :)

**Comment by syscl** [comment]
@animator013 Please try the latest deploy.sh!

syscl
