### ISSUE TITLE
Unable to Patch BIOS 9350 BIOS 1.4.12

### ISSUE THREAD

**Issue by ccolonval** [syscl/M3800#57]
My current Dell XPS 13 9350 has installed Bios version 1.4.12

I have been following the guide but seem to be stuck on : 

4. Patch bios to unlock bios menu.

I have downloaded the tools needed from the  directory in repo: 

 _unlocked BIOS/AFUWINx64/AFUWINx64.EXE_

Following the steps to flash bios  using this [guide](https://github.com/AustinSMU/PRECISION-M3800-OSX/wiki/Unlocking%20the%20BIOS
)

As soon as I try to do : 

3. Use AFUWin64 by navigating to Aptio\afuwin\64\afuwin.zip, and save your current bios to a ROM file.

I noticed that after entering in command prompt " AFUWINx64/AFUWINx64.EXE /O" the AFUWINGUI.EXE loads [empty](http://oi67.tinypic.com/280jr4l.jpg)

Within this limitation I could only set the following Bios settings :
 - Safe Boot Disabled
 - SATA Operation = AHCI

I manage to get Clover Bootloader and if I run verbose this is my [output](http://oi68.tinypic.com/346nbzm.jpg)

**Comment by syscl** [comment]
OMG, I never said you should patch your XPS 13 9350's bios.

This is for M3800 and XPS 15 9530.

You should read this guide https://github.com/syscl/XPS9350-macOS'

syscl

**Comment by ccolonval** [comment]
Dyslexia is never fun (╯▅╰) , thank you very much for your time and the heads up.

**Comment by syscl** [comment]
Never mind, model name of 9350 and 9530 are really easy to get confused.

syscl
