### ISSUE TITLE
运行脚本时，提示DSDT and SSDTs不存在，在clover下dump AHCI

### ISSUE THREAD

**Issue by Raymondee** [syscl/M3800#58]
请问脚本运行是不是在把clover写入到硬盘EFI分区之后进行? "DUMP AHCI table" 是在开机时clover界面选择启动盘那里摁F4+Fn吗，我试过了，还是会提示相同的warning

**Comment by syscl** [comment]
@Raymondee 将你运行的脚本信息截图发在这里，我看看。

syscl

**Comment by syscl** [comment]
@Raymondee 尝试新的脚本

syscl

**Comment by Raymondee** [comment]
遇到了新的问题，麻烦帮我你看一下。
![2017-01-24](https://cloud.githubusercontent.com/assets/25298932/22230697/026581e6-e21a-11e6-8ffd-565b7ff4729c.png)

**Comment by syscl** [comment]
@Raymondee 尝试最新的

syscl

**Comment by Raymondee** [comment]
运行最新脚本，还是和上面图片一样的

**Comment by syscl** [comment]
给我几分钟 我回家帮你看看...

不过老实说其实这个问题不在脚本上 而是你EFI分区的名字问题...


syscl

**Comment by Raymondee** [comment]
好的。我用clover configuration “mount EFI partition”，在finder里面，看到的EFI分区貌似叫Untitled 1, 里面有一个EFI文件夹

**Comment by Raymondee** [comment]
我把untitled 1改名EFI了，全都是ok，目前是停在update kexts from ./kexts.    这里要等待很久吗

**Comment by Raymondee** [comment]
![2017-01-24 2 45 04](https://cloud.githubusercontent.com/assets/25298932/22232156/b7dcd594-e222-11e6-8936-4ce9c132d0bf.png)

**Comment by syscl** [comment]
我知道什么问题

**Comment by syscl** [comment]
刚到家，准备更新

**Comment by syscl** [comment]
@Raymondee 尝试新的脚本吧

syscl

**Comment by Raymondee** [comment]
好的，稍等一下，处理点事情 发自网易邮箱大师 在2017年01月24日 11:12，Zhou Yating 写道： @Raymondee 尝试新的脚本吧 syscl — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Raymondee** [comment]
解决了！现在开机时，会先显示一个小苹果logo，读一点进度条后，闪成8个苹果花屏，然后恢复正常，显示大苹果logo，进度条读完进系统正常。请问这个正常吗？

**Comment by syscl** [comment]
@Raymondee 你可以自己增加花屏补丁。但是，我不喜欢花屏补丁，因为觉得没什么必要。特别是在有固态硬盘的10.12下，几乎一闪而过。

syscl
