### ISSUE TITLE
Failed Compiling DSDT

### ISSUE THREAD

**Issue by devnet-uk** [syscl/M3800#59]
Hi, I am getting the following error: anyone got any suggestions on working around this. Thanks

[  OK  ]  Mount disk0s1.
[  OK  ]  Copy untouch ACPI tables.
[ ---> ]  Disassembling tables...
[  OK  ]  Disassemble tables.
[  OK  ]  Search specification tables by syscl/Yating Zhou.
[ ---> ]  Patching DSDT.dsl
[  OK  ]  Fix PARSEOP_ZERO.
[  OK  ]  Fix ADBG Error.
[  OK  ]  Rename GFX0 to IGPU.
[  OK  ]  7-series/8-series USB.
[  OK  ]  Fix USB _PRW.
[  OK  ]  Acer Aspire E1-571.
[  OK  ]  IRQ Fix.
[  OK  ]  SMBus Fix.
[  OK  ]  AC Adapter Fix.
[  OK  ]  Add MCHC.
[  OK  ]  Fix _WAK Arg0 v2.
[  OK  ]  Add IMEI.
[  OK  ]  Fix Non-zero Mutex.
[  OK  ]  OS Check Fix.
[  OK  ]  Inject Audio Info.
[  OK  ]  Rename B0D3 to HDAU.
[  OK  ]  Remove GLAN device.
[  OK  ]  iGPU TPMX to MEM2.
[  OK  ]  IMTR->TIMR, _T_x->T_x.
[  OK  ]  Insert SLPB.
[  OK  ]  Insert PMCR.
[  OK  ]  Insert PPMC.
[ ---> ]  Patching SSDT-10.dsl
[  OK  ]  _BST package size.
[  OK  ]  Rename GFX0 to IGPU.
[ ---> ]  Patching SSDT-12.dsl
[  OK  ]  Rename GFX0 to IGPU.
[  OK  ]  Rename HD4600 to Iris Pro.
[  OK  ]  Brightness fix (Haswell).
[  OK  ]  Rename B0D3 to HDAU.
[  OK  ]  Insert HDAU device (c) syscl.
[ ---> ]  Patching SSDT-13.dsl
[  OK  ]  Rename GFX0 to IGPU.
[ ---> ]  Patching SSDT-14.dsl
[  OK  ]  Remove invalid operands.
[  OK  ]  Rename GFX0 to IGPU.
[  OK  ]  Disable Nvidia card (Non-operational in OS X).
[ ---> ]  Copying tables to precompile...
[  OK  ]  Copy tables to precompile.
[ ---> ]  Copying untouched tables to ./DSDT/compile...
[  OK  ]  Copy untouched tables to ./DSDT/compile.
[ ---> ]  Compiling tables...
[FAILED]  Compiling DSDT.
/Users/bun/Documents/M3800/DSDT/precompile/DSDT.dsl   6907:             Method (PR2S, 1, Serialized)
Warning  3115 -                              Not all control paths return a value ^  (PR2S)

/Users/bun/Documents/M3800/DSDT/precompile/DSDT.dsl   7028:             Method (_PS0, 0, Serialized)  // _PS0: Power State 0
Warning  3115 -                              Not all control paths return a value ^  (_PS0)

/Users/bun/Documents/M3800/DSDT/precompile/DSDT.dsl   7038:                 Store (D0D3, Local3)
Warning  3144 -                                           Method Local is set but never used ^  (Local3)

/Users/bun/Documents/M3800/DSDT/precompile/DSDT.dsl   7152:             Method (_PS3, 0, Serialized)  // _PS3: Power State 3
Warning  3115 -                              Not all control paths return a value ^  (_PS3)

/Users/bun/Documents/M3800/DSDT/precompile/DSDT.dsl   7327:                         If (LNot (And (PR2S (One), PR2)))
Warning  3122 -                                          Called method may not always return a value ^ 

/Users/bun/Documents/M3800/DSDT/precompile/DSDT.dsl   7346:                         If (LNot (And (PR2S (One), PR2)))
Warning  3122 -                                          Called method may not always return a value ^ 

/Users/bun/Documents/M3800/DSDT/precompile/DSDT.dsl   7368:                         If (LNot (And (PR2S (0x02), PR2)))
Warning  3122 -                                          Called method may not always return a value ^ 

/Users/bun/Documents/M3800/DSDT/precompile/DSDT.dsl   7387:                         If (LNot (And (PR2S (0x02), PR2)))
Warning  3122 -                                          Called method may not always return a value ^ 

/Users/bun/Documents/M3800/DSDT/precompile/DSDT.dsl   7409:                         If (LNot (And (PR2S (0x03), PR2)))
Warning  3122 -                                          Called method may not always return a value ^ 

/Users/bun/Documents/M3800/DSDT/precompile/DSDT.dsl   7428:                         If (LNot (And (PR2S (0x03), PR2)))
Warning  3122 -                                          Called method may not always return a value ^ 

/Users/bun/Documents/M3800/DSDT/precompile/DSDT.dsl   7455:                         If (LNot (And (PR2S (0x04), PR2)))
Warning  3122 -                                          Called method may not always return a value ^ 

/Users/bun/Documents/M3800/DSDT/precompile/DSDT.dsl   7474:                         If (LNot (And (PR2S (0x04), PR2)))
Warning  3122 -                                          Called method may not always return a value ^ 

/Users/bun/Documents/M3800/DSDT/precompile/DSDT.dsl   7496:                         If (LNot (And (PR2S (0x05), PR2)))
Warning  3122 -                                          Called method may not always return a value ^ 

/Users/bun/Documents/M3800/DSDT/precompile/DSDT.dsl   7515:                         If (LNot (And (PR2S (0x05), PR2)))
Warning  3122 -                                          Called method may not always return a value ^ 

/Users/bun/Documents/M3800/DSDT/precompile/DSDT.dsl   7537:                         If (LNot (And (PR2S (0x06), PR2)))
Warning  3122 -                                          Called method may not always return a value ^ 

/Users/bun/Documents/M3800/DSDT/precompile/DSDT.dsl   7556:                         If (LNot (And (PR2S (0x06), PR2)))
Warning  3122 -                                          Called method may not always return a value ^ 

/Users/bun/Documents/M3800/DSDT/precompile/DSDT.dsl   7578:                         If (LNot (And (PR2S (0x07), PR2)))
Warning  3122 -                                          Called method may not always return a value ^ 

/Users/bun/Documents/M3800/DSDT/precompile/DSDT.dsl   7597:                         If (LNot (And (PR2S (0x07), PR2)))
Warning  3122 -                                          Called method may not always return a value ^ 

/Users/bun/Documents/M3800/DSDT/precompile/DSDT.dsl   7619:                         If (LNot (And (PR2S (0x08), PR2)))
Warning  3122 -                                          Called method may not always return a value ^ 

/Users/bun/Documents/M3800/DSDT/precompile/DSDT.dsl   7638:                         If (LNot (And (PR2S (0x08), PR2)))
Warning  3122 -                                          Called method may not always return a value ^ 

/Users/bun/Documents/M3800/DSDT/precompile/DSDT.dsl   7660:                         If (LNot (And (PR2S (0x09), PR2)))
Warning  3122 -                                          Called method may not always return a value ^ 

/Users/bun/Documents/M3800/DSDT/precompile/DSDT.dsl   7679:                         If (LNot (And (PR2S (0x09), PR2)))
Warning  3122 -                                          Called method may not always return a value ^ 

/Users/bun/Documents/M3800/DSDT/precompile/DSDT.dsl   7728:                         If (LNot (And (PR2S (0x0A), PR2)))
Warning  3122 -                                          Called method may not always return a value ^ 

/Users/bun/Documents/M3800/DSDT/precompile/DSDT.dsl   7747:                         If (LNot (And (PR2S (0x0A), PR2)))
Warning  3122 -                                          Called method may not always return a value ^ 

/Users/bun/Documents/M3800/DSDT/precompile/DSDT.dsl   7769:                         If (LNot (And (PR2S (0x0B), PR2)))
Warning  3122 -                                          Called method may not always return a value ^ 

/Users/bun/Documents/M3800/DSDT/precompile/DSDT.dsl   7788:                         If (LNot (And (PR2S (0x0B), PR2)))
Warning  3122 -                                          Called method may not always return a value ^ 

/Users/bun/Documents/M3800/DSDT/precompile/DSDT.dsl   7808:                             If (LNot (And (PR2S (0x0B), PR2)))
Warning  3122 -                                              Called method may not always return a value ^ 

/Users/bun/Documents/M3800/DSDT/precompile/DSDT.dsl   7828:                             If (LNot (And (PR2S (0x0B), PR2)))
Warning  3122 -                                              Called method may not always return a value ^ 

/Users/bun/Documents/M3800/DSDT/precompile/DSDT.dsl   7873:                         If (LNot (And (PR2S (0x0C), PR2)))
Warning  3122 -                                          Called method may not always return a value ^ 

/Users/bun/Documents/M3800/DSDT/precompile/DSDT.dsl   7892:                         If (LNot (And (PR2S (0x0C), PR2)))
Warning  3122 -                                          Called method may not always return a value ^ 

/Users/bun/Documents/M3800/DSDT/precompile/DSDT.dsl   7936:                         If (LNot (And (PR2S (0x0D), PR2)))
Warning  3122 -                                          Called method may not always return a value ^ 

/Users/bun/Documents/M3800/DSDT/precompile/DSDT.dsl   7955:                         If (LNot (And (PR2S (0x0D), PR2)))
Warning  3122 -                                          Called method may not always return a value ^ 

/Users/bun/Documents/M3800/DSDT/precompile/DSDT.dsl   7988:                         If (LNot (And (PR2S (0x0E), PR2)))
Warning  3122 -                                          Called method may not always return a value ^ 

/Users/bun/Documents/M3800/DSDT/precompile/DSDT.dsl   8007:                         If (LNot (And (PR2S (0x0E), PR2)))
Warning  3122 -                                          Called method may not always return a value ^ 

/Users/bun/Documents/M3800/DSDT/precompile/DSDT.dsl   8040:                         If (LNot (And (PR2S (0x0F), PR2)))
Warning  3122 -                                          Called method may not always return a value ^ 

/Users/bun/Documents/M3800/DSDT/precompile/DSDT.dsl   8059:                         If (LNot (And (PR2S (0x0F), PR2)))
Warning  3122 -                                          Called method may not always return a value ^ 

/Users/bun/Documents/M3800/DSDT/precompile/DSDT.dsl  10320:     Method (SPL1, 0, Serialized)
Warning  3115 -                      Not all control paths return a value ^  (SPL1)

/Users/bun/Documents/M3800/DSDT/precompile/DSDT.dsl  10466:             If (CondRefOf (\_OSI, Local0))
Warning  3144 -                                                Method Local is set but never used ^  (Local0)

/Users/bun/Documents/M3800/DSDT/precompile/DSDT.dsl  12827:                 Return (BUF2)
Warning  3104 -                             Reserved method should not return a value ^  (_SRS)

/Users/bun/Documents/M3800/DSDT/precompile/DSDT.dsl  12951:                     Store (LLOW, LLOW)
Warning  3023 -                                                        Duplicate value in list ^  (Source is the same as Target)

/Users/bun/Documents/M3800/DSDT/precompile/DSDT.dsl  12952:                     Store (LHIH, LHIH)
Warning  3023 -                                                        Duplicate value in list ^  (Source is the same as Target)

/Users/bun/Documents/M3800/DSDT/precompile/DSDT.dsl  13288:                 Store (Arg0, ERIB)
Error    6084 -                                                      Object does not exist ^  (ERIB)

/Users/bun/Documents/M3800/DSDT/precompile/DSDT.dsl  13297:                 Store (Arg0, ERIB)
Error    6084 -                                                      Object does not exist ^  (ERIB)

/Users/bun/Documents/M3800/DSDT/precompile/DSDT.dsl  13419:                         WECB(0x64,256,Zero)
Error    6084 -                                                 Object does not exist ^  (WECB)

/Users/bun/Documents/M3800/DSDT/precompile/DSDT.dsl  13438:                                 Store (RECB(0x64,256), Local3)
Error    6084 -                                                                Object does not exist ^  (RECB)

Intel ACPI Component Architecture
ASL+ Optimizing Compiler version 20160422-64(RM)
Copyright (c) 2000 - 2016 Intel Corporation

ASL Input:     /Users/bun/Documents/M3800/DSDT/precompile/DSDT.dsl - 14431 lines, 476971 bytes, 6048 keywords

Compilation complete. 4 Errors, 41 Warnings, 35 Remarks, 132 Optimizations
[FAILED]  Compile DptfTa.
/Users/bun/Documents/M3800/DSDT/precompile/SSDT-10.dsl    947:                 Divide (RMDR, PPUU, Local0, RMDR)
Warning  3144 -                                                     Method Local is set but never used ^  (Local0)

/Users/bun/Documents/M3800/DSDT/precompile/SSDT-10.dsl   1985:         Method (STDP, 1, Serialized)
Warning  3115 -                             Not all control paths return a value ^  (STDP)

/Users/bun/Documents/M3800/DSDT/precompile/SSDT-10.dsl   3991:                 Return (Package (0x01)
Error    6106 -                                          Invalid package length for reserved name ^  (_BST: length 1, required minimum is 4)

/Users/bun/Documents/M3800/DSDT/precompile/SSDT-10.dsl   4366:         Method (_ART, 0, NotSerialized)  // _ART: Active Cooling Relationship Table
Warning  3115 -                             Not all control paths return a value ^  (_ART)

/Users/bun/Documents/M3800/DSDT/precompile/SSDT-10.dsl   4366:         Method (_ART, 0, NotSerialized)  // _ART: Active Cooling Relationship Table
Warning  3107 -                              Reserved method must return a value ^  (Package required for _ART)

Intel ACPI Component Architecture
ASL+ Optimizing Compiler version 20160422-64(RM)
Copyright (c) 2000 - 2016 Intel Corporation

ASL Input:     /Users/bun/Documents/M3800/DSDT/precompile/SSDT-10.dsl - 4404 lines, 129388 bytes, 2155 keywords

Compilation complete. 1 Errors, 4 Warnings, 9 Remarks, 13 Optimizations
[  OK  ]  Compile SaSsdt.
[  OK  ]  Compile SgRef.
[  OK  ]  Compile OptRef.
[ ---> ]  Copying SSDT-rmne.aml to ./DSDT/compile...
[  OK  ]  Copy SSDT-rmne.aml to ./DSDT/compile.
[  OK  ]  Generate C-States and P-State for Intel i7-4702HQ.
[ ---> ]  Installing SSDT-m-M3800.aml to ./DSDT/compile...
[  OK  ]  Copy SSDT-m-M3800.aml to ./DSDT/compile.
[  OK  ]  Clean dynamic SSDTs.
[  OK  ]  Create /Volumes/EFI/EFI/CLOVER/ACPI/patched.
[  OK  ]  Copy tables to /Volumes/EFI/EFI/CLOVER/ACPI/patched.
[ ---> ]  Updating kexts...
[  OK  ]  Remove pervious kexts in /Volumes/EFI/EFI/CLOVER/kexts/10.12.
[  OK  ]  Update kexts from ./CLOVER/kexts/10.12.
[  OK  ]  Update kexts from ./Kexts.
[  OK  ]  BCM2045A0 found.
[  OK  ]  Remove redundant BT driver::BrcmPatchRAM.kext.
[ ---> ]  Installing audio...
[  OK  ]  Install audio.
[ Note ]  Set System Agent (SA) Configuration—>Graphics Configuration->DVMT Pre-Allocated->『160MB』.
[ ---> ]  Unlocking maximum pixel clock...
[  OK  ]  Patch and sign framework.
[ ---> ]  Leading to lid wake on 0x0a2e0008 (c) syscl/lighting/Yating Zhou...
[  OK  ]  Lead to lid wake on 0x0a2e0008.
[  OK  ]  Generate configuration file of sleepwatcher launch daemon.
[  OK  ]  Generating script to unmount external devices before sleep (c) syscl/lighting/Yating Zhou.
[  OK  ]  Generate script to load RTWlanUSB upon sleep.
[ ---> ]  Installing external devices sleep patch...
[  OK  ]  Install sleepwatcher daemon.
[  OK  ]  Install configuration of sleepwatcher daemon.
[  OK  ]  Install sleep script.
[  OK  ]  Install wake script.
[  OK  ]  Fix the permissions of /etc/sysclusbfix.sleep.
[  OK  ]  Fix the permissions of /etc/sysclusbfix.wake.
[  OK  ]  Trigger startup service of syscl.usb.fix.
[  OK  ]  Clean up.
[  OK  ]  Mount disk0s3.
[  OK  ]  Create /Users/bun/Documents/M3800/Backups/2017-02-12-h17_08_05.
[ ---> ]  Convert UDZO(r/o) to UDRW(r/w) ...
[  OK  ]  Convert UDZO(r/o) to UDRW(r/w).
[  OK  ]  Attach Recovery HD.
[  OK  ]  Patch and sign framework for Recovery HD.
[  OK  ]  Detach mountpoint.
[ ---> ]  Convert UDRW(r/w) to UDZO(r/o) ...
[  OK  ]  Convert UDRW(r/w) to UDZO(r/o).
[ ---> ]  Updating Recovery HD for DELL M3800/XPS9530...
cp: /Volumes/Recovery HD/com.apple.recovery.boot/BaseSystem.dmg: No such file or directory
chflags: /Volumes/Recovery HD/com.apple.recovery.boot/BaseSystem.dmg: No such file or directory
[  OK  ]  Clean redundant dmg files.
[FAILED]  Unmount disk0s3.
disk0s3 was already unmounted
[ ---> ]  Rebuilding kernel extensions cache...
[  OK  ]  Rebuild kernel extensions cache.
[ Note ]  Congratulations! All operation has been completed.
[ Note ]  Reboot now. Then enjoy your OS X! -syscl/lighting/Yating Zhou @PCBeta.

**Comment by syscl** [comment]
Hi @m8mbl Could you please paste all your origin ACPI tables and patched tables separately here?

I will analysis it.

Thank you,
syscl

**Comment by devnet-uk** [comment]
hi @syscl,

[ACPI.zip](https://github.com/syscl/M3800/files/769582/ACPI.zip)

please find attached as requested. 

thanks

**Comment by syscl** [comment]
Hi @m8mbl 

I will try to see your ACPI later due to I have midterm exams and dues this month. 

Sorry for my late reply,
syscl

**Comment by devnet-uk** [comment]
Hi @syscl, any luck with this? Appreciate you are busy with exams etc... any pointers on self help would be good.

Thanks
Bun

**Comment by syscl** [comment]
Hi @m8mbl 

I tried to use deploy to patch your ACPI, no any issue at all. Here's the output(I copied your ACPI to my Clover then execute deploy), here's the result

```sh
syscls-MacBook-Pro:~ syscl$ cd github/M3800/
syscls-MacBook-Pro:M3800 syscl$ ./deploy.sh -rlse
[ ---> ]  Updating files from https://github.com/syscl/M3800...
Already up-to-date.
[  OK  ]  Create ./DSDT.
[  OK  ]  Create ./DSDT/prepare.
[  OK  ]  Create ./DSDT/precompile.
[  OK  ]  Create ./DSDT/compile.
/dev/disk0 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *256.1 GB   disk0
   1:                        EFI EFI                     209.7 MB   disk0s1
   2:         Microsoft Reserved                         134.2 MB   disk0s2
   3:       Microsoft Basic Data                         161.1 GB   disk0s3
   4:                  Apple_HFS macOS                   94.5 GB    disk0s4
/dev/disk1 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *960.2 GB   disk1
   1:                        EFI EFI                     209.7 MB   disk1s1
   2:                  Apple_HFS Macintosh HD            840.5 GB   disk1s2
   3:                 Apple_Boot Recovery HD             650.0 MB   disk1s3
   4:                 Linux Swap                         8.2 GB     disk1s4
   5:           Linux Filesystem                         110.5 GB   disk1s5
Enter EFI's IDENTIFIER, e.g. disk0s1: disk1s1
[  OK  ]  Mount disk1s1.
[  OK  ]  Copy untouch ACPI tables.
Available touchpad kext:
[   1  ] ApplePS2SmartTouchPad
[   2  ] VoodooPS2Controller
Please choose the desired touchpad kext (1 or 2): 2
[ Note ]  Use VoodooPS2Controller.
[ ---> ]  Disassembling tables...
[  OK  ]  Disassemble tables.
[  OK  ]  Search specification tables by syscl/Yating Zhou.
[ ---> ]  Patching DSDT.dsl
[  OK  ]  Fix PARSEOP_ZERO.
[  OK  ]  Fix ADBG Error.
[  OK  ]  Rename GFX0 to IGPU.
[  OK  ]  7-series/8-series USB.
[  OK  ]  Fix USB _PRW.
[  OK  ]  Acer Aspire E1-571.
[  OK  ]  IRQ Fix.
[  OK  ]  SMBus Fix.
[  OK  ]  AC Adapter Fix.
[  OK  ]  Add MCHC.
[  OK  ]  Fix _WAK Arg0 v2.
[  OK  ]  Add IMEI.
[  OK  ]  Fix Non-zero Mutex.
[  OK  ]  OS Check Fix.
[  OK  ]  Inject Audio Info.
[  OK  ]  Rename B0D3 to HDAU.
[  OK  ]  Remove GLAN device.
[  OK  ]  iGPU TPMX to MEM2.
[  OK  ]  IMTR->TIMR, _T_x->T_x.
[  OK  ]  Insert SLPB.
[  OK  ]  Insert PMCR.
[  OK  ]  Insert PPMC.
[  OK  ]  Added deep sleep and deep idle properties.
[ ---> ]  Patching SSDT-10.dsl
[  OK  ]  _BST package size.
[  OK  ]  Rename GFX0 to IGPU.
[ ---> ]  Patching SSDT-12.dsl
[  OK  ]  Rename GFX0 to IGPU.
[  OK  ]  Rename HD4600 to Iris Pro.
[  OK  ]  Brightness fix (Haswell).
[  OK  ]  Rename B0D3 to HDAU.
[  OK  ]  Insert HDAU device (c) syscl.
[ ---> ]  Patching SSDT-13.dsl
[  OK  ]  Rename GFX0 to IGPU.
[ ---> ]  Patching SSDT-14.dsl
[  OK  ]  Remove invalid operands.
[  OK  ]  Rename GFX0 to IGPU.
[  OK  ]  Disable Nvidia card (Non-operational in OS X).
[ ---> ]  Copying tables to precompile...
[  OK  ]  Copy tables to precompile.
[ ---> ]  Copying untouched tables to ./DSDT/compile...
[  OK  ]  Copy untouched tables to ./DSDT/compile.
[ ---> ]  Compiling tables...
[  OK  ]  Compiling DSDT.
[  OK  ]  Compile DptfTa.
[  OK  ]  Compile SaSsdt.
[  OK  ]  Compile SgRef.
[  OK  ]  Compile OptRef.
[ ---> ]  Copying SSDT-rmne.aml to ./DSDT/compile...
[  OK  ]  Copy SSDT-rmne.aml to ./DSDT/compile.
[  OK  ]  Generate C-States and P-State for Intel i7-4712HQ.
[ ---> ]  Installing SSDT-m-M3800.aml to ./DSDT/compile...
[  OK  ]  Copy SSDT-m-M3800.aml to ./DSDT/compile.
[  OK  ]  Clean dynamic SSDTs.
[  OK  ]  Create /Volumes/EFI/EFI/CLOVER/ACPI/patched.
[  OK  ]  Copy tables to /Volumes/EFI/EFI/CLOVER/ACPI/patched.
[ ---> ]  Updating kexts...
[  OK  ]  Remove pervious kexts in /Volumes/EFI/EFI/CLOVER/kexts/10.11.
[  OK  ]  Update kexts from ./CLOVER/kexts/10.11.
[  OK  ]  Update kexts from ./Kexts.
[  OK  ]  Install VoodooPS2Controller.
[  OK  ]  BCM2045A0 found.
[  OK  ]  Remove redundant BT driver::BrcmPatchRAM.kext.
[ ---> ]  Installing audio...
[  OK  ]  Install audio.
[ Note ]  Set System Agent (SA) Configuration—>Graphics Configuration->DVMT Pre-Allocated->『160MB』.
[ ---> ]  Unlocking maximum pixel clock...
Password:
[  OK  ]  Patch and sign framework.
[ ---> ]  Leading to lid wake on 0x0a2e0008 (c) syscl/lighting/Yating Zhou...
[  OK  ]  Lead to lid wake on 0x0a2e0008.
[  OK  ]  Generate configuration file of sleepwatcher launch daemon.
[  OK  ]  Generating script to unmount external devices before sleep (c) syscl/lighting/Yating Zhou.
[  OK  ]  Generate script to load RTWlanUSB upon sleep.
[ ---> ]  Installing external devices sleep patch...
[  OK  ]  Install sleepwatcher daemon.
[  OK  ]  Install configuration of sleepwatcher daemon.
[  OK  ]  Install sleep script.
[  OK  ]  Install wake script.
[  OK  ]  Fix the permissions of /etc/sysclusbfix.sleep.
[  OK  ]  Fix the permissions of /etc/sysclusbfix.wake.
[  OK  ]  Trigger startup service of syscl.usb.fix.
[  OK  ]  Clean up.
[  OK  ]  Mount disk1s3.
[  OK  ]  Create /tmp/RecoveryHD.
[  OK  ]  Create /Users/syscl/github/M3800/Backups/2017-03-04-h13_14_28.
[ ---> ]  Convert UDZO(r/o) to UDRW(r/w) ...
[  OK  ]  Convert UDZO(r/o) to UDRW(r/w).
[  OK  ]  Attach Recovery HD.
[  OK  ]  Patch and sign framework for Recovery HD.
[  OK  ]  Detach mountpoint.
[ ---> ]  Convert UDRW(r/w) to UDZO(r/o) ...
[  OK  ]  Convert UDRW(r/w) to UDZO(r/o).
[ ---> ]  Updating Recovery HD for DELL M3800/XPS9530...
[  OK  ]  Clean redundant dmg files.
[  OK  ]  Unmount disk1s3.
[ ---> ]  Rebuilding kernel extensions cache...
[  OK  ]  Rebuild kernel extensions cache.
[ Note ]  Congratulations! All operation has been completed.
[ Note ]  Reboot now. Then enjoy your OS X! -syscl/lighting/Yating Zhou @PCBeta.
```

Here's the patched ACPI table

[patched.zip](https://github.com/syscl/M3800/files/818870/patched.zip)

Double check if you do something wrong. 

Good luck,
syscl

**Comment by devnet-uk** [comment]
hey @syscl, yes I resolved this a week ago. Basically cleared the original ACPI directory and just F4'ed it again.. and then re-ran and it worked. 

Thanks
Bun
