### ISSUE TITLE
Small bug in Deploy.sh

### ISSUE THREAD

**Issue by ghost** [syscl/M3800#6]
There is a bug that made be install it many times before understand.

In Deploy.sh you make a test (important) for graphic driver (if resolution == 1920*1080)

But me, I have a QHD screen, the new one and i had my screen set to 1920 1080 HI-DPI while I run the screen (in native resolution it's too small). Then your script "think" my Dell have a basic 1920*1080p panel. And nothing work after reboot. Bad graphic driver. I think a lot of people who try will fall in this.

But as I said in other issue, you made impressive job.

Thanks

**Comment by syscl** [comment]
Thank you for your important suggestion , I will look in your spec separately and add more improvement for your model.

Do you finish the installation?( I mean install the system to target partition?)

Once you finish installation, you have to 
1. Set inject/Intel =false
2.dump acpi tables by F4 under Clover
3.run my script to patch the iokit and ig-platform at the first time. 
4. Run the script again to fix the lid wake problem.

I will repair some bugs tomorrow ASAP! Since  I go to Panyu without taking my laptop.

**Comment by ghost** [comment]
I am still using external drive for EFI for the moment.

If I understand, the 4 steps you describe me are included in your ./Deploy.sh

I have done 1 time (after setting my resolution to native QHD resolution to make script not beleive i am in simple full hd). Then, script tell me to reboot, i dump F4, i use ./Deploy.sh again.

At this time I think that i am ok :+1: 
- HiDpi at full speed
- Trackpad gesture ok

I have some doubts about the sleep mode. I think that my USB to LAN adapter (LAN7500) prevent my computer to go to Sleep. I must investigate. When it is plugged, it don't go sleep. When i unplug it before boot, it go to sleep and wake up ok.

Thanks again

**Comment by syscl** [comment]
The external USB Wi-Fi is a known issue which can prevent OS X going into sleep even on platforms other than M3800. 

I am planning to add functions for 4K display, hence I believe your ioreg and other information about your M3800 will be valuable for us reaching this target. (Plan to use EDID as my new project Enable-HiDPI-OS X to gain more precise/correct display information)

Second point, maybe you don't have to use external monitor to finish the installation, just set inject Intel = false at the clover menu, and system will let you in(sorry I don't have a 4K display, so I still wait for your confirm)

:)

**Comment by syscl** [comment]
I have updated the deploy.sh with support of the 4K display model, wait for your feedback.

Good luck!

**Comment by ghost** [comment]
Detection seem to be better with that script. No more confustion fullhd < > qhd.
Thanks !
