### ISSUE TITLE
 config貌似有问题

### ISSUE THREAD

**Issue by imxly** [syscl/M3800#60]
我的xps9530不能驱动显卡。查了原因是inject下的intel是flase。然后我改成true后进不了系统。
现在换其他的cofig驱动显卡了。

**Comment by syscl** [comment]
几个问题：
- 什么配置
- 什么系统
- 做了什么设置，有没有对我的Clover进行其它改动
- 附上你的Verbose 图

syscl

**Comment by imxly** [comment]
- 配置：4702HQ，分辨率3200x1600，网卡是原装的7260没驱动，其他跟9530都一样吧？
-系统是10.12.3
-clvoer只换了config
-表示不知道什么是Verbose 图
-其实我的问题是为什么你的config显卡那块的inject下intel是false，因为看我其他人驱动显卡这里都是true
-现在我改了config，驱动都正常。就是有一点，插耳机没声音。可能是我自己造成
-最后还是感谢你的这个m3800项目

**Comment by syscl** [comment]
- verbose模式启动截图
- Clover用我的没有问题
- 设置Intel False是因为IOKit/CoreDisplay对3200x1800分辨率有限制，需要先不驱动显卡的进入系统，然后执行deploy.sh，deploy会自动破解IOKit/CoreDisplay然后自动修改config.plist中的Inject Intel ＝ True
- 从你提供的信息和描述来看，你并没有仔细阅读教程按照我的操作来运行deploy.sh, 这是你无法正确驱动的原因。

这个项目已经有一年多的时间，被证明有效，并且被成功的迁移到Asus FX50(J/K), XPS 13 9350/9360等项目上去。请仔细检查自己的所有操作。

syscl

**Comment by imxly** [comment]
最近按照教程重新操作，显卡已正常驱动。不过出现了两个新问题
1、耳机插上声音很小，音量最大，但是能听到的声音很小很小
2、hdmi外接显示器不没画面

**Comment by syscl** [comment]
你好请使用最新的deploy。问题已经修复。
