### ISSUE TITLE
大神你好，xps15 9530安装10.12.1用了这边最新的文件和脚本，BCM94352Z无线网卡和蓝牙没有成功驱动

### ISSUE THREAD

**Issue by mingxingshi** [syscl/M3800#61]
大神你好，xps15 9530安装10.12.1用了这边最新的文件和脚本，BCM94352Z无线网卡和蓝牙没有成功驱动
[dsdt.zip](https://github.com/syscl/M3800/files/853315/dsdt.zip)
，其他貌似没什么问题。大神能不能帮我看看呢

**Comment by syscl** [comment]
你好 94352z在10.12.x下面需要一个叫fcvo的补丁方可 你在我的github里面找找 syscl

**Comment by mingxingshi** [comment]
谢谢大神提供的信息，现在wifi 蓝牙已经驱动正常
applestore可以正常登陆下载……(^^)

**Comment by sukia163** [comment]
兄弟你好，我也是9530，能分享一下安装文件或注意事项吗，谢谢你
