### ISSUE TITLE
HDMI and mDP stopped work

### ISSUE THREAD

**Issue by devnet-uk** [syscl/M3800#62]
Hi, 

My HDMI and mDP have both stopped working since the successful installation. 

I have reinstalled the OS, and it seems to come back for a short period of time before it stop working once I shutdown or reboot the laptop. 

I am getting this error message in the logs when the ports are connected.
 
Mar 20 08:10:06 buns-MBP com.apple.xpc.launchd[1] (com.apple.displaypolicyd[808]): Service exited with abnormal code: 1
Mar 20 08:10:06 buns-MBP com.apple.xpc.launchd[1] (com.apple.displaypolicyd): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.

Is there a fix for this?

Thanks in advance.

Bun

**Comment by johnyoonh** [comment]
Did you get a solution for this?

**Comment by devnet-uk** [comment]
no solution... I have since sold the laptop.
