### ISSUE TITLE
BCM43xx not working

### ISSUE THREAD

**Issue by edfungus** [syscl/M3800#63]
Hi again. 

So the wifi/bluetooth suddenly stopped working one day and currently the system detects the card (mac address and all) but it is "inactive" and I can't turn it on. 

The card works in Windows/Ubuntu on same machine and I did a fresh install again. Any ideas?

**Comment by syscl** [comment]
Hello @edfungus , TL;DR . 

What system you use?

On 10.12 and later you need to use a patch name ```fcvo``` for DW1560 to make it work.

Good luck!

syscl

**Comment by edfungus** [comment]
So I fixed it by taping two pins on the card that would turn off the card via hardware
