### ISSUE TITLE
10.12.3 dw1560 无法驱动

### ISSUE THREAD

**Issue by Yuee98** [syscl/M3800#64]
打了fcvo也无法驱动wifi，蓝牙同样无效
奇怪的是我第一次装的时候可以用，重装之后就无效了，再怎么弄都不行了……
现在还是10.12.1/2比较稳定吗？

**Comment by syscl** [comment]
请pull上你的配置文件夹。

我用的是10.12.4 正式版，直接从App Store升级的，没有任何问题。。

syscl

**Comment by Yuee98** [comment]
[config.zip](https://github.com/syscl/M3800/files/891796/config.zip)
只修改了config.plist，其他都是用的你的clover文件夹

**Comment by syscl** [comment]
你执行了deploy.sh吗

让新的deploy.sh更新一下你的kext

syscl

**Comment by Yuee98** [comment]
没有网络无法执行，我是第一次安装

**Comment by Yuee98** [comment]
我离线执行deploy.sh后网络可用，但出现了新问题
1.在执行deploy.sh时，有一个note让我set DVMT preallocated to 160MB，但我已经设置了；
2.重启后，加载完白苹果，进入登陆界面时，登陆界面只闪一下，然后就黑屏。
我是3840分辨率M3800，未装电池，usb引导clover。

**Comment by syscl** [comment]
你按照要求操作了吗？设置完DVMT之后在Clover按F4了吗。。

syscl

**Comment by Yuee98** [comment]
我在装系统前就已经按照readme里设置好了bios，但执行deploy时仍有note。
刚才我又重新安装了一遍，步骤如下：
clover安装osx——reboot配置系统——reboot在clover里F4——进入系统——执行deploy.sh——reboot黑屏

**Comment by syscl** [comment]
如果我没记错，4K屏不能设置成最高分辨率，需要设置成类似3200x1800这样的分辨率，不然无法驱动。

syscl

**Comment by syscl** [comment]
第一次 需要网络执行，至少你需要安装某些XCode的组件，不然你进不了系统的。

syscl

**Comment by Yuee98** [comment]
ok，我在装一遍试试吧，分辨率设置就是用系统自带的缩放吗？还是使用其他的插件？

**Comment by syscl** [comment]
@Tkuns https://github.com/syscl/Enable-HiDPI-OSX

syscl

**Comment by Yuee98** [comment]
使用RDM设置分辨率为1600x900HiDPI后不出现黑屏了。
但是要注意不能点进 偏好设置-显示器 里，否则重启会再次黑屏。
不过新的问题又出现了：蓝牙看起来正常，但无效（airdrop找不到）；没有声音；触屏无法驱动。

**Comment by syscl** [comment]
再运行一遍deploy.sh

syscl

**Comment by Yuee98** [comment]
再次运行deploy.sh后，蓝牙正常，外放正常；耳机插入有显示但是没有声音，左上角稍花，finder窗口在笔记本与外接屏幕见拖动时会花一下。
其他的还好，耳机问题有什么建议吗，谢谢。

**Comment by Yuee98** [comment]
睡眠一分钟左右后耳机问题解决。
最后只剩黑屏这一个问题了，我感觉不管是插入／拔出dp，还是改变分辨率都有可能导致重启黑屏，时间大多都用在解决黑屏上了，现在一点也不敢动有关显示的设置。。
跟那个note有关系吗？在运行deploy时出现的set DVMT preallocated to 160m这条，我非常确定我已经设置为160m了。

**Comment by syscl** [comment]
能在插入DP的时候提供一下IOREG给我吗？

谢谢！
syscl

**Comment by Yuee98** [comment]
不好意思，假期去同学那的时候帮他装的，现在我已经回学校了，所以………
忘记关闭issue了，希望这个问题是个例，再次谢谢你之前的帮助。
