### ISSUE TITLE
10.12.4 声卡自带的喇叭能驱动,插上耳机就噪音.

### ISSUE THREAD

**Issue by AKA-KC** [syscl/M3800#65]
rt.....

**Comment by AKA-KC** [comment]
<img width="1043" alt="wx20170425-210613 2x" src="https://cloud.githubusercontent.com/assets/4024715/25386771/13425ccc-29fb-11e7-82ef-5898bd2772b0.png">

**Comment by syscl** [comment]
@KCWong1986 尝试最新的deploy.sh，我已经修复了这个问题。

syscl

**Comment by syscl** [comment]
请尝试最新的deploy.sh. 已经修复编译等一系列问题。
