### ISSUE TITLE
MacOS Sierra on Dell Precision M3800

### ISSUE THREAD

**Issue by mindscrambler** [syscl/M3800#66]
I don't understand what goes wrong. I installed macOS Sierra, installed Clover to HDD(EFI), CLOVER directory replaced with the one from repository, ACPI dump with F4 when booting from HDD , run ./Deploy.sh twice with the output listed bellow. Still when rebooting, it's stopping at half the progress bar with apple logo (after an hour, gave up).
Boot is patched, default settings loaded and the ones specified in this repository are modified accordingly. 
Not experienced with Macs. How do I verify what's wrong? The only FAILED entry is for updating OsxFatBinaryDrv-64.efi that I think it is from Clover install (r4049) and it shouldn't cuse this freeze.

[ ---> ]  Updating files from https://github.com/syscl/M3800...

GitHub - syscl/M3800: auto patch OS X for M3800/XPS9530
github.com
README.md OS X on DELL M3800 and XPS15 (9530) This project targets at giving the relatively complete functional OS X for both Dell Precision M3800 and XPS15 9530.

Already up-to-date.
[  OK  ]  Create ./DSDT.
[  OK  ]  Create ./DSDT/prepare.
[  OK  ]  Create ./DSDT/precompile.
[  OK  ]  Create ./DSDT/compile.
/dev/disk0 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *512.1 GB   disk0
   1:                        EFI EFI                     369.1 MB   disk0s1
   2:       Microsoft Basic Data WinOS                   385.2 GB   disk0s2
   3:           Windows Recovery                         850.4 MB   disk0s3
   4:                  Apple_HFS macOS                   125.0 GB   disk0s4
   5:                 Apple_Boot Recovery HD             650.0 MB   disk0s5

Enter EFI's IDENTIFIER, e.g. disk0s1: disk0s1
[  OK  ]  Mount disk0s1.
[  OK  ]  Copy untouch ACPI tables.
Available touchpad kext:
[   1  ] ApplePS2SmartTouchPad
[   2  ] VoodooPS2Controller
Please choose the desired touchpad kext (1 or 2): 2
[ Note ]  Use VoodooPS2Controller.
[ ---> ]  Disassembling tables...
[  OK  ]  Disassemble tables.
[  OK  ]  Search specification tables by syscl/Yating Zhou.
[ ---> ]  Patching DSDT.dsl
[  OK  ]  Fix PARSEOP_ZERO.
[  OK  ]  Fix ADBG Error.
[  OK  ]  Rename GFX0 to IGPU.
[  OK  ]  7-series/8-series USB.
[  OK  ]  Fix USB _PRW.
[  OK  ]  Acer Aspire E1-571.
[  OK  ]  IRQ Fix.
[  OK  ]  SMBus Fix.
[  OK  ]  AC Adapter Fix.
[  OK  ]  Add MCHC.
[  OK  ]  Fix _WAK Arg0 v2.
[  OK  ]  Add IMEI.
[  OK  ]  Fix Non-zero Mutex.
[  OK  ]  OS Check Fix.
[  OK  ]  Inject Audio Info.
[  OK  ]  Rename B0D3 to HDAU.
[  OK  ]  Remove GLAN device.
[  OK  ]  iGPU TPMX to MEM2.
[  OK  ]  IMTR->TIMR, _T_x->T_x.
[  OK  ]  Insert SLPB.
[  OK  ]  Insert PMCR.
[  OK  ]  Insert PPMC.
[ ---> ]  Patching SSDT-10.dsl
[  OK  ]  _BST package size.
[  OK  ]  Rename GFX0 to IGPU.
[ ---> ]  Patching SSDT-12.dsl
[  OK  ]  Rename GFX0 to IGPU.
[  OK  ]  Rename HD4600 to Iris Pro.
[  OK  ]  Brightness fix (Haswell).
[  OK  ]  Rename B0D3 to HDAU.
[  OK  ]  Insert HDAU device (c) syscl.
[ ---> ]  Patching SSDT-13.dsl
[  OK  ]  Rename GFX0 to IGPU.
[ ---> ]  Patching SSDT-15.dsl
[  OK  ]  Remove invalid operands.
[  OK  ]  Rename GFX0 to IGPU.
[  OK  ]  Disable Nvidia card (Non-operational in OS X).
[ ---> ]  Copying tables to precompile...
[  OK  ]  Copy tables to precompile.
[ ---> ]  Copying untouched tables to ./DSDT/compile...
[  OK  ]  Copy untouched tables to ./DSDT/compile.
[ ---> ]  Compiling tables...
[  OK  ]  Compiling DSDT.
[  OK  ]  Compile DptfTa.
[  OK  ]  Compile SaSsdt.
[  OK  ]  Compile SgRef.
[  OK  ]  Compile OptRef.
[ ---> ]  Copying SSDT-rmne.aml to ./DSDT/compile...
[  OK  ]  Copy SSDT-rmne.aml to ./DSDT/compile.
[  OK  ]  Generate C-States and P-State for Intel i7-4712HQ.
[ ---> ]  Installing SSDT-m-M3800.aml to ./DSDT/compile...
[  OK  ]  Copy SSDT-m-M3800.aml to ./DSDT/compile.
[  OK  ]  Clean dynamic SSDTs.
[  OK  ]  Create /Volumes/EFI/EFI/CLOVER/ACPI/patched.
[  OK  ]  Copy tables to /Volumes/EFI/EFI/CLOVER/ACPI/patched.
[ ---> ]  Updating kexts...
[  OK  ]  Remove pervious kexts in /Volumes/EFI/EFI/CLOVER/kexts/10.12.
[  OK  ]  Update kexts from ./CLOVER/kexts/10.12.
[  OK  ]  Update kexts from ./Kexts.
[  OK  ]  Install VoodooPS2Controller.
[  OK  ]  BCM2045A0 found.
[  OK  ]  Remove redundant BT driver::BrcmPatchRAM.kext.
[FAILED]  Update /Volumes/EFI/EFI/CLOVER/drivers64UEFI/OsxFatBinaryDrv-64.efi.
cp: /Users/alin/Downloads/M3800/CLOVER/drivers64UEFI/OsxFatBinaryDrv-64.efi: No such file or directory
[ ---> ]  Installing audio...
Password:
[  OK  ]  Install audio.
[ Note ]  Set System Agent (SA) Configuration—>Graphics Configuration->DVMT Pre-Allocated->『160MB』.
[ ---> ]  Leading to lid wake on 0x0a2e0008 (c) syscl/lighting/Yating Zhou...
[  OK  ]  Lead to lid wake on 0x0a2e0008.
[  OK  ]  Generate configuration file of sleepwatcher launch daemon.
[  OK  ]  Generating script to unmount external devices before sleep (c) syscl/lighting/Yating Zhou.
[  OK  ]  Generate script to load RTWlanUSB upon sleep.
[ ---> ]  Installing external devices sleep patch...
[  OK  ]  Install sleepwatcher daemon.
[  OK  ]  Install configuration of sleepwatcher daemon.
[  OK  ]  Install sleep script.
[  OK  ]  Install wake script.
[  OK  ]  Fix the permissions of /etc/sysclusbfix.sleep.
[  OK  ]  Fix the permissions of /etc/sysclusbfix.wake.
[  OK  ]  Trigger startup service of syscl.usb.fix.
[  OK  ]  Clean up.
[ ---> ]  Rebuilding kernel extensions cache...
[  OK  ]  Rebuild kernel extensions cache.
[ Note ]  Congratulations! All operation has been completed.
[ Note ]  Reboot now. Then enjoy your OS X! -syscl/lighting/Yating Zhou @PCBeta.

**Comment by SaulGoodman1337** [comment]
Hi,
Boot in verbose with boot arg -v and Post a picture from bootlog

**Comment by mindscrambler** [comment]
Hi,
Is this crop from the end, when it freezes, conclusive enough? It's about audio drivers ? What does it mean? Thanks.
![bootlog_crop](https://cloud.githubusercontent.com/assets/28221165/25568016/84be8ece-2e02-11e7-8b74-59437b727f1b.gif)

**Comment by mindscrambler** [comment]
My booting problem was solved by activating Clover boot option PCI devices -> Insert EFI strings.
Sound and bluetooth work (and ethernet), but no wifi. Also, in About this Mac-> System report-> Graphics/Displays shows Intel Iris Pro 31MB VRAM and no hardware acceleration. Is it supposed to be like this? Whole entry is following:
Chipset Model:	Intel Iris Pro
  Type:	GPU
  Bus:	Built-In
  VRAM (Total):	31 MB
  VRAM (Dynamic, Max):	
  Vendor:	Intel (0x8086)
  Device ID:	0x0416
  Revision ID:	0x0006
  Kernel Extension Info:	No Kext Loaded
  Displays:
Display:
  Resolution:	1920 x 1080
  Pixel Depth:	32-Bit Color (ARGB8888)
  Main Display:	Yes
  Mirror:	Off
  Online:	Yes
  Automatically Adjust Brightness:	No

**Comment by johnyoonh** [comment]
@mindscrambler which wifi card are you using? Intel cards, which come with the laptop is not compatible. If you are using broadcom card, were you able to get it working?

**Comment by moxiecn** [comment]
我的显卡和你的一样31m，很慢，你解决了吗？

**Comment by syscl** [comment]
Feel free to test the new version which added support for 10.15.x
