### ISSUE TITLE
  DW1830 shows up but won't turn on wifi or bluetooth 

### ISSUE THREAD

**Issue by johnyoonh** [syscl/M3800#68]
I originally had bcm94352z and I tried every possible config.plist patch on github, but I couldn't get it working. So I bought two DW1830 (Bcm943602baed) hoping that it will work OOB and compatible with Deploy.sh
I ventured through the web, but I couldn't find the solution. It seems like this repo contains the latest kexts for everything.

I am attaching my IOReg(2.1) and system report. I am using the default confi.plist. This is not a hardware problem because I have two DW1830 cards that both fail.

[Documents.zip](https://github.com/syscl/M3800/files/1066205/Documents.zip)

**Comment by syscl** [comment]
Your Wi-Fi has already powered on, please turn it on..

syscl
