### ISSUE TITLE
upgraded 9530 screen from QHD to UHD

### ISSUE THREAD

**Issue by spud00** [syscl/M3800#69]
Hi, Syscl.
I have a XPS 9530 with i7 4712HQ 512GB SSD and QHD+ Screen. I want to replace the QHD screen to 4K as my QHD screen have light patches on it. 
1 Is it possible?
2 Will the BIOS need to change.
3 Do you place your kext in S/L/E or leave them in Clover?

**Comment by spud00** [comment]
I have successfully updated to the 4K display.  I had an issue initially with flickering screen on first boot which was resolved by hooking up to a HDMITV  and changing the resolution to 1680x945 using enable-HiDPI.sh.
I didn't need to reflash the bios as it was done with the QHD+ screen A9 bios
Could you please tell me if a need to move the next to S/L/E or leave them in Clover?. 

Thank you for your  continuous great work!

**Comment by spud00** [comment]
Only one issue. Touchscreen doesn't seem to work.  It is recognised in USB as Sysaptics Large Touch Screen
Product ID 0x2ac3 Vender ID 0x06cb.
 Any help will be appreciated.

**Comment by syscl** [comment]
Hi, no need to move kexts to SLE, but you can if you prefer.

UHD seems have some issue when use full 4K @60Hz under macOS(a limit in macOS). You can see some issues and discussions there.

As for touchscreen, I have the same issue when replace with a new Precision M3800, my touchscreen under macOS does not work. Need to figure out the solution.

syscl

**Comment by spud00** [comment]
Have you updated to HS yet? If so are you having the same issue as me.
I getting black screen on boot up. External monitor only works while installing.

**Comment by spud00** [comment]
How do I get the internal monitor(UHD) to be recognise in HS?

**Comment by spud00** [comment]
I think the issues are with the Brcmfirmware kext.  I Removed them from Kext folder and it boots up.
I can't get the sound to work yet.

**Comment by syscl** [comment]
thank you for your information I will refine it. I have tons of homework these days, may reply a bit slow..

syscl

**Comment by spud00** [comment]
Take your time. Home work comes first. 
I did mange to get sound at then end. the system(ie sleep. wifi) is still giltchy.
I will wait for you to update and for your fix. For now ill stay on 10.12
Thank You.

**Comment by sukia163** [comment]
兄弟，你能正常使用1920x1080 hidpi了吗?

**Comment by syscl** [comment]
Feel free to test the new version which adds support for 10.15.x
