### ISSUE TITLE
Question about move EFI partition from external to internal hard drive

### ISSUE THREAD

**Issue by ghost** [syscl/M3800#7]
I made all my setups (quite long) using and External USB 3 for my EFI partition.

Could you confirm the steps I need to do to transfer the exact same EFI partition to my internal hard drive (i haven't install Clover app targeting my internal for the moment)

Thanks

**Comment by syscl** [comment]
Recently, I do a lot experiments on config.plist, and find some setting errors that prevent the progress of installation. That's the reason why you may have to use external monitor to execute the deploy.sh, I will fix it tomorrow ASAP. 

After the fix, maybe you can transfer the clover folder from my git as you want.
