### ISSUE TITLE
Signing framework signature

### ISSUE THREAD

**Issue by sieula** [syscl/M3800#70]
So I was having this problem that I cannot fix while patching the framework:

/System/Library/Frameworks/CoreDisplay.framework/Versions/Current/CoreDisplay: replacing existing signature
/System/Library/Frameworks/CoreDisplay.framework/Versions/Current/CoreDisplay: code object is not signed at all
In subcomponent: /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay.tbd

And then when I restart the display is blank. Any ideas?

**Comment by syscl** [comment]
Because you enable full SIP. Please try the latest deploy.sh and Clover in my git repo, the above commands are not require any more.
