### ISSUE TITLE
10.12.6 for M3800, I met some problems

### ISSUE THREAD

**Issue by mathguru** [syscl/M3800#71]
Firstly, thanks for your excellent work, your script is very good and smart.
I'm totally newbie for Hackintosh, just learn it three days before by surfing pcbeta.com.
After several failures, I finally installed 10.12.6 in my M3800 (together with win10, ubuntu ), but I still have several problems need your help or instruction.
1. No audio output.

2. Some Shortcuts don't work, for example, F2 F3 for audio(maybe caused by no audio  device) .

3. Wakeup problem. When I press the power button, the screen is closed (I don't know laptop sleep or not), then I press the power button again, screen is lighted, but the touchpad does't work anymore, keyborad works also fine. 

4. As we know there are webdriver method for Nvidia graphic card, can we use it for K1100M? 

thanks and wish your reply

**Comment by spud00** [comment]
I had similar issues with sound. My issues were fixed by booting without caches and rebuild caches.

**Comment by mathguru** [comment]
@spud00 thanks for your reply, do u use @syscl 's clover? I use it but I can't find the "boot without cashes" item in the clover-booting page after I press space button. Can u share your method about booting without cashes? 
Thanks, dude

**Comment by spud00** [comment]
Yes I do 
On the clover boot press space bar and use -f

**Comment by mathguru** [comment]
@spud00 , thanks for your help.
1st,  I tried to follow your instruction, but I can't find where to use -f in clover boot page (neither with space bar pressed nor in clover options). 
2nd, I want to setup it by clover configurator in mac os, failed again.
3rd, Now I try to modify the config.plist manually in win10, try to add -f in the Boot Args, can boot mac well but I don't it works or not, because there is also no audio in mac.
the whole process is very frustrating.

**Comment by spud00** [comment]
The other way you can boot with out it..
Boot as normally 
Use clover configurer to open your config.plist and edit the system parameters
https://clover-wiki.zetam.org/Configuration/SystemParameters#NoCaches
Save config.plist
Reboot.
Use kext wizard to rebuild caches.
Open config.plist and select boot with caches.
Save.
Reboot.
Hopefully that's helps

**Comment by mathguru** [comment]
@spud00 thanks 
finally I fix it by updating clover to 4243

**Comment by sukia163** [comment]
我安装10.12.6，网卡型号和你一样，问题也和你一样，请教如何解决声音，wifi和蓝牙等问题，我弄了很久没解决。

**Comment by syscl** [comment]
Feel free to try the latest repo, which addressed the problems on 10.15.x
