### ISSUE TITLE
请问下部署的时候有报错，然后重启的时候就卡住了，什么原因呢？

### ISSUE THREAD

**Issue by deanmphnet** [syscl/M3800#73]
![1](https://user-images.githubusercontent.com/33190910/32140632-c7633eb2-bca2-11e7-8f0b-9fe6ac6626f8.jpg)
配置是4702的cpu，网卡还是intel的，主板里面屏蔽了，用的是usb的网卡，不知道是不是这个原因，系统安装的sierra10.12的

**Comment by syscl** [comment]
在clover按下f4然后再执行

**Comment by deanmphnet** [comment]
我把clover安装到硬盘的efi区，然后用你的clover替换掉原来的，然后重启的时候按了F4，进系统，下载这个项目里面的内容，执行部署，但仍然是这个失败信息，后面重启后，就卡住了，不知道为何
机器也是M3800的，刷了你提供的qhd的解锁bios
系统我是在vmware里面刻录到U盘的，安装什么的都没问题 @syscl

**Comment by deanmphnet** [comment]
[debug信息.docx](https://github.com/syscl/M3800/files/1424895/debug.docx)
debug后，我复制过来的，有空的话，帮忙看下，还是那个6092错误 @syscl

**Comment by sukia163** [comment]
f4后必须改名dsdt-0等类似后面的-xxxx不要，再进MAC 执行sh，这里有个要点，每一次执行sh前，必须是新下载或新复制过去的m3800文件夹，绝对不能是之前运行过sh的,我己完美ok无报错，进系统完好，仅剩网卡蓝牙4K屏未能解决。

**Comment by moxiecn** [comment]
谢谢，我按您的要点再研究一下，有问题再麻烦您。
