### ISSUE TITLE
在deploy的时候，Dptfta那里报错

### ISSUE THREAD

**Issue by deanmphnet** [syscl/M3800#74]
@syscl 在deploy的时候，Dptfta这里报Failed，不知道什么原因

**Comment by deanmphnet** [comment]
@syscl 
[origin.zip](https://github.com/syscl/M3800/files/1426218/origin.zip)
[patched.zip](https://github.com/syscl/M3800/files/1426224/patched.zip)

**Comment by deanmphnet** [comment]
@syscl 以下为截图
![1](https://user-images.githubusercontent.com/33190910/32170374-40b3fbc8-bdaf-11e7-9640-cb9d91c90c72.JPG)
2个失败，不知道为什么，有空的话，帮忙看下吧，多谢多谢

**Comment by deanmphnet** [comment]
@syscl 
是不是bios的设置就参照你项目给出的那几项改就可以了？我做了几次都是这个问题，都是按照这个项目中的步骤来操作的，是不是和我用的usb网卡有关系呢，还是说哪里有什么没注意到的地方吗？系统用的是sierra 10.12.6的版本，不用usb网卡的话，DW1560网卡没办法驱动起来

真的非常希望你抽空帮我看看问题在哪里，呵呵，先谢过！

**Comment by syscl** [comment]
你好请把你的DSDT 原始的压缩传上来 我考完试和赶晚几个大的作业／项目帮你看

syscl

**Comment by deanmphnet** [comment]
@syscl 经过这几天的熟悉，我发现这个问题出在什么地方了，是因为clover下按F4提取的时候，ssdt的文件名变成了SSDT-1-ptidevc.aml，我就删了1后面的字符，变成默认的SSDT-1.aml，其他的SSDT文件一样这样去掉后面的字符，就没有报错了，但是又出现新的问题了，
![2017-11-02 6 26 48](https://user-images.githubusercontent.com/33190910/32301167-c50866c2-bf97-11e7-9654-781dddedd48f.png) 
有个失败，是不是和显卡补丁有关的啊，很奇怪呢

**Comment by syscl** [comment]
那个问题 应该跟你SIP有关。把SIP完全关闭了吧

**Comment by deanmphnet** [comment]
如你所说，确实是sip的问题，关闭后，一切正常通过，太棒了！！
我还想问下，这个外接hdmi可以使用嘛？触摸屏还是不能用，thunderbolt好像不识别，这些不知道有解决办法没呢？

**Comment by deanmphnet** [comment]
@syscl 
嗯，HDMI接口外接无反应，不知道是不是和我的配置有关？

**Comment by sukia163** [comment]
@syscl 我己全部sh无错误，触摸屏我的正常能用，但4k不能原生支持，会黑屏，调小分辩率正常，读卡器不工作，网卡由于不是94352z所以网淘中，读卡器是否和网卡有关？

**Comment by deanmphnet** [comment]
@sukia163 读卡器是无解的，和网卡无关，网卡的话bcm的这个确定可以用的，我自己就是，你是xps15的么？什么型号呢？

**Comment by sukia163** [comment]
@deanmphnet 读卡器无论10.xx哪个版本都不行吗?我是Xps 15 9530

**Comment by deanmphnet** [comment]
@sukia163 读卡器我的M3800走的是pcie总线，无解的

**Comment by syscl** [comment]
@deanmphnet 请尝试我目录中的SD卡驱动看能否使用。
