### ISSUE TITLE
10.27 update of Clover failed at 10.12.6 fresh install.

### ISSUE THREAD

**Issue by mathguru** [syscl/M3800#76]
When I was digging of install of 10.13 at M3800, I met a lots of failure. So I decided back to 10.12.6 and establish a MAC environment to study ssdt patching.
But the 10.27 version of Clover failed to enable Intel graphic card. Does it caused by update of IntelGraphicsFixup.kext ?
the former Clover works fine.

**Comment by syscl** [comment]
Feel free to try the latest 10.15.x.
