### ISSUE TITLE
xps 9530 在deploy的时候出现错误

### ISSUE THREAD

**Issue by sukia163** [syscl/M3800#77]
xps 9530 是否能通用m3800的sh?

**Comment by deanmphnet** [comment]
应该是可以的，你得贴下你报错的信息是什么，这几天syscl 好像比较忙，大家互相帮助下先

**Comment by sukia163** [comment]
deanmphnet兄弟，我装的是10.11.6，BIOS己改，过程十分顺利，像装白苹果一样，esp盘的efi也打入了四叶草启动(没有在其他盘装四叶草)，装完能进苹果系统，但网络(bcm943228)，声音，快捷键都无法使用，运行脚本的错误我一会贴上来，我是否应该装10.12.6

**Comment by sukia163** [comment]
最新进度，改了esp no name名为EFI再运行.sh脚本没发现错误了，但进苹果系统卡进度条在中间，没任何提示，不知下一步该如何做了，求助

**Comment by sukia163** [comment]
己全部通过没错误，但wifi不行bcm943228,4k屏也无法开启

**Comment by sukia163** [comment]
读卡器无法工作

**Comment by syscl** [comment]
@sukia163 请尝试我github下刚更新的读卡器驱动

syscl

**Comment by sukia163** [comment]
@syscl 找不到文件在哪？

**Comment by syscl** [comment]
Hi, 在我的GitHub目录有一个sinetech的项目
