### ISSUE TITLE
求助，94328Z黑苹果是否驱动无解，A09 UHD的bios打SH后4K分辨率黑屏，没打SH时能4K

### ISSUE THREAD

**Issue by sukia163** [syscl/M3800#78]
求助，BCM94328Z黑苹果是否驱动无解，如果是，现在最适合黑苹果性价比的m.2网卡是哪款，求告知。

A09 UHD的bios打SH后4K分辨率黑屏，没打SH时能4K，请问应该如何才能打开不黑屏呢，10.11.6系统下，求告知，谢谢了。

**Comment by mathguru** [comment]
我的无线网卡是BCM94352Z, 用原来自带的找不到WiFi网卡。我用以下代码替代原来的解决了WiFi问题。
My WiFi card is BCM94352Z, unfortunately when I reinstall 10.12.6, WiFi card can't be found. By using the following patch instead of the original one, WiFi problem was fixed.
```
<dict>
             <key>Comment</key>
             <string>AirPortBrcm4360 - fcvo</string>
             <key>Disabled</key>
             <false/>
             <key>Find</key>
              <data>
              gflSqgAAdSk=
              </data>
              <key>Name</key>
              <string>AirPortBrcm4360</string>
              <key>Replace</key>
              <data>
              gflSqgAAZpA=
              </data>
</dict>
```

**Comment by sukia163** [comment]
@mathguru 改config.plist吗?

**Comment by mathguru** [comment]
是的，你可以试试。不保证对你的卡有用。
config.plist里把原来的部分替换掉。

**Comment by sukia163** [comment]
@mathguru 十分感谢

**Comment by sukia163** [comment]
@mathguru 替换了无效果阿，dw1560 94352z,是否要打fcvo补丁，如果是，它在哪里可以下载？

**Comment by sukia163** [comment]
@mathguru DW1560 94352ZAE_3 我实在没有办法了，用了屏蔽针脚的方式，希望能驱动，直播中。。。

**Comment by sukia163** [comment]
结果是屏蔽针脚，完成可行正常wifi

**Comment by mathguru** [comment]
能用就好，截止目前，我还不理解什么是屏蔽阵脚。

**Comment by sukia163** [comment]
@mathguru 用透明胶把DW1560（BCM94352Z）的其中两个物理针脚粘起来，让这两个针脚不能接触工作，原生能驱动DW1560，在WIN10和OSX下都能正常工作，减少了许多驱动上面的麻烦。

**Comment by sukia163** [comment]
@mathguru 用透明胶把DW1560（BCM94352Z）的其中两个物理针脚粘起来，让这两个针脚不能接触工作，原生能驱动DW1560，在WIN10和OSX下都能正常工作，不用改CONFIG减少了许多驱动上面的麻烦。估计同为DW1560，能是有硬件上的版本不同的。所以用这种方式最省事。

**Comment by sukia163** [comment]
@mathguru 另外我退回去10.11.6了，10.12.X的触摸版只能当MOUSE用，实在是感觉不方便阿。

**Comment by syscl** [comment]
你好请选择使用VoodooPS2的驱动，我的脚本里面有提供。
