### ISSUE TITLE
Some problem in installation may be about the graphyics

### ISSUE THREAD

**Issue by lncken** [syscl/M3800#8]
This is the second time I take chances to install the os x on my Dell m3800 .And it failed like usual.After selecting the install option in clover.But it will stop at the line contains  'IOBluetoothHCIController'.And this time I search the Internet again.Many people said it may be something wrong about the clover config about the Graphics.And I have try a lot.But it seems didn't work .So I come here for help.If U can help me just reply me or send  a e-mail to admin@lncken.tk.thx.

**Comment by syscl** [comment]
Try to change ig-platform-id to 0 and Inject Intel = false. I will later refine the config.plist. 

Thx for your reply. But I will go home tomorrow.

BTW, what's your spec and settings?

**Comment by lncken** [comment]
Thx for your reply. The spec and settings is as follow:
Intel i7 4702HQ
8GB*2 ELDIPDA 1600
Seagate ST500LM00
Liteonit lmt-256l9m-11
NViDIA Quardo K1100M (2GB)
Intel Dual Band Wireless-AC 7260.
It's the early version .I bought it in 2014.

**Comment by syscl** [comment]
Do you flash the patch bios (A10) and set DVMT allocated to 128MB, disable CFG lock ...?

**Comment by lncken** [comment]
Yes .I have do all this work ready.

**Comment by lncken** [comment]
Oh no .I just check out my bios settings.The version of the bios is A09 and I had patch it .

**Comment by syscl** [comment]
Em, try my clover folder and set Inject Intel = False, ig-platform-id=0, boot without cache, and wait for a while. 

Wait for your reply:)

**Comment by lncken** [comment]
Ok.I will try it tomorrow .And will the version of the bios take influnence to the installation?Thanks for your help.Have agood dream.Good night.

**Comment by syscl** [comment]
Ok, I will refine the folder ASAP. Don't worry. Nite.

**Comment by lncken** [comment]
Many thanks .Good night.

**Comment by lncken** [comment]
I tried again this morning with y your clover folder and set Inject Intel = False, ig-platform-id=0, boot without cache. It still stop at the line contains  'IOBluetoothHCIController'.And I checked out my bios settings again ,they are all in place.I am so comfused. Did I need to remove something in the installation disk?If I need ?Which things should I need to remove?Wait for your reply.

**Comment by lncken** [comment]
BTW,I think maybe the error may have conncetion to my bluetooth .My WIFI+Bluetooth is Intel,not bcm.And I know that yours is the bcm.

**Comment by syscl** [comment]
Umm, you can remove any Fake**.kext under /EFI/CLOVER/kexts/10.11 which may prevent OS X let you in. 

Intel AC 7260 can't be powered by any exist kext till now, hence I replace it with DW1560(ngff BCM94352z)

Maybe, I have to remove any kext patch about Bluetooth.

**Comment by lncken** [comment]
I just check the config.plist. The lines follow may be the reason of the problem I met now .
<dict>
                                <key>Comment</key>
                                <string>AirPortBrcm4360 5ghz</string>
                                <key>Find</key>
                                <data>QYP8/3QsSA==</data>
                                <key>Name</key>
                                <string>AirPortBrcm4360</string>
                                <key>Replace</key>
                                <data>ZscGVVPrKw==</data>
                        </dict>

<dict>
                                <key>Comment</key>
                                <string>IOBluetoothFamily - Continuity &amp; Hand-off</string>
                                <key>Find</key>
                                <data>SIXAdFwPt0gQg8kEg/kGdVBIiw==</data>
                                <key>Name</key>
                                <string>IOBluetoothFamily</string>
                                <key>Replace</key>
                                <data>PsaDvAIAAAJBvg8AAADpTgAAAA==</data>
                        </dict>
Am I right? Wait for your reply.

**Comment by syscl** [comment]
Yep, you can remove this two patches and see if it works.

**Comment by lncken** [comment]
And should I remove any folder in the kexts?

**Comment by syscl** [comment]
Try remove "BrcmFirmwareData.kext
BrcmPatchRAM2.kext
FakePCIID_Broadcom_WiFi.kext"

**Comment by lncken** [comment]
Just now I update my bios to the newest version A10. But when I am in version A09.The bios was patched.Now I can't enter the bios settings .When I press F2 ,the pc just lose any response.And I am so worry now .How can I fix it?

**Comment by lncken** [comment]
But I still can start my m3800 and enter the system .It seems just enter any settings of the bios.

**Comment by syscl** [comment]
Flash the newest BIOS from Dell.com, and dump the your bios by AFU Utility under my Git/M3800/unlocked bios/AFUWinx64/AFUWINGUI.exe. 

Then patch it.

**Comment by syscl** [comment]
Now I've updated the deploy.sh with some exciting improvement, try it and see the change. :)
