### ISSUE TITLE
我的hdmi外接显示器还是无反应，求助！！

### ISSUE THREAD

**Issue by deanmphnet** [syscl/M3800#80]
@syscl 
现在就是hdmi外接显示器还是不行，不知道什么原因，能帮我看看么？谢谢了
![image](https://user-images.githubusercontent.com/33190910/32736825-62678166-c8d3-11e7-8daa-8b11fda06287.png)
声音里面也没有hdmi的选项
dp端口也不行
触摸屏有办法驱动起来么？？
另外，喇叭好像有爆音，就是有时候会突然的“啪”一声

麻烦syscl了，百忙中帮忙看看吧，多谢🙏

**Comment by sukia163** [comment]
触摸屏我的正常，xps15 9530

**Comment by deanmphnet** [comment]
你的系统是哪个版本的？不是10.12版本的吧，应该是低版本的吧

**Comment by sukia163** [comment]
@deanmphnet 对，所以我退回了11.11.6，10.12.X的触摸版不好用阿。

**Comment by mathguru** [comment]
@sukia163 我的触摸板也不好用，蓝牙也是坏的。我改用有线鼠标了。一了百了。

**Comment by deanmphnet** [comment]
@mathguru ，蓝牙可以驱动起来的，我的可以用的

**Comment by syscl** [comment]
@sukia163 你好，能否提供一下您的ioreg和系统报告的保存信息，因为我新的XPS/Precision触摸屏在Mac下不能用。

十分感谢。

**Comment by syscl** [comment]
@deanmphnet 你好什么版本的系统？

**Comment by sukia163** [comment]
@syscl 能否提供一下您的ioreg和系统报告的保存信息,我不懂是哪些信息阿？

**Comment by syscl** [comment]
你好 准备登机了没有Wi-Fi，ioreg方法如下https://www.tonymacx86.com/threads/guide-how-to-make-a-copy-of-ioreg.58368/

而系统报告打开后，在左上角选择文件-》另存为即可.

谢谢

**Comment by sukia163** [comment]
@syscl 请查收，这是11.11.6的系统报告和ioreg
[系统报告.zip](https://github.com/syscl/M3800/files/1655537/default.zip)

**Comment by deanmphnet** [comment]
@syscl 我现在的是10.12.6 hdmi口外接显示器无反应

**Comment by syscl** [comment]
OK十分感谢，我会考虑写一个KEXT来解决这个问题的。
