### ISSUE TITLE
ApplePS2SmartTouchPad自定义一至五指触摸板动作

### ISSUE THREAD

**Issue by sukia163** [syscl/M3800#81]
@syscl 大神等有有空看看这帖，如果能集成起来M3800和XPS 15 9530，应该就更厉害了。http://bbs.pcbeta.com/viewthread-1766484-1-1.html

**Comment by sukia163** [comment]
这里还有个多指不需要驱动小技术，看到的分享给大家http://bbs.pcbeta.com/viewthread-1739476-1-1.html

**Comment by syscl** [comment]
你好在10.12以及后续的系统请使用VoodooPS2
