### ISSUE TITLE
bios禁用独显成功! 4K屏hidpi成功。

### ISSUE THREAD

**Issue by sukia163** [syscl/M3800#84]
@syscl 我xps15 9530 10.11.6， bios选igfx成功禁独显，为省电和散热，可以成功进入系统，无需重装重运行脚本，无发现bug。hidpi有本网网友(手机打字没找到名字，感谢)提示:m3800可用1919x1080hidpi正常稳定。我xps15 9530测试最高是1912x1076hidpi,但个人觉得1912x1075hidpi最清晰，画质感动哭了。至此xps 9530在11系统(感觉目前最好)上除读卡器外己完美，非常感谢@syscl和本网的两位网友🙏🙏🙏希望未来13能更好!

**Comment by syscl** [comment]
十分感谢你的反馈。

我会在稍后和sinteck讨论关于sd 卡的事情。

**Comment by sukia163** [comment]
@syscl 10.11.6最新发现，声音有时休眠后会无声，要重启电脑才正常，休眠后有时又会出现。hdmi外接也有时不能工作，要重新运行deploy.sh后才又正常，但过后又会失效，未能找到原因。
