### ISSUE TITLE
10.12.4 耳机没有声音

### ISSUE THREAD

**Issue by fiorentinaID** [syscl/M3800#85]
@syscl  用了您的驱动，声音没有问题，但是插上耳机没有声音。
看了之前的帖子的方法就是休眠一分钟以上再开启，有的时候耳机有声音，有的时候没有。
问您一下，现在有有吗更好的解决方案？谢谢！

**Comment by syscl** [comment]
请重新使用脚本更新一遍。

启动插上耳机有这个bug，所以开机的时候不要插耳机。等进入系统再插入。
