### ISSUE TITLE
声卡不能驱动

### ISSUE THREAD

**Issue by moxiecn** [syscl/M3800#89]
10.11.6(15G31)之前deploy之后重启声卡是正常的，最近重装了10.11.6升级到15g20015小版本之后重新下载了M3800目录，运行deploy之后其它都是正常只有声卡无法驱动，后来装了voodoohda2.8.7声卡可以驱动但只能用本机扬声器，插卡耳机全是杂音。不知道什么原因。

**Comment by syscl** [comment]
请删除voodoohda，已经修复声卡显卡以及ACPI的bug。
