### ISSUE TITLE
The dummy kext for HDA may not inject ConfigData

### ISSUE THREAD

**Issue by PMheart** [syscl/M3800#9]
Well.You know who I am. :-)
To be reminded,
I do NOT suggest you inject ConfigData in DummyHDA's Info.plist.
You should make another kext for this or inject ConfigData in FakeSMC's Info.plist due to my ConfigData cannot  be injected(ALC887). I inject ConfigData in FakeSMC's Info.plist.
The DummyHDA just inject PathMap...

THIS IS ONLY MY EXPERIENCE,FEEL FREE TO CLOSE IT.

**Comment by syscl** [comment]
Thx Angel, there's some problem with such injection Dummy kext: the language in SysPre/Audio is incorrect under OS X 10.11.4 Beta 5, however, output/input seems OK. 

Any idea about a better way to power the sound card? U know I'm really afraid of the sound card which causes my tragedy experience.

**Comment by syscl** [comment]
I do not use FakeSMC.kext to inject Congfigdata, instead, I use vobro's method to create a totally new HDA according to current system. But this cause the lang problem in SysPre/Audio. 

My next step is to create a separate Configdata (dummy kext) to inject kext located in /EFI/Clover/kexts/10.11/, and xml/zml under /L_/E_/ .

**Comment by PMheart** [comment]
Well.
You should reinstall vanilla AppleHDA.kext.
Then inject ConfigData in FakeSMC's Info.plist.
Then just like I previously said,only inject PathMap in DummyHDA.
Additionally,you'd better use a DummyHDA which is made based on a previous AppleHDA.
Finally,you can change the original match name "xml.zl" to "zml.zl" or any name you like :-) Don't forget that you must add a KextPatch in Config.plist.

**Comment by syscl** [comment]
I've done that, the reason why I updated to the newest public beta system is because I have to test the new HDA, hence I remove any previous HDA before update by the following commands:

``` sh
sudo rm -rf /L*/E*/*.kext
```

``` sh
sudo rm -rf /S*/L*/E*/AppleHDA.kext
```

.

**Comment by PMheart** [comment]
Do NOT do that!
You previously asked for my help.
Do NOT remove all kexts under LE!
And why you remove vanilla AppleHDA...

**Comment by syscl** [comment]
U must forget, Apple will update those extensions as well as IOkit. That's why the package of OS X is so large.

**Comment by PMheart** [comment]
Oops...
I completely forgot it...
And I suggest you inject ConfigData in FakeSMC's Info.plist then inject PathMap in a dummy kext.
I'd like to sleep...:-)

// 英语彻底废了。。

**Comment by syscl** [comment]
Nite, not a problem, lol

**Comment by PMheart** [comment]
Once sth. goes better,let me know whatever Social Networking Apps like QQ or Facebook Messenger.
And I will keep online:-)

**Comment by PMheart** [comment]
Try to downgrade to OS X El Capitan 10.11.3 (build 15D21) and use vanilla AppleHDA then make a dummy kext just inject PathMap and install FakeSMC (ConfigData included) to LE.

Then feedback...

**Comment by syscl** [comment]
Seems there's more research have to be done on AppleHDA.kext.

**Comment by PMheart** [comment]
Hmm...
I think Apple may only change the build version but not change the binary file or others...

**Comment by syscl** [comment]
Audio problem may be fixed by the totally new way from vit9696, time will tell.

**Comment by PMheart** [comment]
Yep. :-)
And I fully forgot this issue...
