### ISSUE TITLE
10.13.5 Graphic Acceleration not Working

### ISSUE THREAD

**Issue by Byron657** [syscl/M3800#91]
@syscl can you please update the script for macOS 10.13.5? The script is not able to patch the graphic!
Thanks for your awesome work tho, I hope you will continue to update the repo :)

**Comment by syscl** [comment]
Thank you I will.

**Comment by syscl** [comment]
@Byron657 Please try the latest kexts folder under the ```Clover```, it will give you fully working graphics! And don't forget to update the config.plist, it will fix the HDMI display issue #87 .
