### ISSUE TITLE
升级10.13.4后睡眠一直有问题

### ISSUE THREAD

**Issue by machangpeng** [syscl/M3800#92]
我在升级10.13.4后睡眠一直有问题，合上笔记本没有反应不能睡眠，直接点击睡眠过一会后就无法进系统了，键盘背光灯还是亮的，就是系统再也无法进入。只能强制关机重新开机。不知道有没有人遇到过类似问题，有没有解决办法。

**Comment by syscl** [comment]
@machangpeng 请尝试最新的Clover/kexts/others下面的```EnableLidwake```, 我已经修复了这个问题。

syscl

**Comment by syscl** [comment]
@machangpeng 如果觉得有效请给[这个](https://github.com/syscl/EnableLidWake)项目点赞，也可以持续从这个项目下载最新的源码.

谢谢!
syscl

**Comment by machangpeng** [comment]
@syscl  感谢技术支持，一直都在用你的这个项目，已经点赞啦。不过睡眠问题我按照你上面说的重新下了整个项目，也加上了EnableLidwake.kext并重新做了deploy.sh，但是问题依旧，然后将EnableLidwake.kext放入Extensions并重建缓存重启系统也不行。现在状态依然是笔记本合上不休眠，点击菜单里的睡眠后要等一段时间才会彻底关机，然后按开机键屏幕变亮，播放的音乐还在继续播放，但就是无法看到系统界面。

**Comment by machangpeng** [comment]
我发现蓝牙一直处于未驱动状态，这个跟休眠是不是有关系？

**Comment by syscl** [comment]
@machangpeng 我测试了一下自己的机子 睡眠在10.13.5上面没有问题 很有可能跟ACPI那块deploy没成功有关 Clover上游合并了rehabman的改动之后 貌似就一直有问题 我没来得记看源码做了什么 但是我会想办把这个有”问题”的改动修复。。

syscl

**Comment by machangpeng** [comment]
@syscl 好的，辛苦啦，那我就坐等你的好消息啦，对了，端午节快乐！

**Comment by syscl** [comment]
请尝试最新的更新，已经添加10.15的支持，解决睡眠唤醒。
