### ISSUE TITLE
10.13.5 全新安装时运行Deploy.sh中途会有Failed提示

### ISSUE THREAD

**Issue by LynnTong** [syscl/M3800#93]
xps9530
bios：A09
运行脚本途中，在编译Dptf和SaSs时会提示错误。重启发现，独显未屏蔽。
替换10.12.5正常工作的patched aml，可以正常屏蔽独显。

**Comment by LynnTong** [comment]
[FAILED]  Compile DptfTa.
Error    6092 - Could not open file "/Users/lynn/M3800/DSDT/precompile/.dsl" (Source Input) - No such file or directory


Intel ACPI Component Architecture
ASL+ Optimizing Compiler version 20160422-64(RM)
Copyright (c) 2000 - 2016 Intel Corporation

[FAILED]  Compile SaSsdt.
Error    6092 - Could not open file "/Users/lynn/M3800/DSDT/precompile/.dsl" (Source Input) - No such file or directory


Intel ACPI Component Architecture
ASL+ Optimizing Compiler version 20160422-64(RM)
Copyright (c) 2000 - 2016 Intel Corporation

**Comment by LynnTong** [comment]
解决了。替换旧版本clover提取的origin文件夹替换后再运行Deploy就ok。

**Comment by AKA-KC** [comment]
我也出现了这个问题....可我没有旧的Origin怎么办?

**Comment by LynnTong** [comment]
建议用旧版本的clover提取。

**Comment by AKA-KC** [comment]
能发我一个么?还了硬盘....格式了没备份

**Comment by LynnTong** [comment]
你是9530还是3800

**Comment by AKA-KC** [comment]
M3800

**Comment by syscl** [comment]
Hmm我希望今晚能推一个修复吧

**Comment by AKA-KC** [comment]
大佬说好的修复捏.....捂脸

**Comment by syscl** [comment]
已经修复，请尝试最新的deploy以及我更新的Clover目录。
