### ISSUE TITLE
M3800按照教程刷bios成砖了，很慌

### ISSUE THREAD

**Issue by zuoyuan333** [syscl/M3800#96]
M3800按照教程刷bios成砖了，很慌

**Comment by syscl** [comment]
别慌 有恢复的教程的。请参阅Dell官网。

**Comment by JOKENIS** [comment]
请问你怎么恢复了？我也是和你情况一样，我刷了这个M3800_QHD_A12_patched.bin重启后成了砖头，有解决的方法吗？
