### ISSUE TITLE
BIOS Step 4

### ISSUE THREAD

**Issue by SkyMacToch** [syscl/M3800#99]
Hello,
Thank you for what you offer !
I have a dell m3800 and my bios is in version A11. I am stuck in step 4, I do not understand how to flash the bios can you give more details?
You have to run AFUWINGUI.EXE or AFUWINx64.EXE and what should you do next? is what should I do with M3800_QHD_A11_patched.bin?

**Comment by syscl** [comment]
Download all the files from https://github.com/syscl/M3800/tree/M3800/unlocked%20BIOS/AFUWINx64 and also the bios https://github.com/syscl/M3800/blob/M3800/unlocked%20BIOS/M3800_QHD_A11_patched.bin.

Then under Windows 7/8, execute the AFUWINx64 command to flash your BIOS. Please note that your laptop is M3800 with QHD+ and note flashing bios will brick your laptop if you did not follow the steps correctly!!

**Comment by SkyMacToch** [comment]
Thank you for your reply.

I'm not in QHD +, from what I see in the windows display setting, I am in Full-HD Touch 1920 * 1080, do you have another .bin?

And for AFUWINx64 if I understood correctly I must launch it in a CMD, can you tell me the exact command to launch it with the .bin? 
And what happens after launching the command, my pc will restart and normally in the bios it should have other options?
